### PR TITLE
Support base docker registry login to increase pull limit

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Pulling image from dockerhub reaches limit during release
- Enabling base_docker_registry_credential to increase this limit
- Related Issue: runtimes/backlog/issues/1234

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Links (hyc_grinder):
- ubi checkpoint: 35883  restore: 35887
- ubu checkpoint: 35881  restore: 35886
- pingperf checkpoint: 35882 restore: 35888

**Review by llxia — APPROVED** [review]
Thanks @LongyuZhang

**Comment by llxia** [comment]
@smlambert could you review this PR? It is currently blocking the CRIU testing. Thanks.

**Review by smlambert — APPROVED** [review]
👍

**Pull request merged**
