### PR TITLE
Release build node and only ask node to do Copy artifacts

### PR DESCRIPTION
**Pull request by sophia-guo**
This way the build agent won't need to be hold until the whole job is done.

Part of https://github.com/adoptium/ci-jenkins-pipelines/issues/384

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Grinder https://ci.eclipse.org/temurin-compliance/job/AQA_Test_Pipeline/70/
https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/88/

**Review by smlambert — APPROVED** [review]
Thanks @sophia-guo !

**Comment by sophia-guo** [comment]
The jobs are always pending and do not execute in Eclipse temurin jenkins https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1731

**Review by zdtsw — APPROVED** [review]

**Comment by llxia** [comment]
AQA_Test_Pipeline/27/ - waiting for the build to complete

**Comment by llxia** [comment]
Update: the above build passed.
While I was testing this PR, I found a bug at https://github.com/adoptium/aqa-tests/blob/53127a9ac659fe1d32706fdace5d3b5c9a37faa4/buildenv/jenkins/aqaTestPipeline.groovy#L7

This means USE_TESTENV_PROPERTIES will be true regardless. This needs to be fixed. I will open a separate issue for this. 
And I will approve this PR as this bug is not related to this PR.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
