### PR TITLE
Enable serviceability_jvmti tests for 19+

### PR DESCRIPTION
**Pull request by sophia-guo**
Related with #4006 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Grinder on different platforms

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5774/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5774/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5774/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5774/

**Comment by sophia-guo** [comment]
This test case `hotspot_serviceability_jvmti` can be combined with test case [serviceability_jvmti_j9](https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L220-L250), which is specifying nativepath by `-nativepath:"$(TESTIMAGE_PATH)/hotspot/jtreg/native" ` and I don't think it works. However even if updated as $(JVM_NATIVE_OPTIONS) it probably won't work too for openj9, as openj9 may not build corresponding test libs. 

As mentioned in https://github.com/adoptium/aqa-tests/pull/3970#issuecomment-1250999986 there are 94 tests failed, which is same number of tests with hotspot if nativepath is not set correctly or testimage is missing https://ci.adoptopenjdk.net/job/Grinder/5731/testReport/

**Comment by sophia-guo** [comment]
As we may gradually enable other Loom related tests https://github.com/adoptium/aqa-tests/issues/4006#issuecomment-1278170329 in one test case, which might not work with openj9 or openj9 might not be interested in. I will leave it as is for now, which can be combined easily later if required.

**Review by smlambert — APPROVED** [review]

**Review by sxa — APPROVED** [review]
LGTM - I had assumed we were running all tests with `--enable-preview` which would cause failures in 19 but on the basis of the grinders that's not the case, so I approvel

**Pull request merged**
