### PR TITLE
Use GitHub token in issue_status.py, handle bugs.openjdk and multithreading

### PR DESCRIPTION
**Pull request by gervaisj**
Use GitHub token in issue_status.py, handle bugs.openjdk and refactor

- Group URLs for more efficient querying
- Use multithreading to quicken processing
  - 362 issues in ~8s
- Accept GitHub username + token to increase limit (see `Usage` in the [README](./scripts/disabled-tests/README.md) for details)
- Handle trackers from `bugs.openjdk.java.net`
- Exclude certain issues (1297 for now)

Fixes https://github.com/adoptium/aqa-tests/issues/3378

Signed-off-by: Jocelyn Gervais [gervaisj14@outlook.com](mailto:gervaisj14@outlook.com)

### Output samples
```json
[
  {
    "JDK_VERSION": "13",
    "JDK_IMPL": "hotspot",
    "TARGET": "jdk_custom",
    "CUSTOM_TARGET": "java/nio/channels/AsyncCloseAndInterrupt.java",
    "PLATFORM": "all_linux,all_aix",
    "ISSUE_TRACKER": "https://github.com/adoptium/aqa-tests/issues/1597",
    "ISSUE_TRACKER_STATUS": "closed"
  },
  {
    "JDK_VERSION": "13",
    "JDK_IMPL": "hotspot",
    "TARGET": "jdk_custom",
    "CUSTOM_TARGET": "java/nio/channels/AsynchronousSocketChannel/Basic.java",
    "PLATFORM": "all_windows",
    "ISSUE_TRACKER": "https://bugs.openjdk.java.net/browse/JDK-7052549",
    "ISSUE_TRACKER_STATUS": "open"
  }
]
```
- When an issue is ignored:
```
WARNING - Excluding 'https://github.com/adoptium/aqa-tests/issues/1297' due to exception segment '/aqa-tests/issues/1297'
```
- Info (`-v`) mode
```
INFO - 1/82 - Ended processing for 'https://github.com/adoptium/aqa-tests/issues/1051': CLOSED
INFO - 2/82 - Ended processing for 'https://github.com/adoptium/aqa-tests/issues/2382': OPEN
INFO - 3/82 - Ended processing for '1https://github.com/adoptium/aqa-tests/issues/16': CLOSED
...
INFO - 55/82 - Ended processing for 'https://github.com/adoptium/aqa-tests/issues/73': CLOSED
INFO - 56/82 - Ended processing for 'https://github.com/adoptium/aqa-tests/issues/2655': OPEN
ERROR - 57/82 - Uncaught exception for 'https://bugs.openjdk.java.net/browse/JDK-8031145': 401 Client Error:  for url: https://bugs.openjdk.java.net/rest/api/latest/issue/JDK-8031145
INFO - 58/82 - Ended processing for 'https://github.com/adoptium/aqa-tests/issues/115': CLOSED
INFO - 59/82 - Ended processing for 'https://github.com/adoptium/aqa-tests/issues/2665': OPEN
...
```
- Debug (`-vv`) mode
```
DEBUG - Loading JSON from <stdin>
DEBUG - Unique issue trackers found: 13
DEBUG - Starting new HTTPS connection (1): api.github.com:443
...
DEBUG - Starting new HTTPS connection (1): bugs.openjdk.java.net:443
DEBUG - https://api.github.com:443 "GET /repos/adoptium/aqa-tests/issues/1267?accept=application%2Fvnd.github.v3%2Bjson&state=all HTTP/1.1" 200 None
DEBUG - Starting new HTTPS connection (1): api.github.com:443
INFO - 1/13 - Ended processing for 'https://github.com/adoptium/aqa-tests/issues/1267': OPEN
DEBUG - https://api.github.com:443 "GET /repos/adoptium/aqa-tests/issues/1597?accept=application%2Fvnd.github.v3%2Bjson&state=all HTTP/1.1" 200 None
...
DEBUG - https://api.github.com:443 "GET /repos/adoptium/temurin-build/issues/248?accept=application%2Fvnd.github.v3%2Bjson&state=all HTTP/1.1" 200 None
INFO - 13/13 - Ended processing for 'https://github.com/adoptium/temurin-build/issues/248': CLOSED
DEBUG - Outputting JSON to <stdout>
```

### CODE REVIEW

**Comment by gervaisj** [comment]
@smlambert @llxia Ready for review!

**Review by smlambert — COMMENTED** [review]
My initial (though quick) review of this is a 👍 - will wait for the walk-through in the March 9th AQAvit mtg (as a 'deskside review') for final review / approval.

**Review by smlambert — APPROVED** [review]
Thanks for the walkthrough in today's call @gervaisj

**Review by llxia — APPROVED** [review]
Thanks @gervaisj

**Pull request merged**
