### PR TITLE
Remove jtreg duplicated ssl call

### PR DESCRIPTION
**Pull request by judovana**
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9102

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by judovana** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9151/

**Review by smlambert — CHANGES_REQUESTED** [review]
Same comment as from the churn review, https://github.com/adoptium/aqa-tests/pull/5134#pullrequestreview-1937284702

**Comment by judovana** [comment]
Returned back to  aqavit jtreg runner:
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9159
there is failure `javax.net.ssl.SSLHandshakeException: The client supported protocol versions [(D)TLS-127.23, TLSv1.2, TLSv1.1, TLSv1] are not accepted by server preferences [TLS13]` which do not look like casued by jtreg launcher... Reruning one more times.

**Comment by judovana** [comment]
Yup. second https://ci.adoptium.net/view/Test_grinder/job/Grinder/9161/ is ol

**Review by smlambert — APPROVED** [review]

**Comment by pshipton** [comment]
This seems the cause of https://github.com/eclipse-openj9/openj9/issues/19164#issuecomment-2005154548, similarly to https://github.com/adoptium/aqa-tests/pull/5134#issuecomment-2003940176

**Comment by pshipton** [comment]
Excluded the test on OpenJ9 amac via https://github.com/adoptium/aqa-tests/pull/5153

**Pull request merged**
