### PR TITLE
updating tag_version="4.1" to tag_version="netty-4.1.74.Final"

### PR DESCRIPTION
**Pull request by yinggzz**
Related to issue #3402 

Signed off: Ying Zhou

### CODE REVIEW

**Comment by yinggzz** [comment]
external test with updated tag version
with jdk11: https://ci.adoptopenjdk.net/job/Grinder/3829/ 
with jdk17: https://ci.adoptopenjdk.net/job/Grinder/3830/

**Comment by sophia-guo** [comment]
Also rerun with jdk8: https://ci.adoptopenjdk.net/job/Grinder/3840/ @yinggzz could you monitor the build and update the test result here? Thanks.

**Comment by yinggzz** [comment]
> Also rerun with jdk8: https://ci.adoptopenjdk.net/job/Grinder/3840/ @yinggzz could you monitor the build and update the test result here? Thanks.

test failed with jdk8: 
```
10:38:42  	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
10:38:42  		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
10:38:42  		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
10:38:42  		... 58 more
10:38:42  	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
10:38:42  		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:171)
10:38:42  		... 59 more
10:38:42  		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
...
10:38:43  [[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-surefire-plugin:2.22.2:test[m [1m(default-test)[m on project [36mnetty-handler[m: [1;31mThere are test failures.[m
10:38:43  [[1;31mERROR[m] [1;31m[m
10:38:43  [[1;31mERROR[m] [1;31mPlease refer to /netty/handler/target/surefire-reports for the individual test results.[m
10:38:43  [[1;31mERROR[m] [1;31mPlease refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.[m
10:38:43  [[1;31mERROR[m] -> [1m[Help 1][m
10:38:43  [[1;31mERROR[m] 
10:38:43  [[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
10:38:43  [[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
10:38:43  [[1;31mERROR[m] 
10:38:43  [[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
10:38:43  [[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
10:38:43  [[1;31mERROR[m] 
10:38:43  [[1;31mERROR[m] After correcting the problems, you can resume the build with the command
10:38:43  [[1;31mERROR[m]   [1mmvn <args> -rf :netty-handler[m
10:38:44  
10:38:44  netty_test_0_FAILED
10:38:44  
10:38:44  No DOCKERIMAGE_TAG set, tag as default 'nightly'
10:38:44  The test here is netty
10:38:44  The directory in the external.sh is netty
10:38:44  Error: No such container: netty-test
```

**Comment by yinggzz** [comment]
> @yinggzz could you take a look at the failures in your grinders, what's the failure? Is it same as without the change? I've taken a quick look that one grinder is timeout. Do you know why it's timeout? Is it because waiting for machine takes too long or tests itself take long?
> 
> The other one looks similar to #3390, which looks like mvn doesn't work well with openjdk17. Could you print out mvn -v?
> 


For test with **openjdk17** after change: failure is related to maven similar to #3990
```
16:44:06  [[1;31mERROR[m] Error executing Maven.
16:44:06  [[1;31mERROR[m] java.lang.IllegalStateException: Unable to load cache item
16:44:06  [[1;31mERROR[m] Caused by: Unable to load cache item
16:44:06  [[1;31mERROR[m] Caused by: Could not initialize class 
```

**mvn -v output:** 

```
14:59:28  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
14:59:28  [1mApache Maven 3.6.3[m
14:59:28  Maven home: /usr/share/maven
14:59:28  Java version: 17.0.3-beta, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk
14:59:28  Default locale: en_US, platform encoding: UTF8
14:59:28  OS name: "linux", version: "4.4.0-210-generic", arch: "amd64", family: "unix"
14:59:28  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
```

test with **openjdk11** result in timeout, I'm not quite sure the reason for the timeout, seem like it is due to waiting for machine taking too long.

**Review by sophia-guo — APPROVED** [review]

**Comment by sophia-guo** [comment]
Errors are known issue.

**Review by smlambert — APPROVED** [review]

**Pull request merged**
