### PR TITLE
Allow users to set docker info in AQA_Test_Pipeline

### PR DESCRIPTION
**Pull request by llxia**
resolves: https://github.com/adoptium/aqa-tests/issues/4747

### CODE REVIEW

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Comment by JasonFengJ9** [comment]
```
14:36:20  build_image:
14:36:20       [echo] Executing external.sh --build --dir criu-ubi-portable-checkpoint --tag nightly --version 11 --impl openj9 --base_docker_registry_dir 'ubi8-with-criu/linux_x86-64-ubi8-criu' --docker_registry_url docker-na.artifactory.swg-devops.com/sys-rt-docker-local --docker_args -v /home/jenkins/workspace/Test_openjdk11_j9_dev.external_x86-64_linux_imageUpload/openjdkbinary/j2sdk-image:/opt/java/openjdk 
14:36:20       [exec] The test here is criu-ubi-portable-checkpoint
14:36:20       [exec] The directory in the external.sh is criu-ubi-portable-checkpoint
14:36:20       [exec] DOCKERIMAGE_TAG nightly has been recognized.
14:36:20       [exec] Private Docker Registry login starts to obtain base Docker Image:
14:36:20       [exec] Error: Must provide --username with --password-stdin
```
`docker_registry_url` was supplied.
@llxia is this error expected?

**Comment by llxia** [comment]
[Reran](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_dev.external_x86-64_linux_imageUpload/324/) passed. `dev.external` related builds need to run with `DYNAMIC_COMPILE=true`.

**Review by JasonFengJ9 — APPROVED** [review]
LGTM

**Pull request merged**
