### PR TITLE
Modify code coverage file path to suit multiple pipelines

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Modify code coverage file path to suit multiple pipelines

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Links:
Internal_Grinder: 20107

**Comment by LongyuZhang** [comment]
@llxia @smlambert Could you review it? Thanks.

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @LongyuZhang !

**Pull request merged**
