### PR TITLE
Make jck additional jtx general

### PR DESCRIPTION
**Pull request by sendaoYan**
Currently jck additional jtx only support FIPS. Make jck additional jtx general

Fixes: #3931

### CODE REVIEW

**Review by smlambert — COMMENTED** [review]
thanks @sendaoYan - as part of this change, can you also update the fipsJtxFullPath variable name to reflect that it is a more general purpose one?  perhaps testFlagJtxFullPath or featureFlagJtxFullPath ?

**Comment by sendaoYan** [comment]
> fipsJtxFullPath

Sorry, I miss the fipsJtxFullPath variable. I correct it later.

**Comment by sendaoYan** [comment]
> testFlagJtxFullPath

Done.

**Comment by llxia** [comment]
FYI https://github.com/adoptium/aqa-tests/pull/3927 is also updating the same file. If this PR or #3927 is merged first, we will likely see merge conflicts in the other one.

**Comment by smlambert** [comment]
Apologies @sendaoYan - you will need to resolve the conflicts in your PR.

**Pull request merged**
