### PR TITLE
Only copy necessary artifact from upstream test jobs

### LINKED ISSUE #3672: Using the rerun link will get unnecessarily extra tap files
Using the rerun link will get unnecessarily extra tap files, which always set the grinder job failed even if the build actually succeeds.  

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4640/
Screen Shot 2022-05-18 at 10 15 14 AM

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix #3672 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by llxia** [comment]
Could you run a Ginder? Thanks

**Comment by sophia-guo** [comment]
Grinder : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4658/

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4659/

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
