### PR TITLE
Capture both out1 + out2 sections of junit report XML

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves backlog/issues/532

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test: internal/Grinder/15401/

**Review by JasonFengJ9 — APPROVED** [review]
LGTM

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @Mesbah-Alam !

**Pull request merged**
