### PR TITLE
jck-runtime-api-java_nio jck test target to special level

### LINKED ISSUE #2770: jck-runtime-api-java_nio jck test target should get put into special level
This target contains testcases that require jckservices machine to be present, so the target should get moved from extended to special, since it requires special setup.  (similar to: https://github.com/adoptium/aqa-tests/pull/2746).

### PR DESCRIPTION
**Pull request by Aryamanz29**
Closes #2770

### CODE REVIEW

**Comment by Aryamanz29** [comment]
Why checks are failing, I've also checked ECA agreement :thinking:

**Review by smlambert — APPROVED** [review]
thanks @Aryamanz29 !  ECA check now passing.  :)

**Comment by Mesbah-Alam** [comment]
Can this PR wait until after the Release week? Otherwise we'd have to run `jck-runtime-api-java_nio jck` manually to ensure compliance.

**Comment by smlambert** [comment]
Yes, we will merge it after the code freeze lifts.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Merging this PR as part of the set of low risk PRs that will make the remainder of the release go more smoothly.

**Pull request merged**
