### PR TITLE
Add timestamps to openjdk_tests and remove timestampes from JenkinsfileBase

### PR DESCRIPTION
**Pull request by YeeSkywalker**
Sign out: Yee Lin
Date: Mar. 12th, 2022
Close: #3396

### CODE REVIEW

**Comment by YeeSkywalker** [comment]
The Grinder test for add timestamps covers all section: [Grinder 3828](https://ci.adoptopenjdk.net/job/Grinder/3828/console)

**Comment by llxia** [comment]
Dynamic: https://ci.adoptopenjdk.net/job/Grinder/3859/

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
@YeeSkywalker could resolve the merge conflicts? Thanks

**Comment by smlambert** [comment]
Conflict needs to be resolved before it can be merged.

**Comment by llxia** [comment]
@YeeSkywalker There are a couple of changes that went in for the test pipeline scripts. It may be easier for you to start with a clean workspace and apply your changes again.

**Comment by YeeSkywalker** [comment]
Have opened a new pr with clean workspace: [#3501 ](https://github.com/adoptium/aqa-tests/pull/3501)

**Pull request closed without merging**
