### PR TITLE
Added the if statement for checkTags.sh

### PR DESCRIPTION
**Pull request by ftm-2005**
Added the if statement for checkTags.sh
Fixes: #5298 
Signed-off-by: Fatima Yaser A A Al-Kharaz <fyk@andrew.cmu.edu>

### CODE REVIEW

**Comment by ftm-2005** [comment]
i fixed the issue #5298

**Review by karianna — APPROVED** [review]

**Comment by llxia** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10035/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10036

**Comment by llxia** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10037/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10038/

**Review by llxia — APPROVED** [review]
Thanks @ftm-2005

**Pull request merged**
