### PR TITLE
Convert HOME to unix path on windows

### PR DESCRIPTION
**Pull request by llxia**
fixes: https://github.com/eclipse-openj9/openj9/issues/16433

Signed-off-by: Lan Xia <Lan_Xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
xlinux: [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/30206/console)

```
00:01:36.562  getOpenjdk:
00:01:36.562       [echo]  Using user specified repo and branch
00:01:36.562       [exec] git clone --depth 1 -q --reference-if-able /home/jenkins/openjdk_cache -b openj9 git@github.com:ibmruntimes/openj9-openjdk-jdk17 openjdktemp
00:01:53.610       [exec] Check sha in openjdk-jdk and store the info in /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/SHA.txt
```


Windows: [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/30205/console)
```
00:04:54.906  build:
00:04:54.906       [echo] pathconvert C:\cygwin64\home\jenkins to unix on windows. home.unix is set to C:/cygwin64/home/jenkins
00:04:54.906  
... 
00:04:57.312  getOpenjdk:
00:04:57.312       [echo]  Using user specified repo and branch
00:04:57.734       [exec] git clone --depth 1 -q --reference-if-able C:/cygwin64/home/jenkins/openjdk_cache -b openj9 git@github.com:ibmruntimes/openj9-openjdk-jdk17 openjdktemp
00:11:26.193       [exec] Check sha in openjdk-jdk and store the info in C:/Users/jenkins/workspace/Grinder/aqa-tests//TKG/SHA.txt
```

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@llxia GH Action Failures.

**Comment by llxia** [comment]
GH action failures are not related to this PR. There are different failures. Some are specific test failures, which are also in the regular nightly. For example:
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_x86-64_linux/242/console
https://github.com/adoptium/aqa-tests/actions/runs/3677727803/jobs/6220086908

This PR only set the git clone reference cache path to unix on windows. It is for performance purposes. Even if the path is wrong, git will ignore it.

**Review by smlambert — APPROVED** [review]
I will follow-up to open an issue to simplify our GH PR testing also (to avoid confusion, speed up runs).

**Pull request merged**
