### PR TITLE
Filter Linux docker container processes from terminationProcess.sh on host node

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
The terminationProcess.sh end of test suite job process cleanup can incorrectly terminate any docker container processes running under the same user uid on the host node. Docker does not isolate container node processes from the parent host.

Fixes temurin-compliance issue 282

This PR for Linux nodes queries the cgroup info to determine if the node is a host or docker container, if a host node then it will filter any processes with a /docker cgroup.

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Test Grinders:
- x64Linux container: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6279/console
- x64Linux host node: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6281/console

**Comment by andrew-m-leonard** [comment]
Tested on temurin compliance ci as well.

**Review by smlambert — APPROVED** [review]
👍

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Pull request merged**
