### PR TITLE
Get REPO and SHA for system repos

### PR DESCRIPTION
**Pull request by psaunderualberta**
Calling the 'addTestenvProperties' macro defined in TKG/scripts/build_test.xml. Need to get that PR approved so proper testing on my end can occur.

### CODE REVIEW

**Comment by llxia** [comment]
Please update the title to be more descriptive. For example, Get REPO and SHA for openjdk and system repos

**Comment by llxia** [comment]
Please remove the change in get.sh and launch Grinder to validate the PR. Thanks

**Comment by psaunderualberta** [comment]
[Grinder without USE_TESTENV_PROPERTIES](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2677)
[Grinder with USE_TESTENV_PROPERTIES](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2678)

**Comment by llxia** [comment]
If this PR is ready to review, please move it out of the draft. Thanks

**Comment by llxia** [comment]
Are we going to include the change for openjdk/build.xml? Or that will be in a separate PR?

**Comment by psaunderualberta** [comment]
Can you please remind me what I need to change in that file? Once I know I can add them to this PR

**Comment by llxia** [comment]
We need to call `addTestenvProperties` in https://github.com/adoptium/aqa-tests/blob/6f6c0066c2469c8b99172995b9f53dfd61df90b7/openjdk/build.xml#L326. Please note, we need to set version and impl. For example, JDK11_REPO, JDK8_OPENJ9_REPO.

I will approve PR, please open another PR for the change in openjdk/build.xml

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
This PR has to be merged together with https://github.com/adoptium/TKG/pull/252

**Review by smlambert — APPROVED** [review]
thanks @psaunderualberta !

**Comment by smlambert** [comment]
Checks failing due to needing the TKG PR to be merged in, will merge both now.

**Pull request merged**
