### PR TITLE
Update SDK_RESOURCE description in testJobTemplate

### LINKED ISSUE #2935: Update SDK_RESOURCE description in testJobTemplate
It would be nice to have `SDK_RESOURCE` description updated as following in testJobTemplate
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L289

```
Where to get sdk? nightly|releases|customized|upstream<br/>
nightly & releases pull the lastest from https://api.adoptium.net/ <br/>
If nightly / releases is selected, please provide JDK_VERSION and JDK_IMPL <br/>
If customized is selected, please provide CUSTOMIZED_SDK_URL (and CUSTOMIZED_SDK_URL_CREDENTIAL_ID if the URL has restricted access)<br/>
If upstream is selected, please provide UPSTREAM_JOB_NAME and UPSTREAM_JOB_NUMBER <br/>
```

### PR DESCRIPTION
**Pull request by zahraaliaghazadeh**
Fixes #2935

### CODE REVIEW

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/work-in-progress/job/WIP_Test_Job_Auto_Gen/52/

**Comment by llxia** [comment]
image

**Review by llxia — APPROVED** [review]
Thanks @zahraaliaghazadeh

**Review by smlambert — APPROVED** [review]
thanks @zahraaliaghazadeh !

**Pull request merged**
