### PR TITLE
Update dev.external workflow for CRIU

### PR DESCRIPTION
**Pull request by llxia**
resolves: https://github.com/adoptium/aqa-tests/issues/4465

### CODE REVIEW

**Comment by llxia** [comment]
image

[TRSS link](http://trssrtp1.fyre.ibm.com/resultSummary?parentId=6446e09591a98a07f601d11b)
[Jenkins link](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_dev.external_x86-64_linux/34/)

**Comment by llxia** [comment]
This PR should be merged after https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/155

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by AdamBrousseau** [comment]
Dependent PR is merged.

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
