### PR TITLE
Move NUM_LIST to the outermost scope that includes a reference

### PR DESCRIPTION
**Pull request by keithc-ca**
See https://github.com/adoptium/aqa-tests/pull/5511#discussion_r1723928123.

### CODE REVIEW

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Trying to run testing is failing with `Exception: groovy.lang.MissingPropertyException: No such property: NUM_LIST for class: groovy.lang.Binding`. I expect it will continue to do so until this or another fix is merged.

**Comment by JasonFengJ9** [comment]
Verification run - https://openj9-jenkins.osuosl.org/job/Grinder/3769/console
It looks good.

**Review by JasonFengJ9 — APPROVED** [review]

**Comment by llxia** [comment]
This needs to be backported into https://github.com/adoptium/aqa-tests/tree/v1.0.3-release as the original problematic PR is in the v1.0.3 branch: https://github.com/adoptium/aqa-tests/pull/5517

**Comment by llxia** [comment]
back port: https://github.com/adoptium/aqa-tests/pull/5519

**Pull request merged**
