### PR TITLE
add CURL_OPTS in get.sh

### PR DESCRIPTION
**Pull request by llxia**
Allow user to set CURL_OPTS for debugging purposes.
This param is optional. It sets options for running the curl command. The default value is s.
s - for silent
v - for verbose

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Internal:
- Grinder/19356: no CURL_OPTS value. Default `s` is used.
```
00:00:34.042  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/lastSuccessfulBuild/artifact/workspace/target/ibm-semeru-open-jdk_ppc64_aix_JDK17U_2021-11-05-04-01.tar.gz
```
- Grinder/19351: CURL_OPTS=v. Details are printed when running curl command
```
00:00:31.433  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSkv --user ****:**** https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/lastSuccessfulBuild/artifact/workspace/target/ibm-semeru-open-jdk_ppc64_aix_JDK17U_2021-11-05-04-01.tar.gz
00:00:31.433    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
00:00:31.433                                   Dload  Upload   Total   Spent    Left  Speed
00:00:31.433  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 9.208.18.95:443...
  ...
  ```

**Comment by smlambert** [comment]
Do we foresee having to enable any other debugging options on any other tooling... rather than introduce a new parameter for each case, do we have a debugging option that turns on verbose for curl and other options for other tools?

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
> do we have a debugging option that turns on verbose for curl and other options for other tools?

I am not aware of any atm, at least not in get.sh. 
I agree to have a general debugging option. I think we can change this param to a general debugging option (likely a boolean) once we identify other needs.

**Review by smlambert — APPROVED** [review]

**Pull request merged**
