### PR TITLE
Delete machineRes.groovy

### LINKED ISSUE #4227: Remove unused file machineRes.groovy
As we arrived at a different solution for relating multiple Jenkins test nodes (via Nested node for server and client testing https://github.com/adoptium/aqa-tests/pull/3364), we do not need a separate [buildenv/jenkins/machineRes.groovy](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/machineRes.groovy) file.  It can and should be deleted.

### PR DESCRIPTION
**Pull request by SajjanYadav**
Fixes #4227 

I am new to open source contributing and found this as an issue to deleting this file named machineRes.groovy

### CODE REVIEW

**Comment by smlambert** [comment]
Thanks @SajjanYadav - please sign the ECA https://adoptium.net/docs/eca-sign-off/, to unblock this PR (and eclipsefdn/eca check will pass).

**Comment by SajjanYadav** [comment]
> Thanks @SajjanYadav - please sign the ECA https://adoptium.net/docs/eca-sign-off/, to unblock this PR (and eclipsefdn/eca check will pass).

Sir i have signed the ECA

**Review by smlambert — APPROVED** [review]

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Thanks @SajjanYadav !

**Comment by SajjanYadav** [comment]
> Thanks @SajjanYadav !

Thanks to you sir :)

**Pull request merged**
