### PR TITLE
Support comma separated list of test flags

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves backlog/issues/1017
Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Tests with TEST_FLAG=fips (where ",criu" gets added automatically) : Grinder/30843 (Green. Note in console log how fips related exclude file is being picked up). 

Test with no TEST_FLAG given: Grinder/30844 (Green).

**Review by llxia — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]
Not sure if we want a proper logger

**Comment by Mesbah-Alam** [comment]
@karianna - adding a proper logger to JavaTestRunner would be a nice to have! Will keep that in mind. Thanks!

**Pull request merged**
