### PR TITLE
Add docker registry parameters for jenkins

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Add docker registry parameters for jenkins
- Depends on PR: https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/87
- Related Issue: ibm_github/runtimes/backlog/issues/879

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test with Docker Registry parameters in grinder: hyc_grinder 27427

**Comment by llxia** [comment]
Please add `DOCKER_REGISTRY_URL` and `DOCKER_REGISTRY_URL_CREDENTIAL_ID` in https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate. Thanks

**Comment by LongyuZhang** [comment]
The two parameters have been added to `testJobTemplate` as suggested. Thanks.

**Review by llxia — APPROVED** [review]
Thanks @LongyuZhang

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
