### PR TITLE
Prerequisites for Quarkus 2+ is Java 11.

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Running quaku_quickstart 2.7.2.Final with jdk8 got 

```
12:30:16      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
12:30:16  Caused by: java.lang.UnsupportedClassVersionError: io/quarkus/maven/components/BootstrapSessionListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

```

It turns out `prerequisites for Quarkus 2+ is Java 11`, 

```
        <quarkus.platform.version>2.7.5.Final</quarkus.platform.version>
        <maven.compiler.source>11</maven.compiler.source>
```

**Comment by sophia-guo** [comment]
Fix the issue mentioned https://github.com/adoptium/aqa-tests/pull/3506#issuecomment-1083317340

https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/577/console

**Review by smlambert — APPROVED** [review]
aha!

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
