### PR TITLE
Dockerfile folder has been removed.

### PR DESCRIPTION
**Pull request by sophia-guo**
Related #3478 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by smlambert** [comment]
Not sure its yet removed for system-test and functional-test, those still need to be dealt with... still contain a static Dockerfile (see recent comment https://github.com/adoptium/aqa-tests/issues/3466#issuecomment-1074264422 about handling those in another cleanup pass...).

**Comment by sophia-guo** [comment]
This fails the job with target sanity or extended or specific third party targets (except for system and function, which have been set as 'special' level. That is the issue will be hidden there if we don't run special)
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/554/

**Comment by smlambert** [comment]
Agree that we will not hit an immediate problem because we are not running system-test or functional-test atm, though @llxia and @LongyuZhang intend to use those targets to verify CRIU prototypes for OpenJ9 testing.

**Review by smlambert — APPROVED** [review]
LGTM (but noting that we will need to finish the removal of this directory from system-test and functional-test when we start using them).

**Review by llxia — APPROVED** [review]

**Pull request merged**
