### PR TITLE
Rename openjdkbinary folder to jdkbinary

### PR DESCRIPTION
**Pull request by llxia**
related: backlog/issues/1243

### CODE REVIEW

**Comment by llxia** [comment]
jdk_math: https://ci.adoptium.net/view/Test_grinder/job/Grinder/7925/
floatSanityTests: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2999/

**Comment by llxia** [comment]
FYI @JasonFengJ9 @pshipton

**Comment by JasonFengJ9** [comment]
There are a few `openjdkbinary` references in other repos:
https://github.com/adoptium/aqa-test-tools
https://github.com/adoptium/temurin-build
Should those be updated as well?

**Comment by llxia** [comment]
related: https://github.com/adoptium/aqa-tests/pull/4837

**Review by JasonFengJ9 — APPROVED** [review]
Verified in a few grinders, looks good.

Thanks @llxia

**Review by karianna — APPROVED** [review]

**Pull request merged**
