### PR TITLE
Support zos for AQA releases

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
zos: [Grinder link](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/20413/)
xlinux: Grinder link

**Comment by llxia** [comment]
FYI @pshipton I will port this PR into the release branch (v0.8.0-release) after the merge. Then I will update testenv_zos.properties to use `ibm-jdk11-zOS-11.0.14` in v0.8.0-release.

**Comment by pshipton** [comment]
What happens when you don't specify JDK11_OPENJ9_REPO and BRANCH in the testenv file? I'm thinking that the builds already specify the OPENJ9 and JDK-X repos and branches. Maybe the testenv only needs to specify TCK, STF, and systemtest repos/branches, and OpenJ9 and OpenJDK comes from the build itself. This would work better for personal builds, ifix builds, etc.

**Comment by llxia** [comment]
> What happens when you don't specify JDK11_OPENJ9_REPO and BRANCH in the testenv file? I'm thinking that the builds already specify the OPENJ9 and JDK-X repos and branches. Maybe the testenv only needs to specify TCK, STF, and systemtest repos/branches, and OpenJ9 and OpenJDK comes from the build itself. This would work better for personal builds, ifix builds, etc.


Currently, we do not handle both job parameters (test repos) and testenv file. It is either-or. 
If JDK11_OPENJ9_REPO and BRANCH are not in testenv, I think they will be set to empty, then the default repo and branch in openjdk/build.xml will be used (https://github.com/ibmruntimes/openj9-openjdk-jdk11.git)

**Review by smlambert — APPROVED** [review]
LGTM

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
