### PR TITLE
 Update tag_version=19.1.0.Final to tag_version=26.0.1.Final

### PR DESCRIPTION
**Pull request by abhijeetjejurkar**
Updated tag_version=19.1.0.Final to tag_version=26.0.1.Final in https://github.com/adoptium/aqa-tests/blob/master/external/wildfly/test.properties#L5

Fixes: #3409

Signed-off-by: Abhijeet Jejurkar <abhijeet.jejurkar2@gmail.com>

### CODE REVIEW

**Comment by abhijeetjejurkar** [comment]
Also Please Assign me this issue.

**Comment by smlambert** [comment]
Please update the description of this PR to not include the statement "This Update is Done in AQAvit v0.8.0".  We are reviewing for merging into master, not into the v0.8.0 branch

**Comment by abhijeetjejurkar** [comment]
> Please update the description of this PR to not include the statement "This Update is Done in AQAvit v0.8.0". We are reviewing for merging into master, not into the v0.8.0 branch

Okay👍, Done

**Review by sophia-guo — APPROVED** [review]

**Review by smlambert — APPROVED** [review]
👍

**Pull request merged**
