### PR TITLE
Update parallel TEST_TIME logic

### PR DESCRIPTION
**Pull request by renfeiw**
- enable TEST_TIME option
- if the TEST_TIME is not achievable, set NUM_MACHINES to machine limit

### CODE REVIEW

**Comment by renfeiw** [comment]
grinder: Grinder/33436/

**Comment by llxia** [comment]
FYI [v0.9.8-release](https://github.com/adoptium/aqa-tests/tree/v0.9.8-release) is created.

**Comment by renfeiw** [comment]
Grinder_TKG/1908

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM 👍

**Pull request merged**
