### PR TITLE
Update to testjob_template parameters' comments

### PR DESCRIPTION
**Pull request by Martins-O-U**
Fixes https://github.com/AdoptOpenJDK/openjdk-tests/issues/2546

### CODE REVIEW

**Comment by Martins-O-U** [comment]
Hello @smlambert, I have created a PR for this task. Kindly assist with reviewing for a possible merge or update.  
Thanks.

**Review by smlambert — CHANGES_REQUESTED** [review]

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Tested via: https://ci.adoptopenjdk.net/view/work-in-progress/job/WIP_Test_Job_Auto_Gen/47/ that generates jobs with these updates:
Screen Shot 2021-04-30 at 1 03 23 PM
Screen Shot 2021-04-30 at 1 04 17 PM

**Comment by Martins-O-U** [comment]
I have signed the ECA. Thanks

**Comment by Martins-O-U** [comment]
Hello @smlambert, please this PR has not yet been merged.

**Comment by smlambert** [comment]
I am well aware @Martins-O-U - PRs in this repo require 2 reviewers.  I am waiting on a 2nd review before it is merged.  You can still count it towards your contributions (as per the [note in the outreachy slack channel](https://adoptium.slack.com/archives/C01PUE50XQQ/p1619545324164200)).

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
