### PR TITLE
Updated github urls to refer to eclipse-openj9

### PR DESCRIPTION
**Pull request by SAY-droid427**
Fixes https://github.com/adoptium/aqa-tests/issues/2551

### CODE REVIEW

**Comment by SAY-droid427** [comment]
@llxia Please review the PR and let me know if I have missed any url reference

**Comment by llxia** [comment]
Thanks @SAY-droid427 could you also update issue links in playlist? For example:
https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L154

**Comment by SAY-droid427** [comment]
@llxia I will do it right away!

**Comment by SAY-droid427** [comment]
@lxia OI have updated all the links now

**Comment by llxia** [comment]
That's ok. I will squash it when merging the PR. Please do squash it in the future. Thanks

**Comment by llxia** [comment]
run aqa --help

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/513/

**Review by llxia — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
