### PR TITLE
Update jdk link

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Update jdk link to remove _criu in pipeline name
- Related Issue: runtimes_backlog/1100

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Link: hyc_jenkins/job/CRIU_Image_Upload/343

**Review by llxia — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
@LongyuZhang could you back port this in https://github.com/adoptium/aqa-tests/tree/v0.9.7-release? Thanks

**Pull request merged**
