### PR TITLE
Support rerun failed jdk | hotspot testcases in Grinder with jdk_custom | hotspot_custom target

### LINKED ISSUE #4265: Add 'Rerun in Grinder using jdk_custom | hotspot_custom with failed testcases'
openjdk failed test case information has been added to tap file. jdk_custom supports multiple testcases. It would be nice to support `Rerun in Grinder using jdk_custom with failed testcases`. Would be nice to do the same for hotspot_custom targets

If buildlist = openjdk and test build has multiple targets failed with multiple test cases. Link 'Rerun failed jdk test cases in Grinder with jdk_custom target' or | and `Rerun failed hotspot test cases in Grinder with hotspot_custom target` will be added depends on the status of failed openjdk test targets.

For examplehttps://ci.adoptopenjdk.net/job/Test_openjdk19_hs_extended.openjdk_x86-64_windows_testList_0/44/artifact/aqa-tests/TKG/output_16740678676868/Test_openjdk19_hs_extended.openjdk_x86-64_windows_testList_0.tap/*view*/

When support 'Rerun failed jdk test cases in Grinder with jdk_custom target' the grinder would be refilled like the build:
https://ci.adoptopenjdk.net/job/Grinder/6396/ with target = jdk_custom and CUSTOM_TARGET = tools/jpackage/share/PerUserCfgTest.java tools/jpackage/share/ServiceTest.java tools/jpackage/windows/Win8282351Test.java  testcases ( testcases recorded in the tap file)

### PR DESCRIPTION
**Pull request by sophia-guo**
close #4265 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Depends on https://github.com/adoptium/TKG/pull/397 #4283

**Comment by sophia-guo** [comment]
Grinder with jdk_custom https://ci.adoptopenjdk.net/job/Grinder/6527/
with normal test target https://ci.adoptopenjdk.net/job/Grinder/6526/
Grinder with windows https://ci.adoptopenjdk.net/job/Grinder/6506/

**Comment by sophia-guo** [comment]
Parallel grinder: https://ci.adoptopenjdk.net/job/Grinder/6532/
No parallel grinder: https://ci.adoptopenjdk.net/job/Grinder/6534/

**Review by llxia — APPROVED** [review]
LGTM

**Comment by sophia-guo** [comment]
There are two links - jdk_custom and hotspot_custom. [Rerun failed jdk test cases in Grinder with jdk_custom target](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=sophia-guo%3AcustomU&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fsophia-guo%2Fopenjdk-tests.git&RERUN_ITERATIONS=0&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=customU&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk19u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk19u%2Fjdk19u-release-linux-arm-temurin&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=sun/security/lib/cacerts/VerifyCACerts.java+sun/security/ssl/X509TrustManagerImpl/Symantec/Distrust.java+jdk/net/ExtendedSocketOption/DontFragmentTest.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-19.0.2%2B7_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&OPENJDK_SHA=&NUM_MACHINES=3&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=2&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=Dynamic)
[Rerun failed hotspot test cases in Grinder with hotspot_custom target](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=hotspot_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=sophia-guo%3AcustomU&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fsophia-guo%2Fopenjdk-tests.git&RERUN_ITERATIONS=0&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=customU&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk19u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk19u%2Fjdk19u-release-linux-arm-temurin&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=compiler/vectorapi/reshape/TestVectorCastNeon.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-19.0.2%2B7_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&OPENJDK_SHA=&NUM_MACHINES=3&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=2&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=Dynamic)

That three tests belong to jdk group and are set in jdk_custom link.

**Comment by smlambert** [comment]
Ah, thanks @sophia-guo, I should have paid more attention!  Thanks for these Grinders!

**Review by smlambert — APPROVED** [review]
👍

**Pull request merged**
