### PR TITLE
Add aot-portable test

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Add aot-portable test
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/15740

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Please ensure this PR contains only aot change. Thanks

**Comment by LongyuZhang** [comment]
The criu related tests are modified to add additional `--docker_registry_required "true"` in this PR, since previous `load` function in `external.sh` only pulls image after log into private docker registry, which is not needed for aot-portable test (pull from dockerhub directly).

Test Links:
- aot_portable-test captures the error `AOT header validation failed: Processor incompatible` (semeru docker has not been updated [link](https://hub.docker.com/r/amd64/ibm-semeru-runtimes/tags)): hyc 26820
- CRIU ubu_checkpoint (hyc 26824)  ubu_restore (hyc 26829)  ubi_checkpoint (hyc 26825)  ubi_restore (hyc 26828)

**Comment by llxia** [comment]
If we use `run` (instead of `load`), will the logic be simpler?

**Comment by llxia** [comment]
Talked with Longyu, and we decided to use `load` for this PR. As we are supporting more use cases (i.e., testing JDK, testing docker image, creating docker image, etc), we will have a design discussion for external testing workflow in general.

**Comment by LongyuZhang** [comment]
New Test Links (hyc_grinder):
- aot test: 26841 (captured `AOT header validation failed` since semeru docker image hasn't updated, [link](https://hub.docker.com/r/amd64/ibm-semeru-runtimes/tags))
- ubu checkpoint: 26839
- ubu restore:  26845
- ubi checkpoint: 26842
- ubi restore:  26843

**Review by llxia — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
