### PR TITLE
Exclude testing in Graal JIT mode

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Review by smlambert — APPROVED** [review]

**Comment by sophia-guo** [comment]
related with https://github.com/adoptium/adoptium/issues/63, which will not fix the issue of jvm_compiler. However according to the console output, it is the right way.

**Comment by tellison** [comment]
I can't leave a review (no write access to repo?), but looks good to me :-)

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/pull/2791#issuecomment-894825898 that is odd, all committers should have this access and @tellison you are a committer (https://projects.eclipse.org/projects/adoptium.aqavit/who).  We will have to follow-up with Eclipse for why you are missing permissions.

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
