### PR TITLE
Update MockitoTest's build.xml to use the same jdk version as to playlist.xml

### PR DESCRIPTION
**Pull request by sophiaxu0424**
- Issue to https://github.com/adoptium/infrastructure/issues/3043

### CODE REVIEW

**Comment by sophiaxu0424** [comment]
Running with nightly jdk11, and it passed:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40988/console

Still need to dive into the case with jdk8 for fixing the 55.0 version error in build.xml

**Comment by sophiaxu0424** [comment]
Trying to testing on jdk8, but both failed with origin master branch, and this PR branch, expected SKIPPED, but keeps failing.
Testing with origin master branch, nightly jdk8, for expected: SKIPPED
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41000/ failed

Testing with this PR issue3043 branch, nightly jdk8 expected: SKIPPED
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41001/ failed

**Comment by sophiaxu0424** [comment]
@llxia @LongyuZhang Would you please kindly check and see if other test should be prepared? TIA!

**Review by LongyuZhang — COMMENTED** [review]
Since this PR is to fix JDK8 build failure, the grinder test needs to run with JDK8 other tests (reproduce what caused failure in the origin issue) to prove this change fixed it.

**Comment by sophiaxu0424** [comment]
> Since this PR is to fix JDK8 build failure, the grinder test needs to run with JDK8 other tests (reproduce what caused failure in the origin issue) to prove this change fixed it.

Hi Longyu,

The original mockito test case with jdk11+ limitations, has compile failure and can't be skipped.
while when we remove the jdk11+ limitation, the reported issue ``` class file has wrong version 55.0, should be 52.0``` could be reproduced, and this reported issue came from the mockito (third-party) not our side, and we are waiting for them to fix.

I am wondering that maybe we should add this jdk8 to disabled list to avoid this compile failure? please advice as well. thanks!

**Comment by LongyuZhang** [comment]
@sophiaxu0424 To validate this changes fixed the JDK8 problem, you can run your branch in a grinder with
- DYNAMIC_COMPILE set to unchecked;
- JDK is JDK 8
- Target is `floatSanityTests`
Then make sure this grinder passed, and the console contains info of either MockitoTest skipped or not shown at all. Thanks.

**Review by llxia — APPROVED** [review]
LGTM

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
