### PR TITLE
Auto rerun test build in FAILURE status

### PR DESCRIPTION
**Pull request by llxia**
This PR will auto-rerun the child test build in FAILURE status (Part 1). To enable this feature, params.RERUN_FAILURE needs to be true.
We will enable the parent test build of rerun in Part 2.

related: https://github.com/adoptium/aqa-tests/issues/5346

### CODE REVIEW

**Comment by llxia** [comment]
- [RERUN_FAILURE = true and parallel](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44710/): 
    - Aborted one [child build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/4798/)  (to mimic the FAILURE build scenario)
    - [rerun](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0_rerun/5/) got generated as expected
- [RERUN_FAILURE = true, RERUN_ITERATIONS = 1 and parallel](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44712/):
    - Did not abort the build
    - Rerun was triggered due to RERUN_ITERATIONS = 1
- [RERUN_FAILURE = true, RERUN_ITERATIONS = 1 and parallel](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44713/) 

- [test in AQA test pipeline](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/AQA_Test_Pipeline_Release/170/) (- rerun in child [builds)](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/897/)
image


TRSS:

image

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Since I have no visibility of tests run on hyc Jenkins, from your testing, what is the difference between 
[RERUN_FAILURE = true, RERUN_ITERATIONS = 1 and parallel](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44712/) Grinder/44712
[RERUN_FAILURE = true, RERUN_ITERATIONS = 1 and parallel](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44713/) Grinder/44713

**Comment by llxia** [comment]
Sorry, Grinder links expired. I think the second link has a typo. It is for scenario `RERUN_FAILURE = false, RERUN_ITERATIONS = 1 and parallel`

**Comment by smlambert** [comment]
Public test runs:

JDK11, x64Linux and ppc64Aix:
[AQA_Test_Pipeline/381/](https://ci.adoptium.net/view/Test_grinder/job/AQA_Test_Pipeline/381/) - RERUN_FAILURE=true, RERUN_ITERATIONS=1,PARALLEL=none
[AQA_Test_Pipeline/382/](https://ci.adoptium.net/view/Test_grinder/job/AQA_Test_Pipeline/382/) - RERUN_FAILURE=true, RERUN_ITERATIONS=0,PARALLEL=none
[AQA_Test_Pipeline/383/](https://ci.adoptium.net/view/Test_grinder/job/AQA_Test_Pipeline/383/) - RERUN_FAILURE=false, RERUN_ITERATIONS=0,PARALLEL=none

JDK17, x86-32_windows,s390x_linux:
[AQA_Test_Pipeline/384/](https://ci.adoptium.net/view/Test_grinder/job/AQA_Test_Pipeline/384/) - RERUN_FAILURE=true, RERUN_ITERATIONS=1,PARALLEL=Dynamic,TEST_TIME=2

**Comment by smlambert** [comment]
I do not quite think I got all of the AQA_Test_Pipeline parameters correct, as many of the test jobs failed with 
```
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress --prune -- origin +refs/heads/autoFailureRerun:refs/remotes/origin/autoFailureRerun" returned status code 128:
stdout: 
stderr: fatal: couldn't find remote ref refs/heads/autoFailureRerun

	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2846)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2185)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)
	at PluginClassLoader for git//jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:408)
Caused: java.io.IOException
	at PluginClassLoader for git//jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:413)
	at PluginClassLoader for scm-api//jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:219)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:126)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:73)
	at PluginClassLoader for workflow-job//org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:311)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:446)
Finished: FAILURE
```
But at least, it forced test job failures, which then triggered reruns which is the functionality that I hoped the runs would demonstrate.  

TRSS instance does not show the rerun link in the tooltip, but it has not been synched in a while, so perhaps that is why.  It does show the info circle in the top corner of the chiclet in the [Grid view](https://trss.adoptium.net/resultSummary?parentId=673d03089e1252006ed4a65e) though, indicating there was a rerun.

Screenshot 2024-11-20 at 4 16 39 PM

**Comment by llxia** [comment]
re https://github.com/adoptium/aqa-tests/pull/5747#issuecomment-2486786197, the rerun job was generated and triggered.

image

However, `LIGHT_WEIGHT_CHECKOUT` has to be set to false for running any personal repo. Otherwise, there will be an error in checking out the repo `stderr: fatal: couldn't find remote ref refs/heads/autoFailureRerun`

 Note: This PR (Step 1) does not cover rerun at the parent level (i.e., `PARALLEL=none` case). It will be covered in Step 2.

**Review by smlambert — APPROVED** [review]
AQA_Test_Pipeline runs showed reruns were triggered for failed jobs.

**Pull request merged**
