### PR TITLE
unexcluded tests related to infra/1274

### PR DESCRIPTION
**Pull request by unnati914**
Deleted the required lines and unexcluded them. 

Let me know if any change is required :)

### CODE REVIEW

**Comment by smlambert** [comment]
Hi @unnati914 - can you please sign the Eclipse Contributor Agreement ([ECA](https://www.eclipse.org/legal/ECA.php))  using the same email as your commit to ensure the eclipsefdn/eca check passes.

**Comment by unnati914** [comment]
Done. Thanks! Could you please review my PR as today is the last day to fill mentor application for GHC OSD. I know this is not right and I should wait but I can't do nothing 😔.
Thanks again

**Comment by unnati914** [comment]
Ohh I did one mistake I used my primary mail (which is not associated with Github) 😔 Could anything can be done now? My mail id is chhabraunnati324@gmail.com

**Comment by unnati914** [comment]
I have updated the ECA. Still its showing error. Please look into it. I have updated my gmail account and linked it with GitHub

**Comment by unnati914** [comment]
thank you its done

**Comment by smlambert** [comment]
run aqa --help

**Comment by llxia** [comment]
The run aqa failure is related to the issue https://github.com/adoptium/aqa-tests/issues/2697

**Comment by unnati914** [comment]
is there anything i need to correct?

**Comment by llxia** [comment]
@unnati914 the run aqa failure is not related to your PR. But if you have time, you are more than welcome to fix #2697. As #2697 can unblock running `run aqa`. The fix for #2697 is very straightforward. Thanks :)

**Comment by unnati914** [comment]
actually i have to fill application for osd 2021 mentor application and one merged pr is compulsory. only 3 hrs to go for deadline

**Comment by unnati914** [comment]
i can fix it.. if that is needed

**Comment by llxia** [comment]
FYI PR for fixing #2697 is created: https://github.com/adoptium/aqa-tests/pull/2733

**Comment by unnati914** [comment]
could i fill the application if issue is solved?

**Comment by smlambert** [comment]
Yes, please focus on your application @unnati914

**Comment by unnati914** [comment]
I'm very sorry for the trouble caused 😔. This is my first contribution to Adoptium and what a mess I have created on the reviewers. So sorry 😞. My PR is okay to be merged right?

**Comment by smlambert** [comment]
Yes we will merge your PR today @unnati914 once we finish testing it.

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
Grinder jobs at:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1097
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1098

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
