### PR TITLE
Add CRIU PingPerf test

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: Lan Xia <Lan_Xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
[internal/Grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/30942/)

**Comment by llxia** [comment]
This is the initial version of CRIU PingPerf. Next steps:
- replace the SDK with nightly SDK
- add upload the image in criu_pingPerf_testCreateRestoreImageOnly

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
