### PR TITLE
Add function of generating and archiving Code Coverage Report

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Add function of generating and archiving Code Coverage Report
- Current version only works with linux platforms
- Jenkins machine with lcov is required (Label_Addition "ci.role.codecov")
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/12133

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
@llxia @smlambert Could you review it? Thanks.

**Comment by LongyuZhang** [comment]
Test links on hyc_jenkins:
- with `CODE_COVERAGE` checked, on machine with label `ci.role.codecov`, and Code Coverage Report archived in Artifacts: 19589
- normal build without checking `CODE_COVERAGE` and label `ci.role.codecov`: 19590

**Comment by llxia** [comment]
Could you please resolve the conflicts? Thanks

**Comment by LongyuZhang** [comment]
> Could you please resolve the conflicts? Thanks

Updated. Will re-test to make sure the new version works. Thanks.

**Comment by LongyuZhang** [comment]
New Test links on hyc_jenkins:
- with CODE_COVERAGE checked, on machine with label ci.role.codecov, and Code Coverage Report archived in Artifacts: 19817
- normal build without checking CODE_COVERAGE and label ci.role.codecov: 19820

**Comment by LongyuZhang** [comment]
New Test links on hyc_jenkins:

with CODE_COVERAGE checked, on machine with label ci.role.codecov, and Code Coverage Report archived in Artifacts: 19845
normal build without checking CODE_COVERAGE and label ci.role.codecov: 19846

**Review by llxia — APPROVED** [review]
Thanks @LongyuZhang

**Review by smlambert — APPROVED** [review]
LGTM 👍

**Pull request merged**
