### PR TITLE
Set dynamic compile for external functional test

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Set dynamic compile for external functional test

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
@llxia @renfeiw Could you review it? Thanks.

**Comment by LongyuZhang** [comment]
Test Links:
external docker criu_test: hyc_grinder 25489

**Review by llxia — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
