### PR TITLE
Ensure JCK remote url matches what user passed

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Related runtimes infrastructure#8332

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Tested here
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34923/

**Comment by AdamBrousseau** [comment]
@llxia for review.

**Comment by llxia** [comment]
All tests failed in Grinder - `Error: Unable to access jarfile /home/jenkins/jck_root/JCK11-unzipped/JCK-compiler-11a/lib/javatest.jar`

```
15:21:17  stage-jck-material:
15:21:18       [echo] LocalSHA = --55913a011cb3156675e1219adc3b6fe07a86e57b--
15:21:18       [echo] RemoteSHA= --b509f106e7735453269bd7d6ea91503848080955	refs/heads/main--
15:21:18       [echo] Ensure JCK repo remoteUrl in cache matches what user asked for...
15:21:18       [echo] Existing remoteURL: 'github.ibm.com:prodroy89/JCK11-unzipped.git'
15:21:18       [echo] Updating remoteUrl to: 'git@github.ibm.com:runtimes/JCK11-unzipped.git'
15:21:18       [echo] Updating /home/jenkins/jck_root/JCK11-unzipped with latest...
15:21:25       [exec] From github.ibm.com:runtimes/JCK11-unzipped
15:21:25       [exec]  * branch                    main       -> FETCH_HEAD
15:21:36       [exec] 
15:21:36       [exec] *** Please tell me who you are.
15:21:36       [exec] 
15:21:36       [exec] Run
15:21:36       [exec] 
15:21:36       [exec]   git config --global user.email "you@example.com"
15:21:36       [exec]   git config --global user.name "Your Name"
15:21:36       [exec] 
15:21:36       [exec] to set your account's default identity.
15:21:36       [exec] Omit --global to set the identity only in this repository.
15:21:36       [exec] 
15:21:36       [exec] fatal: empty ident name (for <jenkins@paix820.rtp.raleigh.ibm.com>) not allowed
15:21:36       [exec] Result: 128
15:21:36       [echo] start building Javatest Runner and jck natives
```

**Comment by AdamBrousseau** [comment]
K I'll take a look. think I'm going to add some more echos in the reset path too.

**Comment by llxia** [comment]
Close the PR as this is obsolete.

**Pull request closed without merging**
