### PR TITLE
Updating JCK references for jck17 to jck17a

### PR DESCRIPTION
**Pull request by adamfarley**
Resolves https://github.com/adoptium/aqa-tests/issues/5748

### CODE REVIEW

**Comment by adamfarley** [comment]
May not be testable until the tck repo has changes as well. 

Working on that here: https://github.com/temurin-compliance/temurin-compliance/issues/601

**Comment by karianna** [comment]
Grinder failed...

**Comment by smlambert** [comment]
New Grinder launched at: 
https://ci.eclipse.org/temurin-compliance/job/Grinder/4647 
with different TARGET value that exists.

**Comment by adamfarley** [comment]
The new Grinder (with a valid target, good catch Shelley) has also failed.

The error is:
```
Error: Unable to access jarfile /home/jenkins/jck_root/JCK17-unzipped/JCK-runtime-17a/lib/javatest.jar
```

I [deleted the machine's JCK17 test material](https://ci.eclipse.org/temurin-compliance/job/DeleteJCKMaterials/521/) before my grinder, and the dates on the JCK17-unzipped folder reflect this:

```
Nov 28 16:56 JCK17-unzipped
```

So I think the test material we're cloning is jck17 and not jck17a. Will raise a confidential Eclipse Foundation ticket to request that change.

**Comment by adamfarley** [comment]
Changing title to WIP, as this change it not safe to merge until it has been tested, and it cannot be tested until [this confidential Eclipse issue](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5364) is resolved.

**Comment by adamfarley** [comment]
Tested as detailed in the issue. Some unit test failures, but 99% of everything passed, and nothing seemed to have trouble finding the test material.

**Review by smlambert — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Pull request merged**
