### PR TITLE
fix _SecurityTests_0 test fail

### PR DESCRIPTION
**Pull request by sendaoYan**
www.google.com can't be reache normally in CHINA. So change the test website from https://www.google.com/ to https://www2.bing.com/

Fixes: #3601

Signed-off-by: sendaoYan <yansendao.ysd@alibaba-inc.com>

### CODE REVIEW

**Comment by llxia** [comment]
Thanks @sendaoYan

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4533/

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @sendaoYan !

**Comment by sendaoYan** [comment]
Thanks @smlambert @llxia

**Pull request merged**
