### PR TITLE
Fix misleading exception of Jenkinsfile.run_parallel_tests

### PR DESCRIPTION
**Pull request by OscarQQ**
Signed-off-by: Yixin Qian <Yixin.Qian@ibm.com>
related: #2730

### CODE REVIEW

**Comment by OscarQQ** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1074/console

**Comment by llxia** [comment]
Thanks @OscarQQ for the quick response! 
Could you update the title to reflect the change? And could you run Grinder with parallel and non-parallel?

**Review by llxia — APPROVED** [review]
LGTM. Thanks @OscarQQ

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
thanks for the thorough testing via Grinders!

**Pull request merged**
