### PR TITLE
Refine concurrency logic

### PR DESCRIPTION
**Pull request by adamfarley**
This change ensures that we identify the correct memory size when running tests in containers, by setting CGMEM to be the number of memory bytes in all circumstances.

We could remove the "-lt" logic altogether, but we shouldn't because sometimes the cgroup limits are set far beyond the machine's maximum memory, for reasons we do not yet understand.

### CODE REVIEW

**Comment by adamfarley** [comment]
Linked to https://github.com/adoptium/aqa-tests/issues/5012

May not close it. Further review required. Should improve matters, though.

**Comment by adamfarley** [comment]
Testing here: https://ci.adoptium.net/job/Grinder/8831/console

**Review by jerboaa — COMMENTED** [review]
`/sys/fs/cgroup/memory/memory.limit_in_bytes` is inherently cgv1 (legacy) specific. This won't work on cgroup v2 systems. FYI.

**Comment by sxa** [comment]
Ref  Severin's comment above, `/sys/fs/cgroup/memory.max` appears to be the right thing for V2 so we ought to change that (either in this PR or a separate one)
Noting that this is a follow on to other fixes in this area under https://github.com/adoptium/aqa-tests/pull/4933 and https://github.com/adoptium/aqa-tests/pull/5035

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Review by sxa — COMMENTED** [review]
@adamfarley Because I'm paranoid about these things can you fire this off on a subset of diverse machines similar to the table at the top of https://github.com/adoptium/aqa-tests/pull/4933 to check that this won't regress anything please?

Suggest one of the PLCT RISC-V machines (4 core, 16Gb), test-sxa-armv7l-ubuntu2004-odroid-2 (8 core, 2Gb), something [running on an Ubuntu 2004 host](https://ci.adoptium.net/label/hw.dockerhost.dockerhost-skytap-ubuntu2004-ppc64le-1/) and [something on Ubuntu 22.04](https://ci.adoptium.net/label/hw.dockerhost.dockerhost-equinix-ubuntu2204-aarch64-1/) as a minimum.

**Comment by adamfarley** [comment]
> Ref Severin's comment above, `/sys/fs/cgroup/memory.max` appears to be the right thing for V2 so we ought to change that (either in this PR or a separate one) Noting that this is a follow on to other fixes in this area under #4933 and #5035

Okie dokie. Will fix.

**Comment by adamfarley** [comment]
> @adamfarley Because I'm paranoid about these things can you fire this off on a subset of diverse machines similar to the table at the top of #4933 to check that this won't regress anything please?
> 
> Suggest one of the PLCT RISC-V machines (4 core, 16Gb), test-sxa-armv7l-ubuntu2004-odroid-2 (8 core, 2Gb), something [running on an Ubuntu 2004 host](https://ci.adoptium.net/label/hw.dockerhost.dockerhost-skytap-ubuntu2004-ppc64le-1/) and [something on Ubuntu 22.04](https://ci.adoptium.net/label/hw.dockerhost.dockerhost-equinix-ubuntu2204-aarch64-1/) as a minimum.

Gotcha. Will run with the updated fix.

**Comment by adamfarley** [comment]
Ok, given that we (a) want to tolerate both memory.max AND memory.etcetcbytes, and (b) that memory.max can be both present, readable and empty, here's a proposal for the new script:

```
KMEMMB=`awk '/^MemTotal:/{print int($$2/1024)}' /proc/meminfo`; 

if [[ -r /sys/fs/cgroup/memory.max && $(cat /sys/fs/cgroup/memory.max) =~ ^[0-9]+$ ]]; 
    then CGMEM=`cat /sys/fs/cgroup/memory.max`; 
elif [[ -r /sys/fs/cgroup/memory/memory.limit_in_bytes && $(cat /sys/fs/cgroup/memory/memory.limit_in_bytes) =~ ^[0-9]+$ ]]; 
    then CGMEM=`cat /sys/fs/cgroup/memory/memory.limit_in_bytes`; 
else 
    CGMEM=`expr $${KMEMMB} \* 1024 \* 1024`; 
fi; 

CGMEMMB=`expr $${CGMEM} / 1024 / 1024`; 

if [ "$${KMEMMB}" -lt "$${CGMEMMB}" ]; then 
    echo "$${KMEMMB}"; else echo "$${CGMEMMB}"; 
fi
```

I added formatting for an easier review.

What do you think?

**Comment by adamfarley** [comment]
P.S. If I ever complain I have too much spare time, remind me of this makefile. Turning it into a bash script would remove the need to put all of this script into a single line.

**Comment by adamfarley** [comment]
Test run: https://ci.adoptium.net/job/Grinder/8832/

Will check across other machines once I know the new code works.

**Comment by jerboaa** [comment]
> Ok, given that we (a) want to tolerate both memory.max AND memory.etcetcbytes, and (b) that memory.max can be both present, readable and empty, here's a proposal for the new script:
> 
> ```
> KMEMMB=`awk '/^MemTotal:/{print int($$2/1024)}' /proc/meminfo`; 
> 
> if [[ -r /sys/fs/cgroup/memory.max && $(cat /sys/fs/cgroup/memory.max) =~ ^[0-9]+$ ]]; 
>     then CGMEM=`cat /sys/fs/cgroup/memory.max`; 
> elif [[ -r /sys/fs/cgroup/memory/memory.limit_in_bytes && $(cat /sys/fs/cgroup/memory/memory.limit_in_bytes) =~ ^[0-9]+$ ]]; 
>     then CGMEM=`cat /sys/fs/cgroup/memory/memory.limit_in_bytes`; 
> else 
>     CGMEM=`expr $${KMEMMB} \* 1024 \* 1024`; 
> fi; 
> 
> CGMEMMB=`expr $${CGMEM} / 1024 / 1024`; 
> 
> if [ "$${KMEMMB}" -lt "$${CGMEMMB}" ]; then 
>     echo "$${KMEMMB}"; else echo "$${CGMEMMB}"; 
> fi
> ```
> 
> I added formatting for an easier review.
> 
> What do you think?

You should test on the FS type on the cgroup root. In pseudo code:

```
if [ "$(stat -f --format '%T' /sys/fs/cgroup)_" == "cgroup2fs_" ]; then
   #cgroup v2 branch
else
   #cgroup v1 branch
fi
```

**Comment by adamfarley** [comment]
Ok, had a ponder and came up with this:

```
KMEMMB=`awk '/^MemTotal:/{print int($$2/1024)}' /proc/meminfo`; 

if [[ -f "/.dockerenv" ]]; then
    CGRPV=`stat -f --format '%T' /sys/fs/cgroup)`
    if [[ "_$$CGRPV" == "_cgroup2fs" ]]; then
        CGMEM=`cat /sys/fs/cgroup/memory.max`; 
    elif [[ "_$$CGRPV" == "_tmpfs" ]]; 
        then CGMEM=`cat /sys/fs/cgroup/memory/memory.limit_in_bytes`; 
    fi; 
fi;

if [[ ! $$(CGMEM) =~ ^[0-9]+$$ ]]; then
    CGMEM=`expr $${KMEMMB} \* 1024 \* 1024`; 
fi; 

CGMEMMB=`expr $${CGMEM} / 1024 / 1024`; 

if [ "$${KMEMMB}" -lt "$${CGMEMMB}" ]; then 
    echo "$${KMEMMB}"; else echo "$${CGMEMMB}"; 
fi
```

This way we:
- Check if we're in a container before running the stat command, which not all OS' have.
- Can handle things if the file is missing, unreadable, or empty.
- Don't use cgroups contents if we're not in a container (some OS' have that folder even outside of any containers).

**Comment by jerboaa** [comment]
```
if [[ -f "/.dockerenv" ]]; then
```

Means you assume `docker` as the runtime. Fails once moved to `podman` or something else, FWIW. Not sure if that's an issue worth addressing at this point.

**Review by karianna — APPROVED** [review]

**Comment by adamfarley** [comment]
Taking into consideration Stewart and Severin's points, I'm testing this:

```
KMEMMB=`awk '/^MemTotal:/{print int($$2/1024)}' /proc/meminfo`; 

if [[ -r /sys/fs/cgroup/memory.max ]]; then
    CGMEM=`cat /sys/fs/cgroup/memory.max 2>1`; 
else
    CGMEM=`cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>1`; 
fi; 

if [[ ! $$(CGMEM) =~ ^[0-9]+$$ ]]; then
    CGMEM=`expr $${KMEMMB} \* 1024 \* 1024`; 
fi; 

CGMEMMB=`expr $${CGMEM} / 1024 / 1024`; 

if [ "$${KMEMMB}" -lt "$${CGMEMMB}" ]; then 
    echo "$${KMEMMB}"; else echo "$${CGMEMMB}"; 
fi
```

This removes the cgroup version check, but also removes the need for it. 

One fewer man-page check and one fewer "if" layer, to make debugging easier.

**Comment by adamfarley** [comment]
Also, I added the formatted copy of the script into a big comment, to make maintenance easier in the future.

**Review by jerboaa — APPROVED** [review]

**Review by sxa — APPROVED** [review]

**Pull request merged**
