### PR TITLE
Excluding OpenJ9 and z/OS specific JTReg tests

### PR DESCRIPTION
**Pull request by psoujany**
Excuding openj9 specific tests and zos specific tests for jdk11 and later releases.

OpenJ9 exclusions:
java/lang/management/MemoryMXBean/MemoryManagementConcMarkSweepGC.sh
java/lang/management/MemoryMXBean/MemoryManagementParallelGC.sh
java/lang/management/MemoryMXBean/MemoryManagementSerialGC.sh
java/lang/management/MemoryMXBean/MemoryTestAllGC.sh
java/lang/management/MemoryMXBean/MemoryTest.java
java/lang/management/MemoryMXBean/LowMemoryTest.java
javax/management/Introspector/ClassLeakTest.java
java/lang/management/MemoryMXBean/MemoryTestZGC.sh

z/OS specific exclusions:
com/sun/management/OperatingSystemMXBean/GetFreePhysicalMemorySize.java
java/nio/channels/FileChannel/directio/WriteDirect.java
java/nio/channels/DatagramChannel/Promiscuous.java

Note :- Openj9 specific exclusions are applicable for jdk11 and later versions whereas z/OS specific exclusions are applicable only for jdk11.

### CODE REVIEW

**Comment by psoujany** [comment]
@llxia Could you please review this PR. Thank you.

**Comment by llxia** [comment]
Thanks @psoujany The above ECA check failed. Did you sign the Eclipse Contributor Agreement (ECA)?https://www.eclipse.org/legal/ECA.php

Also, after this PR, will `jdk_mangement ` be green? If so, we should re-include `jdk_mangement ` in https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L865

**Comment by psoujany** [comment]
Thanks @llxia . I signed ECA policy. 

By excluding these tests jdk_management couldn't be enabled, as there are few more tests which require fix in testcase other than exclusion, work is still in progress.

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]

**Pull request merged**
