### PR TITLE
Add timestamps to openjdk_tests & remove timestamps from Jenkinsfilebase

### PR DESCRIPTION
**Pull request by momanmalik**
Added timestamps to openjdk_tests and removed timestamps from JenkinsfileBase

resolves: #3396
Signed-off-by: Moman Malik <momanmalik@ibm.com>

### CODE REVIEW

**Comment by momanmalik** [comment]
Grinder link: [Grinder/27266](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27266/)

**Comment by llxia** [comment]
Thanks @momanmalik . 
A couple of minor things:
- please change the issue from `Draft` to `Read for review` when it is ready for review
- instead of `Issue: #3396`, we should use git keywords. In this case, we can use `resolves: #3396`
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Review by llxia — APPROVED** [review]
LGTM

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
