### PR TITLE
Fix CLDR11-*.properties for 11.0.18+10

### LINKED ISSUE #4271: 4 MBCS_Tests_CLDR_11_* tests FAILED in Test_openjdk11_hs_special.functional_ppc64le_linux
See https://github.com/adoptium/aqa-tests/issues/4256#issuecomment-1396283990 for original report.

[MBCS_Tests_CLDR_11_ko_KR_linux_0](https://trss.adoptium.net/output/test?id=63c820f6ed0b30773bb6284d) => [deep history 5/14 passed](https://trss.adoptium.net/deepHistory?testId=63c820f6ed0b30773bb6284d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63c81fe9ed0b30773bb620a4&buildName=Test_openjdk11_hs_special.functional_ppc64le_linux&testId=63c820f6ed0b30773bb6284d&testName=MBCS_Tests_CLDR_11_ko_KR_linux_0)
[MBCS_Tests_CLDR_11_ja_JP_linux_0](https://trss.adoptium.net/output/test?id=63c820f6ed0b30773bb62855) => [deep history 5/14 passed](https://trss.adoptium.net/deepHistory?testId=63c820f6ed0b30773bb62855) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63c81fe9ed0b30773bb620a4&buildName=Test_openjdk11_hs_special.functional_ppc64le_linux&testId=63c820f6ed0b30773bb62855&testName=MBCS_Tests_CLDR_11_ja_JP_linux_0)
[MBCS_Tests_CLDR_11_zh_CN_linux_0](https://trss.adoptium.net/output/test?id=63c820f6ed0b30773bb6284e) => [deep history 5/14 passed](https://trss.adoptium.net/deepHistory?testId=63c820f6ed0b30773bb6284e) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63c81fe9ed0b30773bb620a4&buildName=Test_openjdk11_hs_special.functional_ppc64le_linux&testId=63c820f6ed0b30773bb6284e&testName=MBCS_Tests_CLDR_11_zh_CN_linux_0)
[MBCS_Tests_CLDR_11_zh_TW_linux_0](https://trss.adoptium.net/output/test?id=63c820f6ed0b30773bb6284f) => [deep history 5/14 passed](https://trss.adoptium.net/deepHistory?testId=63c820f6ed0b30773bb6284f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63c81fe9ed0b30773bb620a4&buildName=Test_openjdk11_hs_special.functional_ppc64le_linux&testId=63c820f6ed0b30773bb6284f&testName=MBCS_Tests_CLDR_11_zh_TW_linux_0)

6 days ago, these tests ran and [passed](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_special.functional_ppc64le_linux/97/) on [test-osuosl-ubuntu1604-ppc64le-2](https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu1604-ppc64le-2) 

So, passing on Jan 14th on test-osuosl-ubuntu1604-ppc64le-2, failing on Jan 18th on test-osuosl-ubuntu2004-ppc64le-1

**NEED TO CHECK** if https://github.com/adoptium/aqa-tests/pull/4220 is in the v0.9.6-release branch, if not, should it be backported 
  - run failed targets from master branch to check if updated test material passes, rerun in [Grinder/6416](https://ci.adoptopenjdk.net/job/Grinder/6416) on test-osuosl-ubuntu2004-ppc64le-1 - fails with same issue
  - rerun with older test material (v0.9.5-release) at [Grinder/6422](https://ci.adoptopenjdk.net/job/Grinder/6422) on test-osuosl-ubuntu1604-ppc64le-2 - fails
  - rerun with v0.9.6-release on test-osuosl-ubuntu1604-ppc64le-2 in case its machine specific in [Grinder/6444](https://ci.adoptopenjdk.net/job/Grinder/6444) - fails
  
---

**Test Info**
Test Name: MBCS_Tests_CLDR_11_ko_KR_linux_0
Test Duration: 9 sec
Machine: test-osuosl-ubuntu2004-ppc64le-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=63c820f6ed0b30773bb6284d

**Build Info**
Build Name: Test_openjdk11_hs_special.functional_ppc64le_linux
Jenkins Build start time: Jan 18 2023, 05:52 am
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_special.functional_ppc64le_linux/98/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=63c81fe9ed0b30773bb620a4

**Java Version**
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=MBCS_Tests_CLDR_11_ko_KR_linux_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.6-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk11u%2Fjdk11u-release-linux-ppc64le-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-11.0.18%2B10_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;DYNAMIC_COMPILE=true&amp;TKG_SHA=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=1&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

### PR DESCRIPTION
**Pull request by takiguc**
Fixes #4271 

Signed-off-by: Ichiroh Takiguchi takiguc@jp.ibm.com

### CODE REVIEW

**Comment by takiguc** [comment]
#4271 detects the change for
> [JDK-8300483](https://bugs.openjdk.org/browse/JDK-8300483) java/text/Format/NumberFormat/CurrencyFormat.java fails for hr_HR

This fix has follow changes

- Fix CLDR11-*.properties for 11.0.18+10

Test result is as follows:
Linux x64, JDK11
371 tests, 83 ok, 0 not ok, 288 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/351/
PLATFORM: x86-64_linux
BUILD_LIST: functional/MBCS_Tests
TARGET: special.functional
SDK_RESOURCE: releases
JDK_VERSION: 11
JDK_IMPL: hotspot
LABEL: test-ibmcloud-rhel7-x64-1

CLDR_11 is just for JDK11 only.

**Comment by smlambert** [comment]
Also tested and successful against ppc64le_linux in https://ci.adoptopenjdk.net/job/Grinder/6458/

**Review by smlambert — APPROVED** [review]

**Comment by llxia** [comment]
@takiguc could you please back port the change into the aqa release branch https://github.com/adoptium/aqa-tests/tree/v0.9.6-release? Thanks

**Comment by takiguc** [comment]
Hello @llxia 

> could you please back port the change into the aqa release branch https://github.com/adoptium/aqa-tests/tree/v0.9.6-release? Thanks

I submitted PR #4281 .

**Pull request merged**
