### PR TITLE
Do not pass JCK_GIT_REPO to child job parameters

### LINKED ISSUE #5062: JCK_GIT_REPO not being set for Temurin JCK jobs
Not sure why but JCK_GIT_REPO is not being set, thus Temurin JCK jobs are failing with:
```
15:56:08  BUILD FAILED
15:56:08  /home/jenkins/workspace/Test_openjdk21_hs_sanity.jck_x86-64_linux/aqa-tests/TKG/scripts/build_test.xml:95: The following error occurred while executing this line:
15:56:08  /home/jenkins/workspace/Test_openjdk21_hs_sanity.jck_x86-64_linux/aqa-tests/jck/build.xml:294: env.JCK_GIT_REPO: ${env.JCK_GIT_REPO} was not correctly set for running JCK tests. If you do not want to compile JCK tests,       please use BUILD_LIST to include test folders you want to test.
```

Last successful run looks like 2 days ago ?

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix #5062

### CODE REVIEW

**Review by llxia — CHANGES_REQUESTED** [review]
This change is incorrect. It means that AQA Test pipeline allows users to set JCK_GIT_REPO value that will never get used.

As mentioned in https://github.com/adoptium/aqa-tests/issues/5062#issuecomment-1944029020, if JCK_GIT_REPO default value is set in test child job, then do not set it AQA Test pipeline. Just remove JCK_GIT_REPO parameter in AQA Test pipeline.

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Review by andrew-m-leonard — COMMENTED** [review]
Ah yes as Lan said, remember now

**Review by andrew-m-leonard — CHANGES_REQUESTED** [review]
I've removed JCK_GIT_REPO from our AQA_Test_Pipeline job config

**Pull request closed without merging**
