### PR TITLE
Update MBCS_Tests/CLDR_11 for 11.0.14

### LINKED ISSUE #3191: MBCS_Tests/CLDR_11 testcase was failed by 11.0.14
**Describe the bug**
According to following link, CLDR_11 testcase was failed by 11.0.14+b05
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/284/tapResults/
371 tests, 79 ok, 4 not ok, 288 skipped, 0 ToDo, 0 Bail Out!
* MBCS_Tests_CLDR_11_ja_JP_linux_0
* MBCS_Tests_CLDR_11_ko_KR_linux_0
* MBCS_Tests_CLDR_11_zh_CN_linux_0
* MBCS_Tests_CLDR_11_zh_TW_linux_0

**MBCS_Tests_CLDR_11_ja_JP_linux_0**
```
18:07:59  not ok 32 - diff TimeZoneTestB-ja-JP-DEFAULT.log expected_TimeZoneTestB-ja-JP-DEFAULT.log
18:07:59  #   Failed test 'diff TimeZoneTestB-ja-JP-DEFAULT.log expected_TimeZoneTestB-ja-JP-DEFAULT.log'
18:07:59  #   at /home/jenkins/workspace/Grinder_Simple/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 102.
18:07:59  not ok 33 - diff TimeZoneTestB-ja-JP-CLDR.log expected_TimeZoneTestB-ja-JP-CLDR.log
18:07:59  #   Failed test 'diff TimeZoneTestB-ja-JP-CLDR.log expected_TimeZoneTestB-ja-JP-CLDR.log'
18:07:59  #   at /home/jenkins/workspace/Grinder_Simple/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 102.
18:07:59  not ok 34 - diff TimeZoneTestB-ja-JP-JRE.log expected_TimeZoneTestB-ja-JP-JRE.log
18:07:59  #   Failed test 'diff TimeZoneTestB-ja-JP-JRE.log expected_TimeZoneTestB-ja-JP-JRE.log'
18:07:59  #   at /home/jenkins/workspace/Grinder_Simple/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/CLDR_11/tap_compare.pl line 102.
```

```
$ diff TimeZoneTestB-ja-JP-DEFAULT.log expected_TimeZoneTestB-ja-JP-DEFAULT.log
496c496
< MIT	Apia Standard Time	アピア標準時
---
> MIT	Apia Standard Time	Apia Daylight Time	アピア標準時	アピア夏時間
513c513
< Pacific/Apia	Apia Standard Time	アピア標準時
---
> Pacific/Apia	Apia Standard Time	Apia Daylight Time	アピア標準時	アピア夏時間
529d528
< Pacific/Kanton	Kanton Standard Time	Kanton標準時
$ diff TimeZoneTestB-ja-JP-CLDR.log expected_TimeZoneTestB-ja-JP-CLDR.log
498c498
< MIT	Apia Standard Time	アピア標準時
---
> MIT	Apia Standard Time	Apia Daylight Time	アピア標準時	アピア夏時間
514c514
< Pacific/Apia	Apia Standard Time	アピア標準時
---
> Pacific/Apia	Apia Standard Time	Apia Daylight Time	アピア標準時	アピア夏時間
531d530
< Pacific/Kanton	Kanton Standard Time	Kanton標準時
$ diff TimeZoneTestB-ja-JP-JRE.log expected_TimeZoneTestB-ja-JP-JRE.log
494c494
< MIT	West Samoa Standard Time	西サモア時間
---
> MIT	West Samoa Standard Time	West Samoa Daylight Time	西サモア時間	西サモア夏時間
511c511
< Pacific/Apia	West Samoa Standard Time	西サモア時間
---
> Pacific/Apia	West Samoa Standard Time	West Samoa Daylight Time	西サモア時間	西サモア夏時間
527d526
< Pacific/Kanton	Phoenix Is. Time	フェニックス諸島時間
```
Java version information:
```
openjdk version "11.0.14-beta" 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+5-202112021734 (build 11.0.14-beta+5-202112021734)
OpenJDK 64-Bit Server VM Temurin-11.0.14+5-202112021734 (build 11.0.14-beta+5-202112021734, mixed mode)
```

**To Reproduce**
Grinder_Simple parameters link is as follows:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/284/parameters/
PLATFORM: x86-64_linux
BUILD_LIST: functional/MBCS_Tests
TARGET: special.functional
SDK_RESOURCE: nightly
JDK_VERSION: 11
JDK_IMPL: hotspot
LABEL: test-ibmcloud-rhel7-x64-1

**Expected behavior**
CLDR_11 should not be failed
I assume following changes affected this issue:
[JDK-8274407](https://bugs.openjdk.java.net/browse/JDK-8274407) (tz) Update Timezone Data to 2021c
[JDK-8276536](https://bugs.openjdk.java.net/browse/JDK-8276536) Update TimeZoneNames files to follow the changes made by JDK-8275766

Following changes were applied by 11.0.14
* Africa/Windhoek; JDK-8276536, Summer Time display name was changed to "Western African Time", abbreviation was "WAT". Then translation was removed
* Africa/Juba; JDK-8276536, Timezone was changed to CAT
* Pacific/Apia, MIT; JDK-8274407, Abolish daylight saving time
* Pacific/Kanton; JDK-8274407, Use Pacific/Kanton instead of Pacific/Enderbury. By this change, "timezone.regionFormat.standard" resource ("{0} Standard Time") is used on FormatData (sun/text/resources/cldr/ext/FormatData_xx and sun/text/resources/cldr/FormatData) on default. If java.locale.providers is set "JRE", "Phoenix Islands Time" is used for Pacific/Enderbury. Note: For zh_TW locale, "{0} (+0)" is used on sun/text/resources/cldr/FormatData. For zh_TW locale, src/jdk.localedata/share/classes/sun/util/cldr/resources/common/main/zh_Hant.xml is referred. sun/text/resources/cldr/ext/FormatData_zh_Hant does not have a entry for "timezone.regionFormat.standard"
* "Antarctica/Macquarie" was also changed, but since no translation data was available for "Antarctica/Macquarie", CLDR_11 testcase did not pick up this change.

### PR DESCRIPTION
**Pull request by takiguc**
Fixes #3191

Signed-off-by: Ichiroh Takiguchi takiguc@jp.ibm.com

### CODE REVIEW

**Comment by takiguc** [comment]
This fix has follow 3 changes
* Update CLDR_11 testcase data for 11.0.14 (CLDR11-*.properties)
* Ignore Pacific/Kanton timezone because Pacific/Kanton is not supported by JDK11's CLDR (CheckZHTW.java)
* Update test.bat script for CLDR_11 (test.bat)

Test result is as follows:
Linux x64, JDK11
371 tests, 83 ok, 0 not ok, 288 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/291/tapResults/
PLATFORM: x86-64_linux
BUILD_LIST: functional/MBCS_Tests
TARGET: special.functional
SDK_RESOURCE: nightly
JDK_VERSION: 11
JDK_IMPL: hotspot
LABEL: test-ibmcloud-rhel7-x64-1

Windows x64, JDK11
371 tests, 82 ok, 0 not ok, 289 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/290/tapResults/
PLATFORM: x86-64_windows
BUILD_LIST: functional/MBCS_Tests
TARGET: special.functional
SDK_RESOURCE: nightly
JDK_VERSION: 11
JDK_IMPL: hotspot

**Comment by takiguc** [comment]
Test result is as follows:
AIX7.1 ppc64
371 tests, 216 ok, 0 not ok, 155 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/293/tapResults/
PLATFORM: ppc64_aix
BUILD_LIST: functional/MBCS_Tests
TARGET: special.functional
SDK_RESOURCE: nightly
JDK_VERSION: 11
JDK_IMPL: hotspot
LABEL: test-osuosl-aix71-ppc64-1

**Review by smlambert — APPROVED** [review]
thanks @takiguc !

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
