### PR TITLE
Enhance the environment variable check

### PR DESCRIPTION
**Pull request by sophia-guo**
Check environment variable as set only if it's not empty.

Related https://github.com/adoptium/aqa-tests/pull/5683#issuecomment-2504457271

### CODE REVIEW

**Comment by sophia-guo** [comment]
Using [macros "set-property"](https://github.com/adoptium/TKG/blob/master/scripts/build_test.xml#L78C3-L78C30) checking both the presence of the property and whether it is non-empty to handle the case where the env.variable might be set but empty.

**Review by smlambert — APPROVED** [review]

**Comment by llxia** [comment]
Could you please test the change in Grinder?

**Comment by sophia-guo** [comment]
Grinder shows the change won't affect current behaviour.
https://ci.adoptium.net/view/Test_grinder/job/Grinder/11989/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/11992/

This change mainly handle the environment variable is set but empty, which seems can only trigger in this environment https://github.com/adoptium/aqa-tests/pull/5683#issuecomment-2502027532.  Set environment variable as empty in jenkinsfilebase  https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L83 won't trigger this issue. Fix and causes is similar to https://github.com/adoptium/TKG/pull/641/files. 

Given the high cost of setting up this test environment ( trigger the dynamic agent, might also need to use George's PR) and current behaviour won't be changed I'm skipping the test the environment variable is set but empty. If any issues arise late we can address them at that time.

**Comment by llxia** [comment]
I tested openJcePlusTests in 2 scenarios (Grinder_FIPS/2896, Grinder_FIPS/2897). Unfortunately, I cannot test all the cases. But I think this PR is safe to merge.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
