### PR TITLE
Add reference repo for git clone openj9

### PR DESCRIPTION
**Pull request by llxia**
related: runtimes/backlog/issues/815

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
- the cache does not exist (warning message): https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5304/
```
[2022-07-27T15:07:07.944Z] git clone --depth 1 --reference-if-able /home/jenkins/openjdk_cache -b master https://github.com/eclipse/openj9.git
[2022-07-27T15:07:07.944Z] Cloning into 'openj9'...
[2022-07-27T15:07:07.944Z] info: Could not add alternate for '/home/jenkins/openjdk_cache': reference repository '/home/jenkins/openjdk_cache' is not a local repository.
[2022-07-27T15:07:16.833Z] Updating files:  96% (9714/10083)
Updating files:  97% (9781/10083)
Updating files:  98% (9882/10083)
Updating files:  99% (9983/10083)
Updating files: 100% (10083/10083)
Updating files: 100% (10083/10083), done.
[2022-07-27T15:07:16.833Z] check OpenJ9 Repo sha
```

- cache exists and is up to date: Grinder/25185
```
[2022-07-27T15:20:03.267Z] git clone --depth 1 --reference-if-able /home/jenkins/openjdk_cache -b master https://github.com/eclipse-openj9/openj9.git
[2022-07-27T15:20:03.267Z] Cloning into 'openj9'...
[2022-07-27T15:20:09.528Z] Checking out files:  43% (4393/10083)   
Checking out files:  44% (4437/10083)   
Checking out files:  45% (4538/10083)   
...
Checking out files: 100% (10083/10083), done.
[2022-07-27T15:20:09.528Z] check OpenJ9 Repo sha
```

**Comment by llxia** [comment]
Further simplification will be done in https://github.com/adoptium/aqa-tests/issues/3828

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
might be worth adding a comment as to why this is being added.

**Review by smlambert — APPROVED** [review]

**Comment by llxia** [comment]
> might be worth adding a comment as to why this is being added.

This is to improve the git clone efficiency. 

```
Using an already existing repository as an alternate will require fewer objects to be copied from the repository being cloned, reducing network and local storage costs. When using the --reference-if-able, a non existing directory is skipped with a warning instead of aborting the clone.
```
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---reference-if-ableltrepositorygt

**Comment by AdamBrousseau** [comment]
Came back to this looking for this info so I'll add it here.

> The --reference-if-able needs git >= 2.11.4

**Pull request merged**
