### PR TITLE
Nested node for server and client testing

### PR DESCRIPTION
**Pull request by llxia**
Move the main function into runTest(). If RELATED_NODES is provided, the script will try to book it, then book LABEL matched node and run test. Otherwise, run test normally on LABEL.

Related: https://github.com/adoptium/aqa-tests/issues/2841

Co-authored-by: lanxia <lan_xia@ca.ibm.com>
Co-authored-by: Azah Norbline <azahnorbline@gmail.com>

### CODE REVIEW

**Comment by llxia** [comment]
@norbline could you also add a timeout check for waiting for RELATED_NODES? It means make https://github.com/adoptium/aqa-tests/pull/3364/files#diff-ebf20f64c486ae48bd60b965c555076519f9d5623789f4574467d3051bb530f7R171-R177 a function and call it at for LABEL and for RELATED_NODES.

Git clone this change, and you can update this PR directly. Once you are done, please add yourself as co-author. Please see
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by llxia** [comment]
@norbline please also test the following cases, once you are done:
- Regular run without RELATED_NODES
- Run with RELATED_NODES, check if both machines are booked
- Run two Grinder with same RELATED_NODES and LABEL, check if the second job is waiting for the first job due to RELATED_NODES being busy
- Run [Machine-Reservation](https://ci.adoptopenjdk.net/job/Machine-Reservation) to make a node busy. Run 2nd Grinder with free RELATED_NODES and busy LABEL node. The test should start after the busy LABEL node is free.
- Run [Machine-Reservation](https://ci.adoptopenjdk.net/job/Machine-Reservation) to make a node busy. Run 2nd Grinder with busy RELATED_NODES and free LABEL node. The test should start after the busy RELATED_NODES node is free.
- Run [Machine-Reservation](https://ci.adoptopenjdk.net/job/Machine-Reservation) to make a node busy for > timeout. Run 2nd Grinder with busy RELATED_NODES and free LABEL node. The build should timeout.

**Comment by llxia** [comment]
- Regular run without RELATED_NODES https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3716/

**Comment by norbline** [comment]
@llxia seems like I can not update this PR. Access denied

**Comment by llxia** [comment]
@norbline Thanks for testing. Let's merge this PR first, then you can open a new PR for the additional change.

**Review by renfeiw — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
Good to bring this in for now (noting we will need to update/test the scenario when params.RELATED_NODES contains a comma separated list of node names in a later PR).

**Pull request merged**
