### PR TITLE
Add jtreg6.1_1

### LINKED ISSUE #3074: Update jtreg to jtreg-6.1+1 for jdk18
Since yesterday OpenJDK 18 (current mainline development tree) requires jtreg-6.1+1 due to removal of Security Manager. 
https://github.com/adoptium/ci-jenkins-pipelines/issues/211#issue-1032442818

We need to update jtreg from jtreg-6+1 to jtreg-6.1+1 for jdk18

jtreg-6.1+1 is ready for consumption https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/223/, which was a testing run.
When the PR https://github.com/adoptium/ci-jenkins-pipelines/pull/212 is merged, https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline would be stable for jtreg-6.1+1

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #3074 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by llxia** [comment]
Please keep me in the loop regarding updating the jtreg. test.getDependency at both openj9 Jenkins and internal Jenkins needs to be triggered after this change.

**Comment by sophia-guo** [comment]
@llxia jobs at https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/ is ready.

**Comment by llxia** [comment]
Thanks @sophia-guo

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM @sophia-guo !  will wait for the final Grinders to occur!  @llxia - leaving for you to merge after some additional testing, thanks!

**Comment by llxia** [comment]
All 3 Jenkins jobs are updated:
https://ci.adoptopenjdk.net/view/all/job/test.getDependency/1258/
https://openj9-jenkins.osuosl.org/job/test.getDependency/185/
internal/test.getDependency/10080/

**Pull request merged**
