### PR TITLE
Simplify the git clone repo to openjdk-jdk folder - issue #2693

### PR DESCRIPTION
**Pull request by yinggzz**
Fixes: #2693

Signed-off-by: Ying Zhou

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
The PR looks good. Was there any grinder run to test this PR? If yes, please share them in a comment here. Thanks!

**Comment by smlambert** [comment]
For this change, it will be important to try and run several Grinders with 
BUILD_LIST=openjdk
and varying 
JDK_VERSION=8 or 11 or 17 and
TARGET=jdk_math or some other short running target

**Comment by yinggzz** [comment]
Grinder test: https://ci.adoptopenjdk.net/job/Grinder/3260/

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
Gridner results look good: https://ci.adoptopenjdk.net/job/Grinder/3260! Approving! Thanks @yinggzz !

**Comment by smlambert** [comment]
I will request one more variation of Grinder test, where we provide values for the JDK repo/branch
JDK_VERSION=11
JDK_REPO=https://github.com/openjdk/jdk11u.git
JDK_BRANCH=jdk-11.0.14-ga

**Comment by yinggzz** [comment]
Grinder test as requested above: https://ci.adoptopenjdk.net/job/Grinder/

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
