### PR TITLE
Re-enable JVMTI test WaitNotifySuspendedVThreadTest

### PR DESCRIPTION
**Pull request by dipak-bagadiya**
Test has been fixed by eclipse-openj9/openj9#17350

Signed-off-by: Dipak Bagadiya dipak.bagadiya@ibm.com

### CODE REVIEW

**Comment by karianna** [comment]
@dipak-bagadiya Looks like test failures

**Comment by dipak-bagadiya** [comment]
@karianna,
Test failures are unrelated to the changes in this PR.
@llxia @Mesbah-Alam 
Please review and approve the same.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
Let me try if I can rebase from UI directly.

**Pull request merged**
