### PR TITLE
Changes to JavaTestRunner from STF

### PR DESCRIPTION
**Pull request by smlambert**
Some settings for targets that do not require display.

Signed-off-by: Shelley Lambert <slambert@gmail.com>

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
Could we please un-exclude the 2 related targets from playlists as part of this PR too? That'd make it easier to test.   

https://github.com/adoptium/aqa-tests/blob/6220de1d5ed6bbe95af699a4c1aaeb5c025844ea/jck/runtime.api/playlist.xml#L347

https://github.com/adoptium/aqa-tests/blob/6220de1d5ed6bbe95af699a4c1aaeb5c025844ea/jck/runtime.api/playlist.xml#L624

**Comment by Mesbah-Alam** [comment]
Just wondering if the two related targets could be un-excluded as part of this PR. 
That'd make it easier to test this PR on Mac. 

https://github.com/adoptium/aqa-tests/blob/6220de1d5ed6bbe95af699a4c1aaeb5c025844ea/jck/runtime.api/playlist.xml#L347

https://github.com/adoptium/aqa-tests/blob/6220de1d5ed6bbe95af699a4c1aaeb5c025844ea/jck/runtime.api/playlist.xml#L624

**Comment by smlambert** [comment]
@Mesbah-Alam - for disabled test targets, a feature of TKG is that you can run those targets in Grinders by setting TARGET=disabled.jck-runtime-api-signaturetest and 
TARGET=disabled.jck-runtime-api-java_io without having to re-enable them in a branch.  I will co-ordinate with you via DM whether to re-enable or not based on your results (as I do not have nor need to know the details of infrastructure/issues/5254).

**Comment by Mesbah-Alam** [comment]
> Whether to re-enable or not based on your results 

Signaturetest and java_io are working fine on Mac at our end: Grinder 20007 & 20008.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
Thanks @smlambert !

**Comment by Mesbah-Alam** [comment]
Oh.. It says the branch has a conflict. Could you please resolve it? Thanks!

**Pull request merged**
