### PR TITLE
Set configAltPath for special.jck targets

### PR DESCRIPTION
**Pull request by smlambert**
Set default configuration for kerberos / https servers

Signed-off-by: Shelley Lambert <slambert@gmail.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Running grinder (Grinder/19832) internally off of `smlambert:confAltPath` is causing an authentication error: 

```
fatal: Authentication failed for 'https://github.com/smlambert/aqa-tests.git/'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2681)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2102)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:86)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:624)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:853)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1224)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:68)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:310)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:431)
ERROR: Error cloning remote repo 'origin'
```

Speaking with Adam via slack about this.

**Comment by Mesbah-Alam** [comment]
Ah, found the issue. Using https://github.com/smlambert/openjdk-tests makes it work fine. 

The PR looks fine. Running some grinder internally just to confirm all is good.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
Tested with Grinder/19839

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
