### PR TITLE
Changing JCK HTTP URL

### PR DESCRIPTION
**Pull request by adamfarley**
For details, see https://github.com/temurin-compliance/ temurin-compliance/issues/589

### CODE REVIEW

**Comment by adamfarley** [comment]
Please assign this to me, thank you.

**Comment by adamfarley** [comment]
Update: The URL change has the correct effect, except for in 2 places. The Amended URL appears to have the appropriate effect in all scenarios.

**Review by smlambert — APPROVED** [review]

**Review by sophia-guo — APPROVED** [review]

**Comment by karianna** [comment]
@adamfarley So it's not safe to merge this I assume?

**Comment by smlambert** [comment]
It's fine to merge.

**Comment by adamfarley** [comment]
Thank you @smlambert and @sophia-guo 

Also @karianna, for your concern. 🤓

**Pull request merged**
