### PR TITLE
Added certification.info

### PR DESCRIPTION
**Pull request by judovana**
This file should serve for autoamtion, to resove which branch/tag to
checkout, to be able to automatically checkout proper revision to run
agaisnt without human touch

### CODE REVIEW

**Comment by smlambert** [comment]
thanks @judovana 

This is certification info is dependent on what release you are trying to certify, and it is not wrong to put information for the latest release here, but it can also be pulled from a github query for latest release available: 
https://github.com/adoptium/aqa-tests/releases/latest which redirects to 
https://github.com/adoptium/aqa-tests/releases/tag/v0.9.1 
where the release notes describe which CPU this is applicable towards:
- Release branch for April CPU [2022-04-19 CPU for 18.0.1 | 17.0.3 | 11.0.15 | 8u331] [java.com/releases](https://www.java.com/releases/) 

So you will be cloning a branch of the same name: https://github.com/adoptium/aqa-tests/tree/v0.9.1-release

while January was v0.8.0-release (which at the time was the 'latest', https://github.com/adoptium/aqa-tests/releases/tag/v0.8.0).
- Release branch for January CPU [2022-01-18 CPU for 17.0.2 | 11.0.14 | 8u321] [java.com/releases](https://www.java.com/releases/)



If we are to add this file for _convenience_ to list the 'latest release branch name', it would be better to put it into https://github.com/adoptium/aqa-tests/tree/master/testenv directory and not in the top-level directory.

To contribute to an Eclipse project, you also must sign the ECA (helper info here: https://github.com/adoptium/aqa-tests/blob/master/Contributing.md#eclipse-contributor-agreement), otherwise the eclipsefdn/eca validation check fails and we are not able to merge your PR.

**Comment by karianna** [comment]
@judovana need to look at the ECA status

**Comment by judovana** [comment]
hm. You are ok with maintaining  this file togehter with github releases?
if not, then resolving the https://github.com/adoptium/aqa-tests/releases/latest should be enough, although I found it very clumsy, it may be better to let me suffer, rather then aqa people to miantian this file.
Is being @RedHat enough to pass ECA?

As for the various certifications, yes to pass some selected one is always an option. This file was supposed to point to most fresh stable one.

**Comment by llxia** [comment]
IMHO, I would prefer not to maintain the version file if possible. In addition to https://github.com/adoptium/aqa-tests/releases/latest, we can also use cmd `git tag | tail -1` to get the latest tag.

```
$ git tag | tail -1
v0.9.1
```

**Comment by smlambert** [comment]
We ask people to git clone the release branch (versus tag) and we will always follow the naming convention where the branch is named `latest_tag`-release, so v0.9.1-release is the branch to clone as per instructions at https://adoptium.net/docs/aqavit-verification/.

**Comment by judovana** [comment]
> IMHO, I would prefer not to maintain the version file if possible. In addition to https://github.com/adoptium/aqa-tests/releases/latest, we can also use cmd `git tag | tail -1` to get the latest tag.
> 
> ```
> $ git tag | tail -1
> v0.9.1
> ```

I moreover agree with you, but the recommender approach description is then not publicly known nro properly documented

> We ask people to git clone the release branch (versus tag) and we will always follow the naming convention where the branch is 

Yes, the branch is much better here then tag

>named `latest_tag`-release, so v0.9.1-release is the branch to clone as per instructions at https://adoptium.net/docs/aqavit-verification/.

Exactly this approach,  and lack of this documentation is it the missing peace which forced me to do this minidummy PR.
Can you somwhere document, that certification should be run based on tagging andnaming convention as:

```
$ LATEST_TAG=`git tag | tail -n 1`
$ git checkout "${LATEST_TAG}-release"
```

I will move my autmation to this then. Crossing fingers to keep the naming convention!

**Comment by smlambert** [comment]
https://github.com/adoptium/website-v2/pull/647

**Pull request closed without merging**
