### PR TITLE
Exclude FollowReferences/VThreadStackRefTest

### PR DESCRIPTION
**Pull request by babsingh**
Related: https://github.com/eclipse-openj9/openj9/issues/18426

### CODE REVIEW

**Comment by babsingh** [comment]
fyi @pshipton @JasonFengJ9 

Do we also need to port this to the v1.0.0-release and j9.0.42-release branches?

**Review by llxia — APPROVED** [review]
LGTM

**Comment by pshipton** [comment]
> Do we also need to port this to the v1.0.0-release and j9.0.42-release branches?

Yes pls.

**Review by pshipton — APPROVED** [review]

**Comment by babsingh** [comment]
### Backports
- v1.0.0: https://github.com/adoptium/aqa-tests/pull/4938
- j9.0.42: https://github.com/adoptium/aqa-tests/pull/4939

**Pull request merged**
