### PR TITLE
Include jck-compiler-api-java_rmi on all platforms for JDK8 and JDK11

### PR DESCRIPTION
**Pull request by prodroy89**
This PR, enables jck-compiler-api-java_rmi tests for JCK8C and JCK11

Related: runtimes/backlog/issues/559

Signed off by : Prodip Roy (prodroy89@in.ibm.com)

### CODE REVIEW

**Comment by prodroy89** [comment]
Grinder submission for java80:-

1. windows_x86-64|:-
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25234/ - IBM build
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25231/ - openj9 build

 2. Linux_x86-64:-
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25270/ - IBM build
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25230/ - openj9 build

3. Linux-ppcle64:-
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25241/ - IBM build

Grinder submission for java11:-

1. Linux_x86-64:-
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25223/ - IBM build

Thanks.

**Comment by llxia** [comment]
- This PR re-enables tests, not a fix for runtimes/backlog/issues/559. I updated the description.
According to runtimes/backlog/issues/559, the original exclusion was due to intermittent failures (machine/network related). Please provide testing on wins and s390 on JDK8 and JDK11 with at least 10x on 5 machines. The failure rate was ~8%.

FYI @JasonFengJ9 

- This PR also re-enables jck-compiler-lang-LMBD on wins JDK11, could you provide the test link for it?

**Comment by prodroy89** [comment]
@llxia  and @Mesbah-Alam, I have submitted on wins and s390 on JDK8 and JDK11 with at least 10x on 5 machines.

Windows:-
JDK8:-(10x on 5 machines)
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25321/  - IBM build
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25322/ - Openj9

JDK11:- (10x on 1 machine)
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25375/ - IBM build 
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25373/ - Openj9

s390:-

JDK8:-(10x on 5 machines)
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25325/ - IBM build
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25326/ - Openj9

JDK11:-(10x on 5 machines)
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25327/ - IBM build
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/25328/ - Openj9

**Comment by llxia** [comment]
This PR also re-enables jck-compiler-lang-LMBD on wins JDK11, could you provide the test link for it?

**Comment by prodroy89** [comment]
@llxia, I didn't get your last comment, you mean to say need to submit jck-compiler-lang-LMBD test on wins JDK11 with grinder submission by 10 times or more?

**Comment by llxia** [comment]
I do not see jck-compiler-lang-LMBD Grinder link in the above comment. And I would like to ensure it can pass consistently. Thanks

**Comment by prodroy89** [comment]
@llxia, I have submitted jck-compiler-lang-LMBD test with Grinder submission by 10 times on windows platforms with openj9 and IBM builds for jck11.

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/26436/
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/26436/

Thanks

**Comment by Mesbah-Alam** [comment]
@prodroy89 , as I had mentioned above in https://github.com/adoptium/aqa-tests/pull/3798#issuecomment-1169072448, We had [decided](https://github.ibm.com/runtimes/backlog/issues/559#issuecomment-37478674) to disable jck-compiler-api-java_rmi and transfer it to CR team, as it had been failing intermittently on both 8 and 11 across all platforms.  

I can see that you have randomly picked a subset of platform + SDK version combinations and run some grinders and it worked. Does this guarantee that the intermittent failure will now never occur after we enable this target again? Has something changed in infra/ machine side due to which the target is now passing? It would be ideal if you could please update runtimes/backlog/issues/559 confirming that. Thanks.

**Comment by Mesbah-Alam** [comment]
Based on https://github.com/adoptium/aqa-tests/pull/3798#issuecomment-1212032390, closing this PR without merging. Please reopen after adequate testing is done on all platforms, or the underlying test configuration changed. Thanks!

**Pull request closed without merging**
