### PR TITLE
Revert "remove --testdir|-t parameter in get.sh"

### PR DESCRIPTION
**Pull request by llxia**
Reverts adoptium/aqa-tests#2760

### CODE REVIEW

**Comment by llxia** [comment]
#2760 does not work on windows:

```
00:01:12.720  Running in J:\jenkins\workspace\Grinder\aqa-tests
[Pipeline] {
[Pipeline] sh
00:01:13.190  + ./get.sh -s J:jenkinsworkspaceGrinder -p x86-64_windows -r nightly -j 8 -i openj9 --openj9_repo https://github.com/eclipse/openj9.git --openj9_branch master --tkg_repo https://github.com/AdoptOpenJDK/TKG.git --tkg_branch master
00:01:13.191  TESTDIR: /cygdrive/j/jenkins/workspace/Grinder/aqa-tests
00:01:13.191  get jdk binary...
00:01:13.191  ./get.sh: line 162: cd: J:jenkinsworkspaceGrinder: No such file or directory
```

**Comment by sophia-guo** [comment]
I probably could do a quick fix.

**Comment by llxia** [comment]
Thanks @sophia-guo . I think this is why we used `pwd` in the code before.

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
Ah, I just read above for a quick fix versus revert.  👍

**Pull request closed without merging**
