### PR TITLE
work around bazel tool

### PR DESCRIPTION
**Pull request by LizyBbethy**
draft testing how new changes run

### CODE REVIEW

**Comment by llxia** [comment]
@LizyBbethy is this PR ready for review? Could you provide some Grinder links?

**Comment by LizyBbethy** [comment]
> @LizyBbethy is this PR ready for review? Could you provide some Grinder links?

not as yet considering a different approach grinder still breaking

**Comment by smlambert** [comment]
hi @LizyBbethy - If you provide Grinder link, mentors can help determine the issue and give guidance. :)

**Comment by LizyBbethy** [comment]
> hi @LizyBbethy - If you provide Grinder link, mentors can help determine the issue and give guidance. :)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Tether/46/console according to this grinder 
error5

**Comment by smlambert** [comment]
hi @LizyBbethy - the Grinder you have run is running out of the master branch, I have updated 2 parameters, so it will run the code that is currently in your branch, see here: https://ci.adoptopenjdk.net/job/Grinder_Tether/48
Screen Shot 2022-01-25 at 9 58 31 AM

that way will will be able to see how your changes behave in comparison to what is in the master branch.

**Comment by sophia-guo** [comment]
https://adoptium.slack.com/archives/C02NE6QB0SH/p1643203774033900

**Comment by sophia-guo** [comment]
Rerun https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3457/console

**Comment by sophia-guo** [comment]
I have rerun the job on [test-packet-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1) https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Tether/73/console and didn't get the pull image issue (maybe github adoptopenjdk image issue get fixed: the issue seems like the image was built by windows container, though I didn't take a deep look).  https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Tether/73/

The current failure I believe the same failure that this PR is trying to fix ` bazel` is not installed correctly.

```
11:15:09  OpenJDK Runtime Environment (Temurin)(build 1.8.0_332-beta-202202021725-b01)
11:15:09  OpenJDK 64-Bit Server VM (Temurin)(build 25.332-b01, mixed mode)
11:15:09  =JAVA VERSION OUTPUT END=
11:15:09  /wycheproof.sh: line 44: bazel: command not found
11:15:09  /wycheproof.sh: line 47: bazel: command not found
11:15:09  find: ‘/root/.cache’: No such file or directory
```

From the console output there is no docker step doing the wget bazel step ( the step updated in this PR). That is generated Dockerfile doesn't have this step.

We need to see why dockerfile isn't generated correctly.

**Comment by smlambert** [comment]
I think I will close this as the Outreachy term has completed, and there have been some of these changes have come in under other PRs.

**Pull request closed without merging**
