### PR TITLE
remove set -eo pipefail

### PR DESCRIPTION
**Pull request by llxia**
fixes: https://github.com/adoptium/aqa-tests/issues/5295

### CODE REVIEW

**Comment by llxia** [comment]
reran on the failed machine: https://ci.adoptium.net/view/Test_grinder/job/Grinder/9891/

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]

**Comment by judovana** [comment]
`set -eo pipefail` is quite crucial part of the script. Its removal may be breakig other platforms.

In addition, this PR is wrong. The message clearly says "set: Illegal option -o pipefail"  so this PR should have remove **only**  `-o pipefail`, and keep the `e` on. 

Seeing also the `#!/usr/bin/env bash` in the script, is is supposed to be bash, bash should know `-o pipefail`  unless it is ancient bash (or fake bash).

@llxia   - please update your systems. You have to be run exceptionally legacy configurations, and it is enforcing breaking changes  for everybody else.


In addition, the https://github.com/llxia/openjdk-tests/blob/cb86453541d2cedb78dab55e0dac63905c14ad6d/scripts/testenv/testenvSettings.sh do not have isngle *pipe*  so

```
- set -eo pipefail
+ set -e
``
would be very correct fix.  But

```
- set -eo pipefail
``
Thus removing whole -e is usualy very bad fix.  Please  revert if you can.

**Comment by judovana** [comment]
Then at least return the `-e`

**Pull request merged**
