### PR TITLE
Exclude SecurityTests

### PR DESCRIPTION
**Pull request by llxia**

### CODE REVIEW

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/2547/

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Do not believe these were failing against hotspot builds (see: https://trss.adoptium.net/deepHistory?testId=6492801d17052c67152cdbe4) but now they are disabled for all implementations, think you meant to exclude for openj9 based on the issue that is referenced).

**Comment by llxia** [comment]
This is a general issue. The same issue also happens on hotspot builds: https://ci.adoptium.net/job/Grinder/7312/

**Pull request merged**
