### PR TITLE
Add JTwork folder for junit report

### PR DESCRIPTION
**Pull request by llxia**
related: https://github.com/adoptium/aqa-tests/issues/5206

### CODE REVIEW

**Comment by llxia** [comment]
[Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39802/testReport/)

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]

**Comment by judovana** [comment]
Interesting. TYVM!

**Comment by judovana** [comment]
pls note: https://github.com/adoptium/aqa-tests/issues/5206#issuecomment-2055801138 it may be better solution

**Comment by judovana** [comment]
> pls note: [#5206 (comment)](https://github.com/adoptium/aqa-tests/issues/5206#issuecomment-2055801138) it may be better solution

I would rather not merge this, and adjsut cryptotests (and ssl tests and maybe also churn) so they fit more , as per https://github.com/adoptium/aqa-tests/issues/5206#issuecomment-2058376132

**Comment by judovana** [comment]
I will rename it.  I do not have reasons to not do it.
There are however two other questions place in https://github.com/adoptium/aqa-tests/issues/5206#issuecomment-2055801138.  If you place your opinion, it wilk make it a bit easier to finish.

**Comment by judovana** [comment]
> I will rename it. I do not have reasons to not do it. There are however two other questions place in [#5206 (comment)](https://github.com/adoptium/aqa-tests/issues/5206#issuecomment-2055801138). If you place your opinion, it wilk make it a bit easier to finish.

https://github.com/rh-openjdk/CryptoTest/pull/67/commits

**Comment by judovana** [comment]
> > I will rename it. I do not have reasons to not do it. There are however two other questions place in [#5206 (comment)](https://github.com/adoptium/aqa-tests/issues/5206#issuecomment-2055801138). If you place your opinion, it wilk make it a bit easier to finish.
> 
> https://github.com/rh-openjdk/CryptoTest/pull/67/commits

merged. Will applya lso to toher suites where applicable

**Comment by llxia** [comment]
Thanks @judovana for https://github.com/rh-openjdk/CryptoTest/pull/67/.
For future reference, it's important to run tests on PRs before implementing changes to ensure they won't disrupt the regular workflow.

**Comment by judovana** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9691/console

So next time, before merginf ssl-test, crypto test or generally any 3rd party suite, I should create a branch in my aqa-tests fork andm change it so it doubke check the PR to the 3rd party suite. Right?

**Pull request closed without merging**
