### PR TITLE
Removed _mixed in playlist.xml

### PR DESCRIPTION
**Pull request by bkrit**
This Pull Request aims to solve #2713

### CODE REVIEW

**Comment by smlambert** [comment]
thanks @bkrit - can you please sign the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php) using the same email as your commit to ensure the eclipsefdn/eca check passes.

**Review by smlambert — APPROVED** [review]

**Review by llxia — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Once the ECA is signed, we can merge this!

**Comment by smlambert** [comment]
This has gone stale, closing in favour of #2753

**Pull request closed without merging**
