### PR TITLE
Reenabled fixed source tests in jdk_build

### PR DESCRIPTION
**Pull request by judovana**
please note, that the fix should go to stable release  version too. Please note, that the test was alone in its group in jdk11. That was a bit dangerous.

### CODE REVIEW

**Review by smlambert — COMMENTED** [review]
@judovana - you can leave the jdk_build section in place (to guide others in future if they need to exclude something from that target, and just remove exclude lines (L33 of the files)

Also please sign the ECA as per: https://adoptium.net/docs/eca-sign-off/

**Review by smlambert — APPROVED** [review]

**Review by sophia-guo — APPROVED** [review]

**Comment by smlambert** [comment]
It is not our checker, it is the Eclipse Foundation checker, you bend to it, it does not bend to you.  

Options to try for troubleshooting: 
- Set your default[ commit email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) (sounds like you already tried this, if so, push another change to the PR to see if the validation check will pass... doubtful to work, I reran the check and it still fails)
- try using "[Signed-off by](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)" mechanism
- try creating a new PR now that the commit email address matches the ECA account...

**Comment by judovana** [comment]
I will create second EF account. TYVM~

**Comment by judovana** [comment]
I tried that siggned off, did not worked.   I create second EC account. Do not work.. any more hints?

**Comment by smlambert** [comment]
The ECA validation tool is checking this particular PR and the commits within it, if any of the commits are associated with an 'invalid account' it will fail.  When others have hit this issue, its often easiest to create a fresh PR with the git email is aligned with the one from the ECA account.

**Comment by judovana** [comment]
hm. the new pr indeed have passed.. :( 21st century :((

**Pull request closed without merging**
