### PR TITLE
Test -Xtune:throughput in mauveLoadTest variations

### PR DESCRIPTION
**Pull request by cjjdespres**
Fixes: eclipse-openj9/openj9/issues/14551
Signed-off-by: Christian Despres <despresc@ibm.com>

### CODE REVIEW

**Comment by cjjdespres** [comment]
This requires https://github.com/adoptium/TKG/pull/291 to be merged.

**Comment by cjjdespres** [comment]
Attn @mpirvu

**Review by llxia — APPROVED** [review]
Thanks @cjjdespres

**Comment by llxia** [comment]
@cjjdespres could you also update the PR title and description as we do not use Mode189 anymore? Thanks

**Comment by cjjdespres** [comment]
Oh, sure. Forgot about that.

**Review by smlambert — APPROVED** [review]

**Pull request merged**
