### PR TITLE
Check jtr file only if previous cmd completed successfully

### PR DESCRIPTION
**Pull request by llxia**
fix: https://github.com/adoptium/aqa-tests/issues/4115
Signed-off-by: Lan Xia <Lan_Xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/1498/

**Comment by llxia** [comment]
FYI @pshipton

**Review by renfeiw — APPROVED** [review]
LGTM

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
