### PR TITLE
rename opendjk-tests to aqa-tests

### PR DESCRIPTION
**Pull request by OscarQQ**
related: https://github.com/adoptium/aqa-tests/pull/2612
Signed-off-by: Yixin Qian <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
parallel: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/775/
normal: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/776/

**Comment by llxia** [comment]
run aqa -help

**Comment by OscarQQ** [comment]
run aqa -h

**Comment by OscarQQ** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target sanity.openjdk --jdk_version 8 11 --jdk_impl openj9 --platform x86-64_linux

**Comment by OscarQQ** [comment]
run aqa --sdk_resource nightly --build_list functional --target floatSanityTests --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Review by smlambert — APPROVED** [review]
thanks @OscarQQ !

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
run aqa --sdk_resource nightly --build_list functional --target floatSanityTests --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by llxia** [comment]
run aqa --sdk_resource nightly --build_list functional --target floatSanityTests --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by OscarQQ** [comment]
run aqa --sdk_resource nightly --build_list functional --target floatSanityTests --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Pull request merged**
