### PR TITLE
Fix the issue `pwd`on Windows

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #2786 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by llxia** [comment]
Could you resolve the merge conflicts? Thanks

**Comment by sophia-guo** [comment]
Grinder https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/213/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/214/

**Comment by sophia-guo** [comment]
Wrong grinder:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/218/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/219/

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @sophia-guo !

**Pull request merged**
