### PR TITLE
Modify workflow for pingPerf test docker image built

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Modify pingPerf test docker image built flow
- Related Issue: runtimes_backlog/1071

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test links:
hyc_grinder: 32086

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
Thanks @LongyuZhang . I think we should deliver the https://raw.githubusercontent.com/ibmruntimes/semeru-containers/ibm/$jdkVersion-ea/jdk/ubi/ubi8/Dockerfile.open.releases.full changes into https://github.com/ibmruntimes/semeru-containers repo in the future PRs, so we do not need to change the dockerfile at runtime.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
