### PR TITLE
Re-enable java/lang/Thread/virtual/GetStackTrace.java

### PR DESCRIPTION
**Pull request by fengxue-IS**
Test fixed by https://github.com/eclipse-openj9/openj9/pull/18096
Close: https://github.com/eclipse-openj9/openj9/issues/18052

### CODE REVIEW

**Comment by fengxue-IS** [comment]
[Grinder] (https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/34927/) to verify test passes running

**Comment by fengxue-IS** [comment]
grinder passed @llxia @LongyuZhang can you please review this
FYI @babsingh

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
