### PR TITLE
Add validation for platform strings to exclude_parser.py

### PR DESCRIPTION
**Pull request by jiekang**
Fixes: https://github.com/adoptium/aqa-tests/issues/5650

### CODE REVIEW

**Comment by jiekang** [comment]
@smlambert Would appreciate your thoughts here on the approach before I exit Draft.

And maybe I need to update the GH actions somewhere to fail when this exits with code 1?
And are there other things I can validate while I'm here?

**Comment by sophia-guo** [comment]
Alternative of global ERROR_FOUND ( needed for all log.error) to fail the github check is adding custom handler.

```
class ErrorTrackingHandler(logging.Handler):
    def __init__(self):
        super().__init__()
        self.error_logged = False

    def emit(self, record):
        if record.levelno >= logging.ERROR:
            self.error_logged = True

LOG = logging.getLogger("my_custom_logger")
...

# Add the custom error-tracking handler
error_tracker = ErrorTrackingHandler()
LOG.addHandler(error_tracker)

...
# Check if any ERROR or higher-level messages were logged
if error_tracker.error_logged:
    print("Errors were logged, exiting with error.")
    sys.exit(1)

```

**Comment by jiekang** [comment]
This change now:

1. Updates the entire program to exit with error when an 'Error' is logged
2. Logs an error when multiple spaces are detected in the platform string
3. Only parses files in the directory specified by `--exclude-dir`

**Comment by jiekang** [comment]
This is a breaking change, the process will now exit with code 1 when:

- A file exists in the exclude directory that does not match the ProblemList regex `ProblemList_openjdk(?P<jdk_version>\\d+)-?(?P<jdk_impl>.*).txt`
- The exclude file to parse is not a file
- The format of an exclude string does not fit <Testclass> <URL_to_open_issue> <os-arch_comma-separatedList>
- The os-arch cannot be split via `(?<!x86)(?<!alpine)-`

**Review by smlambert — APPROVED** [review]
This looks very good to me, thanks @jiekang!  Have you use a personal repo to do some basic testing (as many of us end up doing with these workflow PRs)?

**Comment by sophia-guo** [comment]
Based on this change, it detected following errors with openjdk problemlist (current supports jdk version, 8,11,17,21,23,24)

ERROR - ./openjdk/excludes/ProblemList_openjdk23.txt:151 : Not exactly 3 elements when splitting java/net/DatagramSocket/GetLocalAddress.java https://github.com/adoptium/aqa-tests/issues/3088 aix-ppc64, linux-ppc64le
ERROR - ./openjdk/excludes/ProblemList_openjdk23.txt:189 : Not exactly 3 elements when splitting java/io/File/GetXSpace.java https://bugs.openjdk.java.net/browse/JDK-8251466 windows-all, linux-arm, aix-all
ERROR - ./openjdk/excludes/ProblemList_openjdk21.txt:141 : Not exactly 3 elements when splitting java/net/DatagramSocket/GetLocalAddress.java https://github.com/adoptium/aqa-tests/issues/3088 aix-ppc64, linux-ppc64le
ERROR - ./openjdk/excludes/ProblemList_openjdk21.txt:179 : Not exactly 3 elements when splitting java/io/File/GetXSpace.java https://bugs.openjdk.java.net/browse/JDK-8251466 windows-all, linux-arm, aix-all

ERROR - ./openjdk/excludes/ProblemList_openjdk23.txt:151 : Not exactly 3 elements when splitting java/net/DatagramSocket/GetLocalAddress.java https://github.com/adoptium/aqa-tests/issues/3088 aix-ppc64, linux-ppc64le
ERROR - ./openjdk/excludes/ProblemList_openjdk23.txt:189 : Not exactly 3 elements when splitting java/io/File/GetXSpace.java https://bugs.openjdk.java.net/browse/JDK-8251466 windows-all, linux-arm, aix-all
ERROR - ./openjdk/excludes/ProblemList_openjdk24.txt:151 : Not exactly 3 elements when splitting java/net/DatagramSocket/GetLocalAddress.java https://github.com/adoptium/aqa-tests/issues/3088 aix-ppc64, linux-ppc64le
ERROR - ./openjdk/excludes/ProblemList_openjdk24.txt:189 : Not exactly 3 elements when splitting java/io/File/GetXSpace.java https://bugs.openjdk.java.net/browse/JDK-8251466 windows-all, linux-arm, aix-all

**Pull request merged**
