### PR TITLE
Update <plat> to <platform> for disabled element

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=sanity --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=system --target=ParallelStreamsLoadTest_special_J9 --platform=x86-64_windows --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=system --target=special --platform=x86-64_windows --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
internal build: /Grinder/15453/

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=regular --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=sanity --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=sanity --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
This PR depends on https://github.com/adoptium/TKG/pull/202

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=sanity --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
internal grinder: Grinder_TKG/1250

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=sanity --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
