### PR TITLE
Converting SVTTestRepo to ebcdic to execute SVT internal tests on z/OS.

### PR DESCRIPTION
**Pull request by psoujany**
Converting SVTTestRepo to ebcdic to execute SVT internal tests on z/OS.

Added gitattributes to SVTTestRepo and modified system/common.xml which does conversion.

Verification Links
z/OS :- runtimes-jenkins/Test_grinder/job/Grinder/15282
Linux :- runtimes-team-svt-jenkins/Test_grinder/job/Grinder/1246

Fixes: runtimes/backlog/issues/517

### CODE REVIEW

**Comment by llxia** [comment]
This PR does not look correct to me. It changes 43 files. It contains lots of changes that have already delivered to the master.

**Comment by Mesbah-Alam** [comment]
Yes, as Lan said above, the PR seems incorrect. It contains changes from previously delivered PRs (e.g. https://github.com/adoptium/aqa-tests/pull/2559/files).

@psoujany , please recreate this PR with only the changes made for "Converting SVTTestRepo to ebcdic".

**Comment by psoujany** [comment]
As said above re-created new PR with only changes related to SVTTestRepo.
https://github.com/adoptium/aqa-tests/pull/2568

**Comment by Mesbah-Alam** [comment]
@psoujany - by 'recreate', I actually meant recreate the changes in https://github.com/adoptium/aqa-tests/pull/2563 - not recreate the PR literally :) .. but It's all good, we'll review https://github.com/adoptium/aqa-tests/pull/2568.

**Pull request closed without merging**
