### PR TITLE
Update langtools_custom target

### LINKED ISSUE #2692: Update langtools_custom target
Currently we run specific langtools testscase using jdk_custom target, which is a little bit confusing ( especially the description is wrong https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L313, for the target both langtools and jdk custom should use the same target jdk_custom). 

It would be nice to add a separate langtools_custom for langtools tests especially langtools may need different options.

### PR DESCRIPTION
**Pull request by totorororo**
Fixes #2692 
Update langtools_custom target

### CODE REVIEW

**Comment by llxia** [comment]
Thanks @totorororo 
Grinder is launched: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1540/

**Comment by llxia** [comment]
There is no default LANGTOOLS_CUSTOM_TARGET set. @sophia-guo any suggestion what should be good default value?

**Comment by sophia-guo** [comment]
This should be a good one tools/javac/4241573/T4241573.java

**Comment by totorororo** [comment]
added default for LANGTOOLS_CUSTOM_TARGET

**Review by sophia-guo — APPROVED** [review]
LGTM.

**Comment by smlambert** [comment]
Tested via https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1541/

**Review by smlambert — APPROVED** [review]

**Pull request merged**
