### PR TITLE
(v0.8.0-release) Update test material branches to v0.8.0

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3029/

**Comment by llxia** [comment]
FYI @pshipton

**Review by smlambert — COMMENTED** [review]
thanks @llxia !  
these look good, while you are here, may I ask you to also update the JDKx branches to use the following tags:
JDK11_BRANCH=jdk-11.0.14-ga
JDK8_BRANCH=jdk8u322-ga
JDK17_BRANCH=jdk-17.0.2-ga

**Comment by llxia** [comment]
JDKx branches are updated.

**Comment by sxa** [comment]
> JDKx branches are updated.

The JDK11u release is now ready to go but I believe we need this PR with the `-ga` changes to go in

**Review by smlambert — APPROVED** [review]
thanks @llxia !

**Pull request merged**
