### PR TITLE
Clean up get.sh

### PR DESCRIPTION
**Pull request by keithc-ca**
* indent consistently
* don't use `[[` where `[` would suffice
* use `=` instead of `==` when not pattern matching
* use quotes where the expansion might be empty

### CODE REVIEW

**Review by smlambert — APPROVED** [review]
LGTM, but will launch some edge case Grinders nonetheless

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2644/

**Comment by llxia** [comment]
The above Grinder failed with 

image

**Comment by keithc-ca** [comment]
Fixed the `]]` that should have been `]` in
```
./get.sh: line 380: [: missing `]'
```

**Comment by llxia** [comment]
@keithc-ca Could you please test the PR in Grinder? Thanks

**Comment by keithc-ca** [comment]
> @keithc-ca Could you please test the PR in Grinder? Thanks

I started https://openj9-jenkins.osuosl.org/job/Grinder/408/ - hopefully I got the parameters right.

**Comment by keithc-ca** [comment]
All is well except that I didn't specify an existing test:
```
Warning: cannot find the following tests [floatSanityTests] in TESTLIST
```

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2684/

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
