### PR TITLE
Netty update

### PR DESCRIPTION
**Pull request by sophia-guo**
update to latest

exclude failed projects

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/690/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/691/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/692/

**Review by smlambert — APPROVED** [review]

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
Wating for Grinder to be completed

**Comment by llxia** [comment]
In https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/692/

```
01:19:19.132  [INFO] Running io.netty.handler.codec.compression.ZlibCrossTest1
Cancelling nested steps due to timeout
11:07:59.740  Sending interrupt signal to process
11:08:15.455  Terminated
11:08:15.455  
11:08:15.455  netty_test_0_FAILED
```
The test hang and got killed due to timeout.

**Comment by sophia-guo** [comment]
Might be network issue or might be intermittent failure. 

New one: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/694/

**Pull request merged**
