### PR TITLE
Delete code related upstream_openjdk_tests jenkins jobs

### LINKED ISSUE #4157: Delete code related upstream_openjdk_tests jenkins jobs
Those jobs are not needed anymore and has been removed 

details #3963

### PR DESCRIPTION
**Pull request by sophia-guo**
Those jobs are not needed anymore and has been removed

close #4157 
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
CUSTOMIZED_SDK_SOURCE_URL was not added to testjobtemplate. So no delete in testJobTemplate.

**Comment by sophia-guo** [comment]
Grider https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6217/

**Review by smlambert — COMMENTED** [review]
I do not think you can remove the CUSTOMIZED_SDK_SOURCE_URL_OPTION from get.sh as I believe it is in use within Red Hat.  Need to confirm.  It could be removed from Jenkinsfilebase, as that groovy script is currently not used.

**Comment by sophia-guo** [comment]
@smlambert updated.

**Review by smlambert — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
