### PR TITLE
Add SHA1SUMS to list of files to archive in getDependency script

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Add SHA1SUMS to the list of files to be archived 

Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test : Grinder/27996.

**Comment by llxia** [comment]
It is correct to have getDependentLibs. We should not remove it. Please see the [internal issue](https://github.ibm.com/runtimes/openj9-openjdk-jdk11-zos/issues/1623) for details.

**Comment by smlambert** [comment]
Note my comment https://github.com/adoptium/aqa-tests/pull/3971#issuecomment-1249412586

I think that it'd be an update to [getDependentLibs ant target](https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.xml#L26) in TKG that should check if they are already present and not re-fetch.

**Comment by llxia** [comment]
That is correct, Shelley. It is correct to have getDependentLibs. Mesbah has updated the PR to revert getDependentLibs change. And this PR is about archiving the SHA1SUMS file in getDependency.

**Review by llxia — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
> I guess that won't be the place to do it, easier to put the logic into the jcstress/build.xml file, something along the lines of this https://github.com/adoptium/aqa-tests/pull/3697 (check if file exists, if so do not trigger download again).

This could be a second pr?

**Comment by llxia** [comment]
The 3rd party libs download logic is in getDependentLibs in TKG. We have a pre-stage job (test.getDependency) to call it and pre-download all libs to prevent any network/server hiccups. And if the pre-staged copy does not exist or is not up to date (sha check), it will download it again. 
https://github.com/adoptium/aqa-tests/pull/3697 sets us back to the download at runtime. It causes problems when the network is unstable. There is an open issue to update the logic: https://github.com/adoptium/aqa-tests/issues/3921

Just to clarify, the current problem is because get dependency did not set up properly for jcstress.

**Comment by Mesbah-Alam** [comment]
Tested this PR in test.getDependency/10391.

**Comment by llxia** [comment]
Thanks @Mesbah-Alam to deliver the changes via https://github.com/adoptium/aqa-tests/pull/3990 and https://github.com/adoptium/TKG/pull/359. This PR is no longer needed for now.

**Pull request closed without merging**
