### PR TITLE
Add jckforeign.c to list of libs to compile for 19+

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
This resolves RTC 148103

Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
- Test with 19 (where ibjckforeign.dylib needs to be built) : Grinder_JCK/697. 
- Test with 11 : (where ibjckforeign.dylib doesn't need to be built): Grinder_JCK/696. 
- Test where SymbolLookup/MethodsTests.html` (the subtest that needs ibjckforeign.dylib is executed): Grinder_JCK/692 (Note: sub-test results other than `SymbolLookup/MethodsTests.html` under `api/java_lang` are unrelated to this PR and can be ignored).

**Comment by ChengJin01** [comment]
FYI:  @ShelleyLambert, @llxia

**Review by karianna — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
Test on Windows : Grinder_JCK/699.

**Review by llxia — APPROVED** [review]
Thanks @Mesbah-Alam

**Pull request merged**
