### PR TITLE
Add Authorization Code Grant OAuth security test

### PR DESCRIPTION
**Pull request by joeyleeeeeee97**
Related to https://github.com/adoptium/aqa-systemtest/issues/453

### CODE REVIEW

**Comment by smlambert** [comment]
Test via: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1681/

**Comment by joeyleeeeeee97** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1686/console

**Comment by smlambert** [comment]
This needs to be merged after https://github.com/adoptium/aqa-systemtest/pull/457 is merged and after we tag the repos with the v1.0.0 tag.

**Comment by smlambert** [comment]
Now that most October release activities are done, can merge this with its associated aqa-systemtest PR.

**Pull request merged**
