### PR TITLE
Use shellcheck on compile.sh

### PR DESCRIPTION
**Pull request by ultramancoder**
Use shellcheck to verify shell scripts work as intended. Apply fixes as needed to confirm intent and handle corner cases.

### CODE REVIEW

**Comment by smlambert** [comment]
This PR is not related to an open issue and you have not signed the ECA (https://adoptium.net/docs/eca-sign-off).  

It would be good form to begin a conversation via an issue than trying to ram changes into repositories without discussion.

**Comment by ultramancoder** [comment]
Sorry for the error. I am new here so made the mistake. I'll open an issue first for discussion. I did sign the ECA but the status didn't update for some reason, I'll look into it again.

**Comment by smlambert** [comment]
thanks @ultramancoder - the ECA validation check appears to now pass

**Comment by smlambert** [comment]
I am going to close this as not required.

**Pull request closed without merging**
