### PR TITLE
Fetching tweets related to external_custom

### PR DESCRIPTION
**Pull request by SAY-droid427**
Tasks performed:
- Created directory tweetest in buildenv
- Fetched tweets related to the external_custom hash tags

Fixes https://github.com/adoptium/aqa-tests/issues/2785

### CODE REVIEW

**Comment by SAY-droid427** [comment]
Hello @llxia @sophia-guo @smlambert I have created the buidenv/tweetest as of now. Looking forward to your review.
After this I think we will need to store the github_url of the test, the branch name and the test command from the text field of the response object and then pass it along somewhere. After storing the details how do we trigger the tests?

**Comment by smlambert** [comment]
Hi @SAY-droid427 - apologies for the churn on my thoughts on where to put this code.  Now that I see the PR, I think its actually better to put it into the aqa-test-tools repository as its own directory/tool, https://github.com/adoptium/aqa-test-tools/tree/master/Tweetest.  :) 

Exciting to see it coming along!  For triggering tests, if we have the piece that hears the request from the Twitter API, then we can have it produce and print out a URL for a Jenkins Grinder job with all of the "correct" parameters set, so create a URL like the ones produced by the Rerun in Grinder link for the Grinder_Tweetest job:

```
https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=external_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=true&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse-openj9%3Amaster&EXTERNAL_TEST_CMD=ant+test&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FSAY-droid427%2Fopenjdk-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=cleanup-external&EXTERNAL_CUSTOM_REPO=https%3A%2F%2Fgithub.com%2Fapache%2Fzookeeper&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&EXTERNAL_REPO_BRANCH=master&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=azure&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=nightly&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=external%2Fexternal_custom&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None
```

**Comment by smlambert** [comment]
Thanks kindly @SAY-droid427 !  (sorry for the initial misdirection!)

**Comment by SAY-droid427** [comment]
@smlambert Should I open the new issue related to the printing the URL for grinder rerun and others in aqa-test or aqa-test-tools repo?

**Comment by smlambert** [comment]
yes, please create an issue for it in the repo where the code will live (so aqa-test-tools :) ), thanks!

**Pull request closed without merging**
