### PR TITLE
Update bug_report.md

### PR DESCRIPTION
**Pull request by pandenaman007**
Updated bug_report.md .

### CODE REVIEW

**Comment by smlambert** [comment]
Please delete the entire text of the existing bug_report.md file, and then copy / paste the entire markdown formatted code below as is (without changing it) to replace the markdown that you just deleted (including the section at the top with name, about, title, labels, assignees).  There is a handy copy/paste icon when you hover your cursor over the top right corner of the code block below, to make sure you grab the entire piece of it for use to replace the existing text.

Screen Shot 2023-03-04 at 12 35 30 PM


```
name: Failing test report
about: An Issue to describe a failing test
title: '<Test Name> FAILED in <Jenkins Test Job Name> '
labels: ''
assignees: ''

**Failing Test Info**
Test Name:  
Test Duration:  
Machine it fails on: 
Machines it passes on (if intermittent):

**Jenkins Test Job Info**
Jenkins Test Job Name: (Example: Test_openjdk8_hs_extended.openjdk_arm_linux_testList_0)
Jenkins Test Job URL: 
TRSS link for the build (if available):

**Deep History Link from TRSS (if available)**

** Rerun in Grinder Link (if available) or Steps to Reproduce**

**Java Version output (from console output)**

**Relevant Console Output (showing exceptions/errors/crashes)**

**Attach or link to relevant artifacts** 
In the case of test failures, the Jenkins Test Job has test_output.tar.gz artifacts that contain extra logs and core files in the case of crashes.  Please download and inspect these files.  Copy relevant files to an accessible location that can be linked to, or attach relevant files to this issue directly.

```

**Comment by pandenaman007** [comment]
Sorry for the inconvenience I will do it ASAP.

**Comment by smlambert** [comment]
No problem and no rush @pandenaman007 - thanks for taking it on!

**Comment by smlambert** [comment]
Superseded by https://github.com/adoptium/aqa-tests/pull/4394

**Pull request closed without merging**
