### PR TITLE
fixed cut command for jck/splitter/splitter.sh

### PR DESCRIPTION
**Pull request by yaqsun**
The following error occurs when running "echo "$1" | rev | cut -d"/" -f1 -f2 | rev" command

```
cut: only one type of list may be specified
Try 'cut --help' for more information.
```

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by yaqsun** [comment]
Excuse me, how to change entries of jck.mk through the splitter.sh script? Run the splitter.sh script(bash splitter.sh /jck/jck8/JCK-compiler-8c/tests/lang/ANNOT 5) separately and manually change the resulting content to jck.mk?

**Comment by smlambert** [comment]
FYI @llxia @Mesbah-Alam 

@yaqsun - at the moment, the answer to your question is yes.  We have recently discussed how we will also automate this step and break out the content for each version into its own makefiles, but we have not yet delivered that enhancement, so for now, it is as you said.

**Review by karianna — APPROVED** [review]

**Comment by yaqsun** [comment]
> | rev | cut -d"/" -f1 -f2 | rev

```
$ cut --version
$ cut (GNU coreutils) 8.30
```
Run 'echo "JCK-compiler-8c/tests/lang/ANNOT" | rev | cut -d"/" -f1-2 | rev' to output 'lang/ANNOT', run 'echo "JCK-compiler-8c/tests/lang/ANNOT" | rev | cut -d"/" -f1 -f2 | rev' to output 1 error, that is, cut: only one type in the list can be specified. And I looked up some descriptions of cut's -f parameter, which is used as -f1,2 or -f1-2. Maybe I can find some more documentation on cut?

**Comment by sophia-guo** [comment]
@yaqsun that's fine. Both -f1-2 and -f1 -f2 works on my Mac, but -f1-2 may be more common.

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
