### PR TITLE
Upgrade jtreg version for JDK11

### PR DESCRIPTION
**Pull request by llxia**
resolves: https://github.com/eclipse-openj9/openj9/issues/15664

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/1213/

**Comment by llxia** [comment]
FYI @pshipton

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
quick hotspot sniff test: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5365

**Review by smlambert — APPROVED** [review]

**Pull request merged**
