### PR TITLE
RedHat ojdk 17 exclusions

### PR DESCRIPTION
**Pull request by RadekCap**
We are removing ECCurves on our version.

I'm not sure about proper exclusion syntax, pls feel free to point me to some source if exists. I guess it from the existing exclusions around.

### CODE REVIEW

**Comment by karianna** [comment]
@RadekCap can you sign the ECA?

**Comment by smlambert** [comment]
Details on ECA: https://adoptium.net/docs/eca-sign-off/

**Comment by RadekCap** [comment]
Yes, I have signed an older version that required v3. I did it on Friday and re-ran the check. It failed again.

I have double-checked now and in my Eclipse Foundation I can see the following:

... The Eclipse Contributor Agreement 3.1.0 that you signed is valid for a period of three years from date of signing and is set to expire on 2026-02-23.  ....

**Comment by smlambert** [comment]
I believe the ECA validation failure is related to the fact that it sees an email associated with this PR that is not the same as the email in the Eclipse profile you have set up and signed the agreement under:
Screen Shot 2023-02-27 at 8 49 04 AM

**Pull request closed without merging**
