### PR TITLE
Support OPENJCEPLUS_GIT_REPO and OPENJCEPLUS_GIT_BRANCH in testenv.properties

### PR DESCRIPTION
**Pull request by llxia**
- create testenvSettings.sh for testenv variable settings
- export OPENJCEPLUS_GIT_REPO and OPENJCEPLUS_GIT_BRANCH values in testenvSettings.sh
- update functional/OpenJcePlusTests/build.xml to handle branch/tag/sha values
- add JDKXXX_OPENJCEPLUS_GIT_REPO and JDKXXX_OPENJCEPLUS_GIT_BRANCH in testenv.properties
- when DYNAMIC_COMPILE=true, we will run `make <test>` command directly (compile.sh will be skipped)
To fix https://github.com/adoptium/aqa-tests/issues/4509, testenvSettings.sh needs to run before `make <test>` command

resolves: https://github.com/adoptium/aqa-tests/issues/5290 and https://github.com/adoptium/aqa-tests/issues/4509

### CODE REVIEW

**Comment by llxia** [comment]
- `JDK11_OPENJCEPLUS_GIT_BRANCH=1afb341176257c109b65b4151159e0838d1e2fbe`: [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40362/)

**Review by smlambert — COMMENTED** [review]
I'd like to keep newly added scripts organized into the scripts folder.  I haven't looked closely at this PR yet, but wanted to let you know about the existence https://github.com/adoptium/aqa-tests/tree/master/scripts/testenv and that I think testenvSettings.sh should live there.

We should also test how this change impacts the functionality that was added in https://github.com/adoptium/aqa-tests/blob/master/scripts/testenv/checkTags.sh

**Comment by llxia** [comment]
> wanted to let you know about the existence https://github.com/adoptium/aqa-tests/tree/master/scripts/testenv and that I think testenvSettings.sh should live there.

I will move `testenvSettings.sh`  under the folder

> We should also test how this change impacts the functionality that was added in https://github.com/adoptium/aqa-tests/blob/master/scripts/testenv/checkTags.sh

I moved the content from `compile.sh` into `testenvSettings.sh` and added OPENJCEPLUS changes. Since `testenvSettings.sh` is used in multiple places (i.e., `compile.sh`, before `make <test>` , potentially in get.sh in the future), it should be a separate script for common use. 

This PR should not impact https://github.com/adoptium/aqa-tests/blob/master/scripts/testenv/checkTags.sh because `checkTags.sh` gets triggered in https://github.com/adoptium/aqa-tests/blob/master/get.sh#L780, which is before compilation and test run. `testenvSettings.sh`  exports the values in testenv.prtoperties. 

Also, since `checkTags.sh` gets triggered when USE_TESTENV_PROPERTIES=true, it got triggered via the above test runs. 
```
00:00:27.005  Running checkTags with ./testenv/testenv.properties and 11
00:00:28.433  Use branch name dev from ./testenv/testenv.properties
```
However, if you have a better way of testing it, please let me know.

**Comment by smlambert** [comment]
> However, if you have a better way of testing it, please let me know.

I just wanted to check that things still get called.  Since checkTags only refers to the JDK_BRANCH, there is nothing to add there to support the OPENJCEPLUS tags.

Thanks @llxia !

**Review by smlambert — APPROVED** [review]

**Review by pshipton — APPROVED** [review]

**Comment by llxia** [comment]
reran with folder change (**WIP** - will update when the Grinders are done):
- jdk_math: [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40387/)
- jdk_math windows: [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40389/)
- openJcePlusTests USE_TESTENV_PROPERTIES=true, DYNAMIC_COMPILE=true: [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40390/)
- MiniMix_5m: [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40391/)

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
