### PR TITLE
Update openj9 branches to v0.30.0-release in aqa-tests v0.8.0-release branch

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3014

```
[2022-01-17T22:46:05.501Z] get functional test material...
[2022-01-17T22:46:05.501Z] git clone --depth 1 -b v0.30.0-release https://github.com/eclipse-openj9/openj9.git
```

**Comment by llxia** [comment]
FYI @pshipton

**Comment by pshipton** [comment]
This is good for OpenJ9. I assume the other repos are going to separately get tagged for the release as well?

**Review by smlambert — APPROVED** [review]
thanks Lan!  
We will also need to update AQAvit repos (TKG, STF and aqa-systemtest) to use the v0.8.0 tags that have been created (noting I did not branch those as it is unnecessary to do so.

We'll also update the OpenJDK 8u, 11u and 17u to specific tags, but we can also do those under separate PRs.

**Comment by llxia** [comment]
Any preference of what we should tag https://github.com/eclipse-openj9/openj9-systemtest with? `v0.8.0` or `v0.30.0-release`? If not, I am thinking to tag it with `v0.8.0`, so it aligns with the rest test material.

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
