### PR TITLE
Add Temurin specific excludes for July

### PR DESCRIPTION
**Pull request by smlambert**
- Add Temurin specific exclude files
- For JDK21+ exclude AbsPathsInImage due to OOM on public Adoptium nodes
- For JDK11+ exclude SecureDS on linux-all as not supported on alpine-linux and jtreg currently does not differentiate alpine-linux from other linux platforms.  Will plan to raise an issue to fix in upstream jtreg, so can have a more specific exclude later.
- VersionCheck exclude on JDK8/x64Linux
- TestHumongousCodeCacheRoots JDK8/aix exclusion

### CODE REVIEW

**Comment by jiekang** [comment]
### Windows x86_64 test exclude proposal:


**Failures due to lack of WSL:**
JDK 11
```
com/sun/jdi/JdbReadTwiceTest.sh
```
JDK 21
```
javax/script/ScriptEngineOrder.sh
javax/script/ProviderTest.sh
```

Also 49 failures in jdk_instrument_0
https://trss.adoptium.net/output/test?id=6692d8e2d24e1b006e221ffb

**Failures due to headless**

JDK 17
```
java/beans/PropertyEditor/6380849/TestPropertyEditor.java
java/beans/PropertyEditor/TestColorClass.java
java/beans/PropertyEditor/TestColorClassJava.java
java/beans/PropertyEditor/TestColorClassNull.java
java/beans/PropertyEditor/TestColorClassValue.java
java/beans/PropertyEditor/TestFontClass.java
java/beans/PropertyEditor/TestFontClassJava.java
java/beans/PropertyEditor/TestFontClassNull.java
java/beans/PropertyEditor/TestFontClassValue.java
java/beans/XMLEncoder/java_awt_ScrollPane.java
javax/imageio/plugins/jpeg/JPEGsNotAcceleratedTest.java
```

JDK 21
```
java/beans/PropertyEditor/6380849/TestPropertyEditor.java
java/beans/PropertyEditor/TestColorClass.java
java/beans/PropertyEditor/TestColorClassJava.java
java/beans/PropertyEditor/TestColorClassNull.java
java/beans/PropertyEditor/TestColorClassValue.java
java/beans/PropertyEditor/TestFontClass.java
java/beans/PropertyEditor/TestFontClassJava.java
java/beans/PropertyEditor/TestFontClassNull.java
java/beans/PropertyEditor/TestFontClassValue.java
java/beans/XMLEncoder/java_awt_ScrollPane.java
javax/imageio/plugins/jpeg/JPEGsNotAcceleratedTest.java
```

JDK 22
```
java/beans/PropertyEditor/6380849/TestPropertyEditor.java
java/beans/PropertyEditor/TestColorClass.java
java/beans/PropertyEditor/TestColorClassJava.java
java/beans/PropertyEditor/TestColorClassNull.java
java/beans/PropertyEditor/TestColorClassValue.java
java/beans/PropertyEditor/TestFontClass.java
java/beans/PropertyEditor/TestFontClassJava.java
java/beans/PropertyEditor/TestFontClassNull.java
java/beans/PropertyEditor/TestFontClassValue.java
java/beans/XMLEncoder/java_awt_ScrollPane.java
javax/imageio/plugins/jpeg/JPEGsNotAcceleratedTest.java
```

**Known MBCS issue**

JDK 22
```
MBCS_Tests_formatter_tw_windows_0 
```

**Comment by jiekang** [comment]
Noting here: For Adoptium, WSL failures can be sidestepped by running the test on: `test-azure-win2016-x64-1`, `test-azure-win2019-x64-1`, or `test-azure-win2022-x64-1`
So we could choose not to exclude them.

**Comment by llxia** [comment]
https://github.com/adoptium/aqa-tests/pull/5447 is merged first. Could you resolve the merge conflict in this PR?

**Comment by smlambert** [comment]
Close this PR in favour of new / clean one, https://github.com/adoptium/aqa-tests/pull/5450 that will cherrypick into release branch also.

**Pull request closed without merging**
