### PR TITLE
Exclude problematic tests on Win32 with related issues opened.

### PR DESCRIPTION
**Pull request by sophia-guo**
Exclude problematic tests on Win32 with related issues opened.

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Review by smlambert — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
@sophia-guo - can you resolve the conflict please?

**Comment by sophia-guo** [comment]
@smlambert resolved. Thanks!

**Pull request merged**
