### PR TITLE
Switch source file for jckforeign lib on JDK20+

### PR DESCRIPTION
**Pull request by sxa**
Untested PR at present, but the theory is sound :-)

The source file of a new dependent library has been changed between 19 and 20.

### CODE REVIEW

**Review by smlambert — APPROVED** [review]

**Comment by sxa** [comment]
Patch has been tested and verified

**Comment by Mesbah-Alam** [comment]
Was this PR tested? We have been seeing tck 20 builds failing at native compile step across all platforms with following error: 

```
00:03:05.924       [exec] rm -rf /home/jenkins/jck_root/JCK20-unzipped/natives/linux/
00:03:05.924       [exec] mkdir -p /home/jenkins/jck_root/JCK20-unzipped/natives/linux/
00:03:05.924       [exec] cd /home/jenkins/jck_root/JCK20-unzipped/natives/linux/ && gcc -fPIC -I/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jni/include/solaris -I/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jni/include/linux -I/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src -I"/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20" -I"/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jni/include" -I"/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jvmti/include" -shared  /home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jni/jckjni.c -o/home/jenkins/jck_root/JCK20-unzipped/natives/linux/libjckjni.so
00:03:09.860       [exec] cd /home/jenkins/jck_root/JCK20-unzipped/natives/linux/ && gcc -fPIC -I/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jni/include/solaris -I/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jni/include/linux -I/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src -I"/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20" -I"/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jni/include" -I"/home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jvmti/include" -shared  /home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/src/share/lib/jvmti/jckjvmti.c -o/home/jenkins/jck_root/JCK20-unzipped/natives/linux/libjckjvmti.so
00:03:13.088       [exec] make[2]: Leaving directory '/home/jenkins/workspace/Test_openjdk20_j9_sanity.jck_s390x_linux_testList_2/aqa-tests/jck'
00:03:13.088       [exec] make[2]: *** No rule to make target 'Linker.c', needed by 'libjckforeign.so'.  Stop.
00:03:13.088   
````

**Comment by Mesbah-Alam** [comment]
List of directories under `$(SRCDIR)$(D)tests$(D)api$(D)java_lang$(D)foreign` is different in 19 and 20 : 

19: https://github.ibm.com/runtimes/JCK19-unzipped/tree/main/JCK-runtime-19/tests/api/java_lang/foreign
20: https://github.ibm.com/runtimes/JCK20-unzipped/tree/main/JCK-runtime-20/tests/api/java_lang/foreign

**Comment by Mesbah-Alam** [comment]
https://github.com/adoptium/aqa-tests/pull/4466#issuecomment-1487323233 - Taking the question back. Internal failures are likely due to internal 20 repo missing folders under $(SRCDIR)$(D)tests$(D)api$(D)java_lang$(D)foreign.

**Comment by smlambert** [comment]
Let's take this conversation offline.  This change was tested as we just completed the TCK runs for JDK20 Temurin [March release](https://github.com/adoptium/adoptium/issues/218).  There was another issue, which has not yet been addressed in the aqa-tests repo based on the new targets that were added via https://github.com/adoptium/aqa-tests/pull/4454 which we can also discuss in a private Slack thread.

**Comment by sxa** [comment]
> Hi @sxa , this PR breaks JCK21 (see the [comment above](https://github.com/adoptium/aqa-tests/pull/4466#issuecomment-1631230465)), could you please take a look? Thanks

I don't have access to JCK21 so I am unable to do anything with this.

**Comment by ChengJin01** [comment]
> > Hi @sxa , this PR breaks JCK21 (see the [comment above](https://github.com/adoptium/aqa-tests/pull/4466#issuecomment-1631230465)), could you please take a look? Thanks
> 
> I don't have access to JCK21 so I am unable to do anything with this.

@sxa,  No worries.  @llxia and I already fixed up the issue on our side.

**Pull request merged**
