### PR TITLE
Deleted lines with issues in ProblemList_openjdk17.txt file

### PR DESCRIPTION
**Pull request by maiia-pi**
Deleted lines with issues in ProblemList_openjdk17.txt file which passed the test:
https://bugs.openjdk.java.net/browse/JDK-8221400
https://bugs.openjdk.java.net/browse/JDK-8173082

### CODE REVIEW

**Review by smlambert — COMMENTED** [review]
@maiia-pi - you can't delete the .gitignore file, there are items in the file that need to be there

**Comment by maiia-pi** [comment]
@smlambert Should I return it back?

**Comment by smlambert** [comment]
Yes it should not be deleted or changed.  Your original PR had added changes to it which should not be included.

**Comment by smlambert** [comment]
hi @maiia-pi - are you able to restore the .gitignore file?  The change to the ProblemList file looks good, so the only thing blocking the approval of this PR is that the .gitignore file needs to be restored to the version that is currently in the master branch.

**Comment by smlambert** [comment]
Closing as stale (same note as your other PR can not delete the .gitignore file, reopen if you still want to work on this, and restore the missing file).  Thanks.

**Pull request closed without merging**
