### PR TITLE
jck: run headless tests on alpine

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
No issue at IBM internal side : Grinder/20204.

**Comment by karianna** [comment]
@gdams - Can this be taken out of draft?

**Comment by gdams** [comment]
@ShelleyLambert using the keyword seemed to work! This one is ready for merge now!

**Review by smlambert — APPROVED** [review]
thanks @gdams !

**Pull request merged**
