### PR TITLE
Support multiple jdk custom targets

### LINKED ISSUE #4015: Support multiple testcases for jdk_custom
There has always be the requirement for supporting multiple testcases for jdk_custom target. Based on the solution for a different issue https://github.com/adoptium/aqa-tests/issues/3993#issuecomment-1259419584 it might be worth to try and support that feature.

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #4015 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
x64-linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6133/
windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6134/

**Review by llxia — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
I would have also suggested updating 
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L358 as 'living' documentation for this enhancement.

**Pull request merged**
