### PR TITLE
Add TKG ITERATION options

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
grinder: Grinder_TKG/1760/

**Comment by sophia-guo** [comment]
Just a common note, run-aqa also needs to update to support the features like this ( related with adding extra environment variables or jenkins parameters ).

**Review by karianna — APPROVED** [review]
LGTM

**Comment by renfeiw** [comment]
tested in Grinder/30114/

**Pull request merged**
