### PR TITLE
Fix external tests git install problem

### LINKED ISSUE #2900: External wildfly, spring, system-test, and functional-test failed with “git not found” error
Testname: external/wildfly, external/spring, external/system-test, external/functional-test
jdk_impl: openj9
jdk_verison: 11
platform: xlinux
test_link: 
- https://ci.adoptopenjdk.net/job/Grinder_wildfly/2/console
- https://ci.adoptopenjdk.net/job/Grinder_spring/2/console
- https://ci.adoptopenjdk.net/job/Grinder_system-test/2/console
- https://ci.adoptopenjdk.net/job/Grinder_functional-test/2/console
```
20:09:22       [exec] Step 14/18 : RUN git clone
20:09:22       [exec]  ---> Running in fbbde2c78917
20:09:23       [exec] [91m/bin/sh: 1: git: not found
20:09:23       [exec] The command '/bin/sh -c git clone' returned a non-zero code: 127
20:09:23       [exec] [0m
20:09:23  
20:09:23  BUILD FAILED
20:09:23  /home/jenkins/workspace/Grinder_functional-test/aqa-tests/TKG/scripts/build_test.xml:76: The following error occurred while executing this line:
20:09:23  /home/jenkins/workspace/Grinder_functional-test/aqa-tests/external/functional-test/build.xml:25: The following error occurred while executing this line:
20:09:23  /home/jenkins/workspace/Grinder_functional-test/aqa-tests/external/build.xml:87: exec returned: 127
```

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Fix "git not found" problem in several external tests
Closes #2900

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Links:
wildfly: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1495
spring: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1496
functional-test: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1497
system-test: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1498

**Review by smlambert — APPROVED** [review]
thanks @LongyuZhang !

**Review by llxia — APPROVED** [review]
Thanks @LongyuZhang .

**Comment by llxia** [comment]
It looks like most values in the properties files are the same. I think we should have the default value if the property is not set. An enhancement in future PR. :)

**Pull request merged**
