### PR TITLE
Exclude overrunning SPARCV9 tests

### PR DESCRIPTION
**Pull request by adamfarley**
These tests take between 10 mins and 2 hours to run, so I'm excluding them to avoid timeouts. Anyone who wants them put back in should feel free to propose faster machines, make the case for 5 extra hours of runtime per execution, or find a solution for the cause of the timeouts.

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Review by sxa — COMMENTED** [review]
@adamfarley Can you adjust the title of the PR+Commit message to say "SPARC" rather than "Spark" please

**Comment by adamfarley** [comment]
Sure thing Stewart. Will remember that for the future.

**Review by sxa — APPROVED** [review]
I'm happy with this but it would be good to have an explicit 👍🏻 on this from @smlambert too before merging.

**Review by smlambert — APPROVED** [review]
I approve it, though I think excluding the 10 min tests is likely more aggressive than required.  We may revisit those to reinclude some at some point in the future.

**Pull request merged**
