### PR TITLE
updated ITERATIONS description

### PR DESCRIPTION
**Pull request by prahasR**
Solves #2941

### CODE REVIEW

**Comment by smlambert** [comment]
Waiting for https://ci.adoptopenjdk.net/view/work-in-progress/job/WIP_Test_Job_Auto_Gen/53 to complete to launch a test for this PR.  (Weekend test runs are running and consuming all resources at present, expect to kick the PR test off later today).

**Comment by smlambert** [comment]
@prahasR - can you make sure to sign the ECA (https://www.eclipse.org/legal/ECA.php) and ensure that the email of your Eclipse profile and the one associated with the github account & commit are the same so that the eclipsefdn/eca validation check passes ?

**Comment by prahasR** [comment]
@smlambert I signed the ECA, is it fine now?

**Comment by smlambert** [comment]
Testing via: https://ci.adoptopenjdk.net/view/work-in-progress/job/WIP_Test_Job_Auto_Gen/54/

**Comment by smlambert** [comment]
Screen grab of section of job generated in the test run:

Screen Shot 2021-10-02 at 11 39 08 AM

**Review by smlambert — APPROVED** [review]
thanks @prahasR !

**Comment by prahasR** [comment]
@smlambert can you please merge it also.

**Comment by smlambert** [comment]
PRs in this repository require 2 reviewers, I am waiting for my fellow reviewers to be online (Monday in their work hours) to request the second review, upon which time this can be merged.

**Review by sophia-guo — APPROVED** [review]
LGTM

**Pull request merged**
