### PR TITLE
Add support for Orka

### LINKED ISSUE #4899: Smoke tests failing on aarch64 mac platforms (related to Orka dynamic agents)
Thank you for reporting a broken build! Please fill in the following details:

- **Jenkins link to the failing log:**
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-mac-aarch64-temurin_SmokeTests/215/console
- **Which platforms (OS+arch) are affected?:** mac platforms
- **If you look at the historic logs, does the problem appear to be specific to one machine?**
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))**

All aarch64 mac nodes are now being spun up from Orka, which means no static machines are waiting for a test job being sent to them.  This was addressed for AQAvit tests via this [PR/844](https://github.com/adoptium/ci-jenkins-pipelines/pull/844), but for some reason the smoke tests do not call into this method ([waitForANodeToBecomeActive()](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L1759-L1796)).

x86 mac smoke tests are running and passing because there are still 2 static machines online in Jenkins, so jobs find available nodes

### PR DESCRIPTION
**Pull request by smlambert**
Fixes #4899 

Update PLATFORM_MAP with Orka dynamic agent for Mac platforms

### CODE REVIEW

**Comment by smlambert** [comment]
Grinder on aarch64_mac: https://ci.adoptium.net/view/Test_grinder/job/Grinder/8139/

**Comment by sophia-guo** [comment]
This PR is eventually needed.

However this might not be the fix for https://github.com/adoptium/aqa-tests/issues/4899. See my comment in https://github.com/adoptium/aqa-tests/issues/4899

I run a grinder with master which still works for mac aarch64 as in grinder the ACTIVE_NODE_TIMEOUT will be set as 15 min.
https://ci.adoptium.net/view/Test_grinder/job/Grinder/8154/console

**Comment by sophia-guo** [comment]
In short the orka test agent is used in a different way from the current dynamic agents logic is aqa-tests.

**Comment by smlambert** [comment]
@sophia-guo - by your comment, do you feel this PR, https://github.com/adoptium/ci-jenkins-pipelines/pull/853 is a preferred approach?  If so, I can close this one and move that one out of draft.

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
Ugh sorry, pulled the trigger too fast - reversal PR https://github.com/adoptium/aqa-tests/pull/4913

**Pull request merged**
