### PR TITLE
Archive testenv properties

### PR DESCRIPTION
**Pull request by psaunderualberta**
Issue: #3084

### CODE REVIEW

**Comment by psaunderualberta** [comment]
[Grinder](https://ci.adoptopenjdk.net/job/Grinder/2173/)

**Comment by llxia** [comment]
hmm, not sure if it is related to docker, I do not see any file attached in the above Grinder.
We are expecting to see both testenv.properties and SHA.txt archived.

**Comment by psaunderualberta** [comment]
(Grinder)[https://ci.adoptopenjdk.net/job/Grinder/2301/]

Let me know if this one doesn't work either.

**Comment by sophia-guo** [comment]
This looks good. https://github.com/adoptium/aqa-tests/pull/3085#issuecomment-956770132

**Comment by llxia** [comment]
No, I still do not see any archived files. I am not sure it is related to your PR. Need investigation.

This is what I am looking for:
image

https://ci.adoptopenjdk.net/job/Grinder/2309/

**Comment by sophia-guo** [comment]
I believe I see the files in https://ci.adoptopenjdk.net/job/Grinder/2301/. But today when I looked again, no files. Rerun it's there https://ci.adoptopenjdk.net/job/Grinder/2326/ 

Screen Shot 2021-11-03 at 9 23 45 AM

I can see some other earlier grinder doesn't have sha.txt archived.

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/job/Grinder/2309/ doesn't have that files https://github.com/adoptium/aqa-tests/pull/3085#issuecomment-957512716. Did the build 2309 have that txt files before?

Is there configuration about only a specific number of builds archive will be kept? As I saw only the latest five grinder have the archived files.

**Comment by sophia-guo** [comment]
Yes, I believe that jenkins some default configuration. The build https://ci.adoptopenjdk.net/job/Grinder/2322/ is the fifth latest jobs and have that .txt files archived. 

Screen Shot 2021-11-03 at 9 30 09 AM

Then when it became the sixth latest I can't find the archived files any more.
Screen Shot 2021-11-03 at 9 37 01 AM

**Comment by llxia** [comment]
Yes, I do not think the issue is related to this PR. Grinder at Openj9 worked as expected
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/337/
image

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
FYI I updated the `Max # of builds to keep with artifacts` in Grinder to 30.

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
