### PR TITLE
Removed JRE_IMAGE in openjdk.mk

### PR DESCRIPTION
**Pull request by akanbifatimah**
I have removed the JRE_IMAGE in openjdk.mk. Thank you.

### CODE REVIEW

**Comment by llxia** [comment]
@akanbifatimah Thanks for the PR. Please create a separate PR for Added DYNAMIC_COMPILE in testJobTemplate

**Comment by llxia** [comment]
You, you have to PRs - this one and #3037. DYNAMIC_COMPILE change is in both PRs. Since this PR is for Removed JRE_IMAGE, please remove DYNAMIC_COMPILE change from this PR.

**Comment by akanbifatimah** [comment]
Thank you so much for your guidance, I understand now and will effect it immediately, thank you once again.

**Comment by akanbifatimah** [comment]
Thank you @smlambert and @llxia , I learnt new things from the project

**Pull request merged**
