### PR TITLE
re-enable jdk 17 tests excluded by issue 248

### PR DESCRIPTION
**Pull request by yinggzz**
Partial Fixes: #3214

Signed-off-by: Ying Zhou

### CODE REVIEW

**Comment by smlambert** [comment]
run aqa --help

**Comment by Mesbah-Alam** [comment]
`Fixes: #3214` will close https://github.com/adoptium/aqa-tests/issues/3214 when this PR gets merged. But since we have other PRs related to https://github.com/adoptium/aqa-tests/issues/3214, I suggest we use something like "Related to" or "Partially fixes" instead of "Fixes".

**Comment by Mesbah-Alam** [comment]
Also, please feel free to post the Grinder links that test this PR on HotSpot and OpenJ9.

**Comment by yinggzz** [comment]
Grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3167/

**Pull request closed without merging**
