### PR TITLE
Remove runAqaConfig.json

### PR DESCRIPTION
**Pull request by nadeensami**
Allow custom repos to be set by the users as command arguments rather than in runAqaConfig.json.

Fixes: #3163

Signed-off-by: Nadeen Mohamed <nadeen@ualberta.ca>

### CODE REVIEW

**Comment by llxia** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target jdk_math --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Review by llxia — APPROVED** [review]
Thanks @nadeensami

**Review by smlambert — APPROVED** [review]

**Comment by llxia** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target jdk_math --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux --tkg_repo nadeensami:issue-3163

**Comment by llxia** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target jdk_math --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux --tkg_repo nadeensami//TKG:issue-3163

**Comment by llxia** [comment]
Never mind, we cannot test PR https://github.com/adoptium/TKG/pull/259 and this PR using `run aqa` :

image

**Comment by smlambert** [comment]
Since there are several related PRs including https://github.com/adoptium/TKG/pull/259, will hold off on merging them until all are reviewed and can be merged together.

**Pull request merged**
