### PR TITLE
Revert "jck: Use multiJVM=group"

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Reverts adoptium/aqa-tests#4499

Jck testing has shown on at least Windows x64 that numerous test groups fail with memory exhaustion, and many testcase failures. It looks like the persistent multi agent JVM, at least on Windows leaks memory over time...

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
@sxa i'll run a jdk17 and a jdk20 build run tonight, and we can see, some jck jobs failed due to the "host verification failed..." so a bunch of tests were not run... I'm suspecting the other platforms maybe more resiliant !

**Comment by andrew-m-leonard** [comment]
Just running jdk17 over night: https://ci.adoptium.net/job/build-scripts/job/release-openjdk17-pipeline/22/

**Comment by andrew-m-leonard** [comment]
> > Just running jdk17 over night: https://ci.adoptium.net/job/build-scripts/job/release-openjdk17-pipeline/22/
> 
> To be clear, that's with group still enabled, not with this PR's revert right?

@sxa Yes, so we can see effects on tests on all platforms

**Comment by andrew-m-leonard** [comment]
@sxa @smlambert Maybe to play it safe for the release, we just merge this into the new aqa release branch, and we can spend some more time judging the multi group effects for next release, thoughts?
I don't fancy risking it for this release

**Comment by sxa** [comment]
> @sxa @smlambert Maybe to play it safe for the release, we just merge this into the new aqa release branch, and we can spend some more time judging the multi group effects for next release, thoughts? I don't fancy risking it for this release

I'd rather have it with the group option enabled. But let's see the result of the JDK17 run before making any decisions. Can you kick off a JDK20 TCK run one with this PR's branch as a comparison?

**Comment by andrew-m-leonard** [comment]
Workaround via PR: https://github.com/adoptium/aqa-tests/pull/4506

**Pull request closed without merging**
