### PR TITLE
Decouple JCK from STF

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves backlog/issues/372

- Adds a stand-alone Java program (JavaTestRunner.java) that can run collect all information to launch javatest.jar to run jck tests.  
- Adds makefile that compiles jck natives 
- Updates jck/build.xml to : 
    - Remove logic to checkout systemtest and stf 
    - Add logic to compile JavaTestRunner.java and JCK natives 
- Updates jck.mk to : 
    -  Add command line to invoke JavaTestRunner.java 
- Updates jck playlist xml files to use the new command line 
 
Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test with JDK11 `extended`: 
- x64 Linux : Grinder/16543

Test with JDK16 `extended` 
- mac : Grinder/16544

**Comment by llxia** [comment]
Just for the record, as discussed, we should deliver this PR to a branch, not master.

**Comment by Mesbah-Alam** [comment]
Failures reported in the extended runs above will need some time to be investigated (details in backlog/issues/372). This will likely cause some updates to the PR. However, since the sanity runs are green, I think the code-review can start already.

**Comment by llxia** [comment]
This PR is intended for `JavaTestRunner ` branch, not master. Please update the PR to point to JavaTestRunner. Thanks

**Comment by smlambert** [comment]
I am happy to merge this into a JavaTestRunner branch, and then soak with it a while, so we can see that it is working well.  Thanks for this effort, it certainly reduces complexity and the amount of time to compile and reduces our overall technical debt.  Thanks @Mesbah-Alam !

**Comment by Mesbah-Alam** [comment]
Further testing: 
- Extended.jck with JDK8 on Windows: Grinder/16643/
- Extended.jck with JDK16 on zLinux: Grinder/16644

**Comment by llxia** [comment]
It is great that we can reduce the complexity and dependencies! Thanks so much for the work @Mesbah-Alam !

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM, a good long soak in its JavaTestRunner branch, updating if we observe issues and we can eventually plan to merge JavaTestRunner branch into master after upcoming releases when this has been given time to see any other issues that may arise.  Thanks @Mesbah-Alam !

**Pull request merged**
