### PR TITLE
Initial update of camel

### PR DESCRIPTION
**Pull request by sophia-guo**
Related with #3468 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
jdk17: 
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/614/

**Comment by sophia-guo** [comment]
This PR update the way of running camel to fix the issues of test framework. Tests are available for jdk11+.  There are still tests failures, which will be updated at #3468. If tests failures are jdk version dependant, we can do the same way as in #3520

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM

**Pull request merged**
