### PR TITLE
Excluded new written security infra tests

### PR DESCRIPTION
**Pull request by sophia-guo**
Related https://github.com/adoptium/aqa-tests/issues/4808

### CODE REVIEW

**Comment by pshipton** [comment]
Pls add the excludes to the J9 exclude lists as well.

**Comment by smlambert** [comment]
To ease this change, could consider just excluding the jdk_security_infra target since these 44 failing testcases are the bulk of it (it has 45 testcases, only 1 passing).

@Haroon-Khel - FYI, this is the first exercising of the disabled_tests linter, see that it has an error:
```
Run find . -name "playlist.xml" | python3 ./scripts/disabled_tests/playlist_parser.py -v > /dev/null
Traceback (most recent call last):
  File "/home/runner/work/aqa-tests/aqa-tests/./scripts/disabled_tests/playlist_parser.py", line 9, in <module>
    import lxml.etree
ModuleNotFoundError: No module named 'lxml'
Error: Process completed with exit code 1.
```

Screenshot 2024-01-10 at 1 57 08 PM

**Comment by pshipton** [comment]
> Pls add the excludes to the J9 exclude lists as well.

There is one complication. The tests should be excluded for all OpenJ9 platforms except for z/OS.

**Comment by sophia-guo** [comment]
Disabled by playlist.xml for all platforms. Deleted disabled tests in Problemlist.txt as tests have been rewritten with new framework those tests are not available anymore. 

Those tests failed for all platforms, any reason we need to keep them for z/OS @pshipton ?

**Review by smlambert — APPROVED** [review]

**Comment by sophia-guo** [comment]
@pshipton Thanks, updated.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
The linter failed so I won't merge this now.

**Comment by sophia-guo** [comment]
Linter issue is related with [refer to ](https://github.com/adoptium/aqa-tests/pull/4942) . see https://github.com/adoptium/aqa-tests/pull/4955#issuecomment-1885444642.

**Pull request merged**
