### PR TITLE
Exclude jdk_container subtests for linux 

### PR DESCRIPTION
**Pull request by annaibm**
Exclude jdk_container subtests for all linux versions

### CODE REVIEW

**Comment by annaibm** [comment]
Grinder tests:
RHEL7:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39073/
cent7
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39074/

**Comment by karianna** [comment]
@annaibm Failing tests

**Comment by llxia** [comment]
related: https://github.com/eclipse-openj9/openj9/issues/19176

**Comment by llxia** [comment]
re https://github.com/adoptium/aqa-tests/pull/5162#issuecomment-2016640140, PR builds do not test personal repos. It is a known issue https://github.com/adoptium/aqa-tests/issues/4855. PR builds should be disabled to avoid confusion.

**Comment by llxia** [comment]
!rhel.7: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39155/

**Comment by annaibm** [comment]
cent8x86-svl-rt8-1.fyre.ibm.com
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39219/
sles15x86-rtp-rt1-1.fyre.ibm.com
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39209/

**Review by karianna — APPROVED** [review]

**Review by llxia — APPROVED** [review]

**Comment by llxia** [comment]
Thanks @annaibm . Please back port this change into https://github.com/adoptium/aqa-tests/tree/v1.0.1-release

**Comment by annaibm** [comment]
@llxia Please find the PR for porting the changes into [v1.0.1 -release](https://github.com/adoptium/aqa-tests/tree/v1.0.1-release):  
[5185](https://github.com/adoptium/aqa-tests/pull/5185)

**Pull request merged**
