### PR TITLE
Set default LIGHT_WEIGHT_CHECKOUT to true

### PR DESCRIPTION
**Pull request by llxia**
related: https://github.com/adoptium/aqa-tests/issues/4580

### CODE REVIEW

**Comment by llxia** [comment]
https://ci.adoptium.net/job/WIP_Test_Job_Auto_Gen/77/
https://ci.adoptium.net/job/Test_openjdk17_j9_sanity.perf_x86-64_linux/205/

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Looks like https://issues.jenkins.io/browse/JENKINS-42971 was fixed, do we still need this?

**Comment by AdamBrousseau** [comment]
@karianna correct that is resolved, which is why we are making this change. We will be taking advantage of lightweight checkout while still using parameterized scm values, at least for branch.

**Review by karianna — APPROVED** [review]

**Pull request merged**
