### PR TITLE
Remove JDK8 restriction for alpine library path

### PR DESCRIPTION
**Pull request by Haroon-Khel**
Testing to see if this fixes https://github.com/adoptium/aqa-tests/issues/5425 and https://github.com/adoptium/infrastructure/issues/3529

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
Running jdk 11 tests on test-docker-alpine320-x64-1 which is using jdk21 as its default https://ci.adoptium.net/job/Grinder/10571/console

**Review by sxa — CHANGES_REQUESTED** [review]
Lines 330 and 623 need the same change (623 will specifically resolve the problem during the compile phase)

Verified at https://ci.adoptium.net/job/Grinder/10581/console

**Comment by Haroon-Khel** [comment]
AQA test pipeline for JDK8 11 17 and 21 on all of our x64 Alpine boxes to make sure other JDKs arent affected
https://ci.adoptium.net/job/AQA_Test_Pipeline/335/console

**Review by sxa — APPROVED** [review]
> AQA test pipeline for JDK8 11 17 and 21 on all of our x64 Alpine boxes to make sure other JDKs arent affected https://ci.adoptium.net/job/AQA_Test_Pipeline/336/console

Thanks - granting my approval on the condition that  those tests pass successfully.

**Comment by Haroon-Khel** [comment]
Its having trouble building the downstream jobs off my branch, https://ci.adoptium.net/job/Test_openjdk8_hs_special.functional_x86-64_alpine-linux/112/console for example
```
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress --prune -- origin +refs/heads/alpine.library:refs/remotes/origin/alpine.library" returned status code 128:
stdout: 
stderr: fatal: couldn't find remote ref refs/heads/alpine.library
```
Its using `origin` in place of my fork. My fork and branch have been passed to the job in the parameters section

**Comment by sxa** [comment]
> Its using `origin` in place of my fork. My fork and branch have been passed to the job in the parameters section

Interesting - I hit a similar issue recently too - maybe post in #aqa-tests to see if anyone can explain/mitigate it? Can't think why Grinder would be different but I think that's what I experienced too.

**Comment by Haroon-Khel** [comment]
Each of the grinders compiled and were built fine, other jdks have not been affected. This pr can be merged

**Review by smlambert — APPROVED** [review]
thanks @Haroon-Khel - can you cherrypick this PR to the v1.0.2-release branch as well?

**Pull request merged**
