### PR TITLE
Fix typo in platform name for x86-64_windows

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Fix typo in platform name for x86-64_windows

Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Could we have a Grinder for this PR? Thanks

**Comment by Mesbah-Alam** [comment]
Test: Grinder/28853.

**Review by llxia — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
