### PR TITLE
Support nested zip file

### PR DESCRIPTION
**Pull request by llxia**
Related: https://github.com/adoptium/aqa-tests/issues/3531

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
internal/Grinder/22550/
```
00:00:17.684  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/openjdk11-pipeline-IBM/127/artifact/target/linux/x64/openj9/*.tar.gz/*zip*/openj9.zip
00:00:47.174  openj9.zip is a nested zip
00:00:49.949  Found files under openj9.zip:
00:00:49.949  ibm-semeru-certified-debugimage_x64_linux_JDK11U_2022-04-07-01-01.tar.gz
00:00:49.949  ibm-semeru-certified-jdk_x64_linux_JDK11U_2022-04-07-01-01.tar.gz
00:00:49.949  ibm-semeru-certified-jre_x64_linux_JDK11U_2022-04-07-01-01.tar.gz
00:00:49.949  ibm-semeru-certified-testimage_x64_linux_JDK11U_2022-04-07-01-01.tar.gz
00:00:49.949  Uncompressing file: ibm-semeru-certified-jdk_x64_linux_JDK11U_2022-04-07-01-01.tar.gz ...
00:00:53.334  Uncompressing file: ibm-semeru-certified-jre_x64_linux_JDK11U_2022-04-07-01-01.tar.gz ...
00:00:55.315  Uncompressing file: ibm-semeru-certified-testimage_x64_linux_JDK11U_2022-04-07-01-01.tar.gz ...
00:00:55.315  Uncompressing ibm-semeru-certified-debugimage_x64_linux_JDK11U_2022-04-07-01-01.tar.gz over ./j2sdk-image...
```
internal/Grinder/22554/

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4347/

**Review by smlambert — APPROVED** [review]
thanks @llxia (and for testing on the various platforms)

**Review by renfeiw — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
