### PR TITLE
Support custom config json file

### PR DESCRIPTION
**Pull request by llxia**
related: https://github.com/adoptium/aqa-tests/issues/5510

### CODE REVIEW

**Comment by llxia** [comment]
- [Internal run](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/AQA_Test_Pipeline_Release/86/)
- [Internal run](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/AQA_Test_Pipeline_Release/87/)

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by karianna — COMMENTED** [review]
Are we also able to do an external run to test for regression?

**Comment by llxia** [comment]
This does not affect external runs. The feature is only enabled if the special keyword is set.
If the external run wants this feature, we can address it in a separate issue.

**Review by karianna — APPROVED** [review]

**Pull request merged**
