### PR TITLE
Exclude containers tests on all linux platforms

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
This PR needs a bump to resolve the conflicts.

**Comment by smlambert** [comment]
Sorry I was late to review this @sophia-guo, it needs some conflicts resolved.

**Comment by sophia-guo** [comment]
Conflicts resolved. Thanks @smlambert

**Pull request merged**
