### PR TITLE
Add jck22 config files

### LINKED ISSUE #5158: Add config file for tck22
Add config file for tck22 for March release

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #5158

### CODE REVIEW

**Comment by sophia-guo** [comment]
@llxia  https://github.com/adoptium/aqa-tests/pull/4882#issuecomment-1822733151 mentioned grinder testing with jck22 has been done Could you check if those two files are good?

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
FYI, Other vendors use alternate config files, so only Grinders needed are for temurin-compliance server.

**Comment by sophia-guo** [comment]
Eclipse grinder /Grinder/4108

**Comment by smlambert** [comment]
`Cannot write: No space left on device`

**Review by llxia — APPROVED** [review]

**Pull request merged**
