### PR TITLE
Unexcluding HelpFlagsTest as the issue causing failure is resolved

### PR DESCRIPTION
**Pull request by adamfarley**
See this issue for details.

https://bugs.openjdk.java.net/browse/JDK-8273235

Signed-off-by: Adam Farley <adfarley@redhat.com>

### CODE REVIEW

**Comment by adamfarley** [comment]
Running grinder to verify. Link shortly.

**Comment by smlambert** [comment]
Is it possible the the backported fix to jdk11u does not work as expected?

Things to try:
Run the test locally to see the test run and pass (and to see what test material is present, if it contains the fix)
Run a Grinder with KEEP_WORKSPACE=true and log on to machine to see if the test material matches what you expect
Run a Grinder of the entire test target (not jdk_custom, but jdk_tools, the make target that contains this test, and grab the archived test output file and look at the jtr file of the failing test for any further clues)

**Comment by adamfarley** [comment]
Ok, did some digging and I've figured out what's going wrong.

The test fix has gone into the jdk11u, and jdk17u upstream repositories.

We have cloned it into the *master* branches for the adoptium version of those repos.

However, we *test* against the *dev* branches. Only the jdk17 dev branch has the fix. For some reason, the jdk11u dev branch does not have the fix. If adoptium's jdk11u (dev branch) is meant to be a clone of the upstream jdk11u-dev, then something's broken because the upstream jdk11u-dev has the fix already.

I'll ask on Slack to see where adoptium's jdk11u's dev branch is meant to come from.

**Comment by adamfarley** [comment]
Fixed. The [mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-skara-jdk11u/) was broken due to merge conflicts. [George resolved these](https://adoptium.slack.com/archives/C09NLQQAV/p1638530896054300?thread_ts=1638529323.054100&cid=C09NLQQAV), and now the [test passes](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2710/console).

We should be ok to merge this PR now. Will put a request into Slack for people to approve, and I'll tag Shelley so she knows this is now good to go.

**Review by gdams — APPROVED** [review]

**Review by smlambert — APPROVED** [review]
thanks @adamfarley !

**Pull request merged**
