### PR TITLE
Break up compiler/lang/CLSS tests into subgroups

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
`compiler/lang/CLSS` contains, respectively, 314, 319, 403 and 406 sub-tests in jck 8, 11, 16 and 17. Running them in just one playlist target causes that target to take too long to finish, especially on slower platforms. 

This change breaks compiler/lang/CLSS sub-tests into 10 sub-groups and divides them into 10 playlist targets.  

Note, since the number of sub-tests vary across versions, we had to define 4 sets of sub-tests (one for each JDK version).

This change will allow for enhanced granularity in jck compiler tests -- aiding parallel execution of extended builds. This will also help in defining more targeted exclusions. 

Related to : backlog/issues/546

Signed-off-by: Mesbah-Alam <Mesbah_Alam@ca.ibm.com>

FYI @JasonFengJ9 @pshipton @llxia

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test : Grinder/16856

**Comment by llxia** [comment]
I am ok with this PR for now. But I think we need to create a program to automatically scan the folder structure and create the GROUPs. Otherwise, maintaining the GROUPs and supporting ongoing java versions are going to be a nightmare.

**Comment by Mesbah-Alam** [comment]
> I think we need to create a program  

Agreed. And I am in fact using a program already to generate these groups :) 

I will clean it up and we can put it into the repo at some point.

**Comment by llxia** [comment]
Thanks @Mesbah-Alam Do you have an issue tracking it?

**Comment by Mesbah-Alam** [comment]
> Thanks @Mesbah-Alam Do you have an issue tracking it? 

Nope.. I just created the program this week for splitting up lang/CLSS tests over here. I'm yet to create an issue for the program.

**Comment by llxia** [comment]
Thanks. It would be nice to get the program delivered. And we can make it an automatic process to add testing for new java versions. :)

**Comment by smlambert** [comment]
Feel free to put such a program into https://github.com/adoptium/aqa-tests/tree/master/jck/diff as it relates to a similar effort of checking targets match dir structure and all test material is included.

**Comment by Mesbah-Alam** [comment]
>Feel free to put such a program into https://github.com/adoptium/aqa-tests/tree/master/jck/diff as it relates to a similar effort of checking targets match dir structure and all test material is included. 

Sure , will do.

**Review by llxia — APPROVED** [review]

**Review by smlambert — APPROVED** [review]
Happy to bring this in now (and have the automation added later), thanks @Mesbah-Alam !

**Pull request merged**
