### PR TITLE
Increase timeout for OpenJcePlusTests

### PR DESCRIPTION
**Pull request by llxia**
increase timeout to 2hrs

related: https://github.com/eclipse-openj9/openj9/issues/19200

### CODE REVIEW

**Comment by llxia** [comment]
[Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39120/)

**Comment by llxia** [comment]
FYI @jasonkatonica

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by JasonFengJ9 — APPROVED** [review]

**Comment by llxia** [comment]
This PR will be backported into v1.0.1-release via https://github.com/adoptium/aqa-tests/pull/5175

**Pull request merged**
