### PR TITLE
Using JTREG_JDK_TEST_DIR to auto add jdk component test path

### PR DESCRIPTION
**Pull request by sophia-guo**
Remove the requirement for the test full path.

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
[langtools custom testcase will be added. ]( https://github.com/adoptium/aqa-tests/issues/2692).  It's better to remove the requirement to pass in the whole path of test cases, which is confusing for users. Documents will also need to be updated and a FYI to the test  Slack will need to be post.

Grinder:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/137/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/138/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/139/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/140/

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
Thanks @sophia-guo - can you update the help text in the Grinder job (if it needs it...)?

**Comment by smlambert** [comment]
@sophia-guo, https://github.com/adoptium/aqa-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins also needs to be updated to reflect this change.

**Comment by sophia-guo** [comment]
Yes, updated https://github.com/adoptium/aqa-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins

**Pull request merged**
