### PR TITLE
Add ASGCTBaseTest for openj9/ibm

### PR DESCRIPTION
**Pull request by llxia**
depends on https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/33
related: https://github.com/eclipse-openj9/openj9/issues/12276

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/245/

**Comment by llxia** [comment]
FYI @pshipton @JasonFengJ9

**Review by smlambert — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
