### PR TITLE
Having build unzip issues due to nested zip in jenkins submission on windows platforms.

### PR DESCRIPTION
**Pull request by prodroy89**
Having build unzip issues due to nested zip in jenkins submission on windows platforms.

Fixes is given here:- https://github.com/prodroy89/aqa-tests/blob/8af20858dcfa4480057f6075b3c7abd743098db3/get.sh#L313

Signed-off-by: Prodip Roy <prodroy89@in.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
@prodroy89 Please do the following:
- Please squash the commits
- Update the tile to reflect the change
- Please provide a Grinder link

**Comment by prodroy89** [comment]
Hi @llxia , I have given details in below, thanks.
P**lease squash the commits**
Here only 2 commits, 
1. [Merge branch 'adoptium:master' into build_issues_windows](https://github.com/adoptium/aqa-tests/pull/5661/commits/8af20858dcfa4480057f6075b3c7abd743098db3)
2. And code chnages:- [Update get.sh by using '' in zip](https://github.com/adoptium/aqa-tests/pull/5661/commits/894be7c9c9ffa19d4034a315293557c94eb8f554)

**Update the tile to reflect the change**
https://github.com/prodroy89/aqa-tests/blob/8af20858dcfa4480057f6075b3c7abd743098db3/get.sh#L313
image

**Please provide a Grinder link**
**Nested zip issues**
Ref. Link:- https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/24128/

**After changes the code unzipping issues gone**

single link:- https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/24115/
Grinder link:- https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/24394/

**Thanks.**

**Comment by llxia** [comment]
> Please squash the commits

Please squash your 2 commits into one. See https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

> Update the tile to reflect the change

Change PR tile  `Having build unzip issues due to nested zip in jenkins submission on windows platforms.` and commit title  to `Add quote around *.zip`

**Comment by prodroy89** [comment]
Hi @llxia, I had done the changes from GUI in aqa-tests for this PR, that's why it's not allowing me to squash the commits into one commit. I have done the changes freshly from git terminal now and created into one commit.
So I am attaching that new PR link here https://github.com/adoptium/aqa-tests/pull/5665 and closing this PR.

Thanks.

**Pull request closed without merging**
