### PR TITLE
Bug Resolve: Comment triggered PR build (run aqa) failed with KeyErro…

### PR DESCRIPTION
**Pull request by arkumari2000**
Related Issue: #2697

### CODE REVIEW

**Comment by llxia** [comment]
Thanks @arkumari2000 ! Could you please sign the Eclipse Contributor Agreement ([ECA](https://www.eclipse.org/legal/ECA.php)) using the same email as your commit to ensure the eclipsefdn/eca check passes?

**Comment by arkumari2000** [comment]
> Thanks @arkumari2000 ! Could you please sign the Eclipse Contributor Agreement ([ECA](https://www.eclipse.org/legal/ECA.php)) using the same email as your commit to ensure the eclipsefdn/eca check passes?

I have logged in still it's not checked

**Comment by llxia** [comment]
I revalidated and ECA passed. Thanks @arkumari2000

**Review by llxia — APPROVED** [review]
LGTM

**Review by sophia-guo — APPROVED** [review]
LGTM

**Pull request merged**
