### PR TITLE
(v0.9.3-release) Update repo branches for zos

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
- zos MiniMix_5m: Grinder/25679/
```
00:24:35.676  clone_stf:
00:24:38.689       [exec] git clone -q git@github.com:adoptium/STF.git
00:24:38.689       [echo] git rev-parse v0.9.3 
00:24:39.541       [echo] git checkout -q -f acec22e74c358ad21adb13a2e5085fb9d0ddffb8 
00:24:39.939       [move] Moving 1 file to /home/jenkins/workspace/Grinder/aqa-tests/system/STF/.git/info
00:24:40.835       [exec] HEAD is now at 31445cf Replace the word 'master' with 'main' in comments (#130)
00:24:41.784       [exec] Check sha in /home/jenkins/workspace/Grinder/aqa-tests/TKG/../system/STF and store the info in /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/SHA.txt
00:24:41.784       [exec] ================================================
00:24:41.784       [exec] timestamp: 20220713-202639
00:24:41.784       [exec] repo dir: /home/jenkins/workspace/Grinder/aqa-tests/TKG/../system/STF
00:24:41.784       [exec] git repo: 
00:24:41.784       [exec]   Fetch URL: git@github.com:adoptium/STF.git
00:24:41.784       [exec] sha:
00:24:41.784       [exec] 31445cf4c3c2245323897835657276849e33c001
00:24:42.189       [exec] USE_TESTENV_PROPERTIES was set, not writing to testenv.properties
00:24:42.189       [echo] /home/jenkins/workspace/Grinder/aqa-tests/TKG/../system/aqa-systemtest does not exist, clone from GitHub
00:24:42.189  
00:24:42.189  clone_systemtest:
00:25:02.683       [exec] git clone -q git@github.com:adoptium/aqa-systemtest.git
00:25:02.683       [echo] git rev-parse v0.9.3 
00:25:02.683       [echo] git checkout -q -f fec406e1c1645761c9106a5c0e4f4effda7956c7 
00:25:04.276       [move] Moving 1 file to /home/jenkins/workspace/Grinder/aqa-tests/system/aqa-systemtest/.git/info
00:25:07.223       [exec] HEAD is now at ea6d79b Replace master with main (#477)
00:25:08.756       [exec] Check sha in /home/jenkins/workspace/Grinder/aqa-tests/TKG/../system/aqa-systemtest and store the info in /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/SHA.txt
00:25:08.756       [exec] ================================================
00:25:08.756       [exec] timestamp: 20220713-202706
00:25:08.756       [exec] repo dir: /home/jenkins/workspace/Grinder/aqa-tests/TKG/../system/aqa-systemtest
00:25:08.756       [exec] git repo: 
00:25:08.756       [exec]   Fetch URL: git@github.com:adoptium/aqa-systemtest.git
00:25:08.756       [exec] sha:
00:25:08.756       [exec] ea6d79b6d5869fe3cea1b8427f47efd4a5718a31
00:25:08.756       [exec] USE_TESTENV_PROPERTIES was set, not writing to testenv.properties
00:25:08.756       [echo] /home/jenkins/workspace/Grinder/aqa-tests/TKG/../system/openj9-systemtest does not exist, clone from GitHub
00:25:08.756  
00:25:08.756  clone_openj9-systemtest:
00:25:13.207       [exec] git clone -q git@github.com:eclipse-openj9/openj9-systemtest.git
00:25:13.207       [echo] git rev-parse openj9-0.33.0 
00:25:13.207       [echo] git checkout -q -f d2ff3b22514a7db57658a998e617f7687280162a 
00:25:13.207       [move] Moving 1 file to /home/jenkins/workspace/Grinder/aqa-tests/system/openj9-systemtest/.git/info
00:25:14.422       [exec] HEAD is now at d2ff3b2 Merge pull request #145 from pshipton/fixdep
00:25:16.172       [exec] Check sha in /home/jenkins/workspace/Grinder/aqa-tests/TKG/../system/openj9-systemtest and store the info in /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/SHA.txt
00:25:16.172       [exec] ================================================
00:25:16.172       [exec] timestamp: 20220713-202713
00:25:16.172       [exec] repo dir: /home/jenkins/workspace/Grinder/aqa-tests/TKG/../system/openj9-systemtest
00:25:16.172       [exec] git repo: 
00:25:16.172       [exec]   Fetch URL: git@github.com:eclipse-openj9/openj9-systemtest.git
00:25:16.172       [exec] sha:
00:25:16.172       [exec] d2ff3b22514a7db57658a998e617f7687280162a
00:25:16.574       [exec] USE_TESTENV_PROPERTIES was set, not writing to testenv.properties
```

**Comment by llxia** [comment]
Note: Perset to ibm-jdk11-zOS-11.0.16 atm. We will use head stream testing for now until the branch is created.

**Comment by llxia** [comment]
FYI @pshipton

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
