### PR TITLE
Exclude openjdk test java/io/File/GetXSpace.java

### PR DESCRIPTION
**Pull request by lumpfish**
Signed-off-by: Simon Rushton <srushton@redhat.com>

### CODE REVIEW

**Comment by lumpfish** [comment]
Ref: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2461

**Comment by sophia-guo** [comment]
Might update the issue link to https://bugs.openjdk.java.net/browse/JDK-8251466

**Comment by lumpfish** [comment]
I thought if I pointed to https://github.com/adoptium/aqa-tests/pull/2561 that would also include the investigation we had done at AdoptOpenJDK (as well as the reference to https://bugs.openjdk.java.net/browse/JDK-8251466).

**Comment by sophia-guo** [comment]
https://github.com/adoptium/aqa-tests/pull/2561#issuecomment-832053009 yes, that also makes sense. Though would prefer the bug system one so we know at first sight that it's the upstream issue instead of adoptium.

**Comment by smlambert** [comment]
Ultimately the link that is used in the comment of the exclude should be the core issue that needs to be fixed in order to reinclude the test and we should not keep other peripheral issues open or else we experience issue bloat where we live in a world where we have 2 open issues for 1 problem.  2561 served its purpose as a placeholder for excellent additional triage and now can be closed (if not being referenced by an exclude). 

On a related note: we need to go through this repo and 'fix' the bloat before we can turn on the automation to check if its safe to re-include tests based on whether the core issue is resolved or not.  I especially do not like when we hold open a test issue when it has become clear that it is an infra issue.  When we do this, it makes it hard to see overall trends and make program plans and decisions.

**Comment by lumpfish** [comment]
Updated the link to https://bugs.openjdk.java.net/browse/JDK-8251466

**Review by smlambert — APPROVED** [review]

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
