### PR TITLE
Exclude automated jck tests requiring a real UI to be run manually

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Exclude those UI jck tests requiring manual running https://github.com/temurin-compliance/temurin-compliance/issues/29

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Review by sxa — APPROVED** [review]
LGTM

**Review by gdams — APPROVED** [review]

**Comment by sophia-guo** [comment]
The disable feature supports regular expression. Probably use regular expression for some similar disable would be better. https://github.com/adoptium/aqa-tests/blob/master/doc/userGuide.md#exclude-test-against-multiple-criteria

To disable for all implementations we can simply do it by not adding  the  <impl> element.

**Comment by Mesbah-Alam** [comment]
> To disable for all implementations we can simply do it by not adding the element. 

The down side of this would be that we'd miss documentation on why we disabled a target on which impl - something we may not want. 

For example, `jck-runtime-api-javax_naming-spi` is being disabled on hotspot for https://github.com/temurin-compliance/temurin-compliance/issues/29. It was disabled previously on openj9 for infrastructure/issues/5254.  So, when infrastructure/issues/5254 is fixed, we'd want to enable it on just openj9, but still keep it disabled on hotspot. Having separate `disabled` tags helps in this case.

**Comment by andrew-m-leonard** [comment]
> > To disable for all implementations we can simply do it by not adding the element.
> 
> The down side of this would be that we'd miss documentation on why we disabled a target on which impl - something we may not want.
> 
> For example, `jck-runtime-api-javax_naming-spi` is being disabled on hotspot for [temurin-compliance/temurin-compliance#29](https://github.com/temurin-compliance/temurin-compliance/issues/29). It was disabled previously on openj9 for infrastructure/issues/5254. So, when infrastructure/issues/5254 is fixed, we'd want to enable it on just openj9, but still keep it disabled on hotspot. Having separate `disabled` tags helps in this case.

Thanks @Mesbah-Alam yes agree makes good sense.

**Pull request merged**
