### PR TITLE
(v1.0.3-release) Update testenv.properties

### PR DESCRIPTION
**Pull request by llxia**

### CODE REVIEW

**Comment by llxia** [comment]
@smlambert I guessed the following values for Sep release. Please feel free to change them.
```
JDK23_REPO=https://github.com/adoptium/jdk23u.git
JDK23_BRANCH=jdk-23.0.0-ga
```

**Comment by llxia** [comment]
The tests should not be launched until openjceplus branch `semeru-java-23.0.0` is created at https://github.com/ibmruntimes/OpenJCEPlus.git

FYI @AdamBrousseau

**Review by pshipton — APPROVED** [review]

**Comment by AdamBrousseau** [comment]
We created `semeru-java-23` since openjdk versioning does not include the 0.0 so the builds expect the same.

**Comment by llxia** [comment]
re https://github.com/adoptium/aqa-tests/pull/5482#issuecomment-2266100054, update in PR https://github.com/adoptium/aqa-tests/pull/5483

**Comment by smlambert** [comment]
As per our quick Slack chat, there is no jdk23u repo, since there is a change in how this is handled upstream, so I believe it will need to be 

JDK23_REPO=https://github.com/adoptium/jdk.git
JDK23_BRANCH=jdk23 
or 
JDK23_BRANCH=release_jdk23

**Pull request merged**
