### PR TITLE
Update jcstress version

### PR DESCRIPTION
**Pull request by Luigi96**
Update Jcstress version to match dependency update on [TKG - #515](https://github.com/adoptium/TKG/pull/515)

### CODE REVIEW

**Review by karianna — APPROVED** [review]
Approving, a nice refactor later on might be to have the version string passed in as a variable.

**Comment by llxia** [comment]
Enhancement issue is opened at https://github.com/adoptium/TKG/issues/541

**Comment by llxia** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9847/

**Comment by judovana** [comment]
Hello!

I had filled and am working on https://github.com/adoptium/aqa-tests/issues/5261 is it related or is it just coincidence?
I wanted to do this same change, but first I wanted to move jcstress build to non-personal space: https://github.com/adoptium/ci-jenkins-pipelines/pull/1020

Thanx for doing this!

**Review by llxia — APPROVED** [review]

**Comment by llxia** [comment]
https://github.com/adoptium/TKG/issues/541 is an enhancement for easy maintenance in the future. jar version should not be in the fname. In this way, we do not need to update references for any jctress.jar upgrades.

**Comment by judovana** [comment]
> Approving, a nice refactor later on might be to have the version string passed in as a variable.

Actually there is a missing step.

IIRC, quite a lot fo new targets were added beten 2022 and 2024, @Luigi96  Had you tried that what targets are *not* run ?

**Comment by llxia** [comment]
> I wanted to follow the jtreg principle, where the getDepndencies will resolve best jcstress-xyz.jar for given jdk/variant, and provide that via variable and/or will provie it simply as jctress.jar.

For jtreg, we need to run different versions of jtreg.jar based on the JDK version, and special unzipping is needed. Are these needed for jcstress jar? From what I can see, we just reference the jcstress.jar directly.

**Comment by judovana** [comment]
Ifaik not yet. But  soon the bytecode level will be hit, and for jdk8 will be needed different jcstress then for newer.

**Comment by judovana** [comment]
> > Approving, a nice refactor later on might be to have the version string passed in as a variable.
> 
> Actually there is a missing step.
> 
> IIRC, quite a lot fo new targets were added beten 2022 and 2024, @Luigi96 Had you tried that what targets are _not_ run ?

```
--- /home/jvanek/git/ci-jenkins-pipelines/tools/code-tools/jcstress/2022
+++ /home/jvanek/git/ci-jenkins-pipelines/tools/code-tools/jcstress/2024
@@ -1,6 +1,6 @@
 Java Concurrency Stress Tests
 ---------------------------------------------------------------------------------
-Rev: d118775943666d46, built by jvanek with 11.0.22 at 2024-04-25T21:58:48Z
+Rev: c565311051494f4b, built by jvanek with 11.0.22 at 2024-04-25T21:53:16Z
 
 Burning up to figure out the exact CPU count....... done!
 
@@ -113,6 +113,24 @@
 org.openjdk.jcstress.samples.problems.racecondition.RaceCondition_02_CheckThenReact.Atomic
 org.openjdk.jcstress.samples.problems.racecondition.RaceCondition_02_CheckThenReact.Racy
 org.openjdk.jcstress.samples.problems.racecondition.RaceCondition_02_CheckThenReact.Sync
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.BooleanTest
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.ByteTest
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.CharTest
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.DoubleTest
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.FloatTest
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.IntTest
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.LongTest
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.ShortTest
+org.openjdk.jcstress.tests.accessAtomic.arrays.sync.StringTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.BooleanTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.ByteTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.CharTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.DoubleTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.FloatTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.IntTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.LongTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.ShortTest
+org.openjdk.jcstress.tests.accessAtomic.fields.conflict.sync.StringTest
 org.openjdk.jcstress.tests.accessAtomic.fields.conflict.volatiles.BooleanTest
 org.openjdk.jcstress.tests.accessAtomic.fields.conflict.volatiles.ByteTest
 org.openjdk.jcstress.tests.accessAtomic.fields.conflict.volatiles.CharTest
@@ -122,6 +140,15 @@
 org.openjdk.jcstress.tests.accessAtomic.fields.conflict.volatiles.LongTest
 org.openjdk.jcstress.tests.accessAtomic.fields.conflict.volatiles.ShortTest
 org.openjdk.jcstress.tests.accessAtomic.fields.conflict.volatiles.StringTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.BooleanTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.ByteTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.CharTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.DoubleTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.FloatTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.IntTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.LongTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.ShortTest
+org.openjdk.jcstress.tests.accessAtomic.fields.sync.StringTest
 org.openjdk.jcstress.tests.accessAtomic.fields.volatiles.BooleanTest
 org.openjdk.jcstress.tests.accessAtomic.fields.volatiles.ByteTest
 org.openjdk.jcstress.tests.accessAtomic.fields.volatiles.CharTest
@@ -293,6 +320,69 @@
 org.openjdk.jcstress.tests.accessAtomic.varHandles.fields.volatiles.LongTest
 org.openjdk.jcstress.tests.accessAtomic.varHandles.fields.volatiles.ShortTest
 org.openjdk.jcstress.tests.accessAtomic.varHandles.fields.volatiles.StringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.BooleanBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.BooleanByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.BooleanCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.BooleanFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.BooleanIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.BooleanShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.BooleanStringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ByteBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ByteByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ByteCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ByteFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ByteIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ByteShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ByteStringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.CharBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.CharByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.CharCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.CharFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.CharIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.CharShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.CharStringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.DoubleBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.DoubleByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.DoubleCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.DoubleFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.DoubleIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.DoubleShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.DoubleStringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.FloatBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.FloatByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.FloatCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.FloatFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.FloatIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.FloatShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.FloatStringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.IntBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.IntByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.IntCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.IntFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.IntIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.IntShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.IntStringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.LongBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.LongByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.LongCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.LongFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.LongIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.LongShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.LongStringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ShortBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ShortByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ShortCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ShortFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ShortIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ShortShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.ShortStringTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.StringBooleanTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.StringByteTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.StringCharTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.StringFloatTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.StringIntTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.StringShortTest
+org.openjdk.jcstress.tests.acqrel.fields.sync.StringStringTest
 org.openjdk.jcstress.tests.acqrel.fields.volatiles.BooleanBooleanTest
 org.openjdk.jcstress.tests.acqrel.fields.volatiles.BooleanByteTest
 org.openjdk.jcstress.tests.acqrel.fields.volatiles.BooleanCharTest
@@ -1936,6 +2026,24 @@
 org.openjdk.jcstress.tests.causality.Test7
 org.openjdk.jcstress.tests.causality.Test8
 org.openjdk.jcstress.tests.causality.Test9
+org.openjdk.jcstress.tests.coherence.arrays.sync.BooleanTest
+org.openjdk.jcstress.tests.coherence.arrays.sync.ByteTest
+org.openjdk.jcstress.tests.coherence.arrays.sync.CharTest
+org.openjdk.jcstress.tests.coherence.arrays.sync.DoubleTest
+org.openjdk.jcstress.tests.coherence.arrays.sync.FloatTest
+org.openjdk.jcstress.tests.coherence.arrays.sync.IntTest
+org.openjdk.jcstress.tests.coherence.arrays.sync.LongTest
+org.openjdk.jcstress.tests.coherence.arrays.sync.ShortTest
+org.openjdk.jcstress.tests.coherence.arrays.sync.StringTest
+org.openjdk.jcstress.tests.coherence.fields.sync.BooleanTest
+org.openjdk.jcstress.tests.coherence.fields.sync.ByteTest
+org.openjdk.jcstress.tests.coherence.fields.sync.CharTest
+org.openjdk.jcstress.tests.coherence.fields.sync.DoubleTest
+org.openjdk.jcstress.tests.coherence.fields.sync.FloatTest
+org.openjdk.jcstress.tests.coherence.fields.sync.IntTest
+org.openjdk.jcstress.tests.coherence.fields.sync.LongTest
+org.openjdk.jcstress.tests.coherence.fields.sync.ShortTest
+org.openjdk.jcstress.tests.coherence.fields.sync.StringTest
 org.openjdk.jcstress.tests.coherence.fields.volatiles.BooleanTest
 org.openjdk.jcstress.tests.coherence.fields.volatiles.ByteTest
 org.openjdk.jcstress.tests.coherence.fields.volatiles.CharTest
@@ -2258,6 +2366,33 @@
 org.openjdk.jcstress.tests.countdownlatch.waits.BoundedSingleTest
 org.openjdk.jcstress.tests.countdownlatch.waits.UnboundedDoubleTest
 org.openjdk.jcstress.tests.countdownlatch.waits.UnboundedSingleTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.BooleanTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.ByteTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.CharTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.DoubleTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.FloatTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.IntTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.LongTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.ShortTest
+org.openjdk.jcstress.tests.defaultValues.arrays.large.sync.StringTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.BooleanTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.ByteTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.CharTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.DoubleTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.FloatTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.IntTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.LongTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.ShortTest
+org.openjdk.jcstress.tests.defaultValues.arrays.small.sync.StringTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.BooleanTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.ByteTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.CharTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.DoubleTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.FloatTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.IntTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.LongTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.ShortTest
+org.openjdk.jcstress.tests.defaultValues.fields.sync.StringTest
 org.openjdk.jcstress.tests.defaultValues.fields.volatiles.BooleanTest
 org.openjdk.jcstress.tests.defaultValues.fields.volatiles.ByteTest
 org.openjdk.jcstress.tests.defaultValues.fields.volatiles.CharTest
@@ -2377,6 +2512,33 @@
 org.openjdk.jcstress.tests.fences.varHandles.StoreStoreFenceTest2.StoreStoreFenceString
 org.openjdk.jcstress.tests.future.FutureTaskSetTest
 org.openjdk.jcstress.tests.future.ThreadNames
+org.openjdk.jcstress.tests.init.arrays.large.sync.BooleanTest
+org.openjdk.jcstress.tests.init.arrays.large.sync.ByteTest
+org.openjdk.jcstress.tests.init.arrays.large.sync.CharTest
+org.openjdk.jcstress.tests.init.arrays.large.sync.DoubleTest
+org.openjdk.jcstress.tests.init.arrays.large.sync.FloatTest
+org.openjdk.jcstress.tests.init.arrays.large.sync.IntTest
+org.openjdk.jcstress.tests.init.arrays.large.sync.LongTest
+org.openjdk.jcstress.tests.init.arrays.large.sync.ShortTest
+org.openjdk.jcstress.tests.init.arrays.large.sync.StringTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.BooleanTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.ByteTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.CharTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.DoubleTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.FloatTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.IntTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.LongTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.ShortTest
+org.openjdk.jcstress.tests.init.arrays.small.sync.StringTest
+org.openjdk.jcstress.tests.init.fields.sync.BooleanTest
+org.openjdk.jcstress.tests.init.fields.sync.ByteTest
+org.openjdk.jcstress.tests.init.fields.sync.CharTest
+org.openjdk.jcstress.tests.init.fields.sync.DoubleTest
+org.openjdk.jcstress.tests.init.fields.sync.FloatTest
+org.openjdk.jcstress.tests.init.fields.sync.IntTest
+org.openjdk.jcstress.tests.init.fields.sync.LongTest
+org.openjdk.jcstress.tests.init.fields.sync.ShortTest
+org.openjdk.jcstress.tests.init.fields.sync.StringTest
 org.openjdk.jcstress.tests.init.fields.volatiles.BooleanTest
 org.openjdk.jcstress.tests.init.fields.volatiles.ByteTest
 org.openjdk.jcstress.tests.init.fields.volatiles.CharTest
@@ -2394,6 +2556,33 @@
 org.openjdk.jcstress.tests.init.primitives.fenced.IntFencedTest
 org.openjdk.jcstress.tests.init.primitives.fenced.LongFencedTest
 org.openjdk.jcstress.tests.init.primitives.fenced.ShortFencedTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.BooleanTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.ByteTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.CharTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.DoubleTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.FloatTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.IntTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.LongTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.ShortTest
+org.openjdk.jcstress.tests.initClass.arrays.large.sync.StringTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.BooleanTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.ByteTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.CharTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.DoubleTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.FloatTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.IntTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.LongTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.ShortTest
+org.openjdk.jcstress.tests.initClass.arrays.small.sync.StringTest
+org.openjdk.jcstress.tests.initClass.fields.sync.BooleanTest
+org.openjdk.jcstress.tests.initClass.fields.sync.ByteTest
+org.openjdk.jcstress.tests.initClass.fields.sync.CharTest
+org.openjdk.jcstress.tests.initClass.fields.sync.DoubleTest
+org.openjdk.jcstress.tests.initClass.fields.sync.FloatTest
+org.openjdk.jcstress.tests.initClass.fields.sync.IntTest
+org.openjdk.jcstress.tests.initClass.fields.sync.LongTest
+org.openjdk.jcstress.tests.initClass.fields.sync.ShortTest
+org.openjdk.jcstress.tests.initClass.fields.sync.StringTest
 org.openjdk.jcstress.tests.initClass.fields.volatiles.BooleanTest
 org.openjdk.jcstress.tests.initClass.fields.volatiles.ByteTest
 org.openjdk.jcstress.tests.initClass.fields.volatiles.CharTest
@@ -2403,6 +2592,24 @@
 org.openjdk.jcstress.tests.initClass.fields.volatiles.LongTest
 org.openjdk.jcstress.tests.initClass.fields.volatiles.ShortTest
 org.openjdk.jcstress.tests.initClass.fields.volatiles.StringTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.BooleanTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.ByteTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.CharTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.DoubleTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.FloatTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.IntTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.LongTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.ShortTest
+org.openjdk.jcstress.tests.initLen.arrays.large.sync.StringTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.BooleanTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.ByteTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.CharTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.DoubleTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.FloatTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.IntTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.LongTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.ShortTest
+org.openjdk.jcstress.tests.initLen.arrays.small.sync.StringTest
 org.openjdk.jcstress.tests.interrupt.CurrentThreadIsInterruptedBreakTest
 org.openjdk.jcstress.tests.interrupt.CurrentThreadIsInterruptedMethodTest
 org.openjdk.jcstress.tests.interrupt.CurrentThreadIsInterruptedTest
@@ -4324,6 +4419,24 @@
 org.openjdk.jcstress.tests.tearing.ArrayInterleaveTest
 org.openjdk.jcstress.tests.tearing.UnsafeArrayInterleaveTest
 org.openjdk.jcstress.tests.tearing.UnsafeIntTearingTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.BooleanTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.ByteTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.CharTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.DoubleTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.FloatTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.IntTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.LongTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.ShortTest
+org.openjdk.jcstress.tests.tearing.arrays.large.sync.StringTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.BooleanTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.ByteTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.CharTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.DoubleTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.FloatTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.IntTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.LongTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.ShortTest
+org.openjdk.jcstress.tests.tearing.arrays.small.sync.StringTest
 org.openjdk.jcstress.tests.tearing.buffers.ByteBufferInterleaveTest
 org.openjdk.jcstress.tests.tearing.buffers.CharBufferInterleaveTest
 org.openjdk.jcstress.tests.tearing.buffers.DirectByteBufferInterleaveTest
@@ -4332,6 +4445,15 @@
 org.openjdk.jcstress.tests.tearing.buffers.IntBufferInterleaveTest
 org.openjdk.jcstress.tests.tearing.buffers.LongBufferInterleaveTest
 org.openjdk.jcstress.tests.tearing.buffers.ShortBufferInterleaveTest
+org.openjdk.jcstress.tests.tearing.fields.sync.BooleanTest
+org.openjdk.jcstress.tests.tearing.fields.sync.ByteTest
+org.openjdk.jcstress.tests.tearing.fields.sync.CharTest
+org.openjdk.jcstress.tests.tearing.fields.sync.DoubleTest
+org.openjdk.jcstress.tests.tearing.fields.sync.FloatTest
+org.openjdk.jcstress.tests.tearing.fields.sync.IntTest
+org.openjdk.jcstress.tests.tearing.fields.sync.LongTest
+org.openjdk.jcstress.tests.tearing.fields.sync.ShortTest
+org.openjdk.jcstress.tests.tearing.fields.sync.StringTest
 org.openjdk.jcstress.tests.tearing.fields.volatiles.BooleanTest
 org.openjdk.jcstress.tests.tearing.fields.volatiles.ByteTest
 org.openjdk.jcstress.tests.tearing.fields.volatiles.CharTest
```

**Comment by judovana** [comment]
Should I draft PR, or will somebody else doing it?

**Pull request merged**
