### PR TITLE
Re-enable jdk 11 tests 

### PR DESCRIPTION
**Pull request by tommytwm**
Re-enabled tests excluded by issue 248. Partial fix of: #3214 

This patch re-enables JDK 11 test excluded by issue 248.

Refer to [Grinder Test Results](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3147/testReport/)
image
image

Signed-off-by: Tommy Tho <tommythowm@gmail.com>

### CODE REVIEW

**Comment by tommytwm** [comment]
ok wait hold on theres a problem with my build
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3155/

**Comment by smlambert** [comment]
run aqa -help

**Comment by smlambert** [comment]
run aqa --help

**Comment by smlambert** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target jdk_lang --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux

**Comment by tommytwm** [comment]
run aqa --help

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @tommytwm !

**Pull request merged**
