### PR TITLE
Update document regarding new disable format

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Review by llxia — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
run aqa --help

**Comment by smlambert** [comment]
run aqa --sdk_resource nightly --build_list openjdk --target jdk_math --jdk_version 8 --jdk_impl hotspot --platform x86-64_linux

**Comment by renfeiw** [comment]
> @smlambert Build(s) failed.
> Workflow Run ID: [1078726512](https://github.com/adoptium/aqa-tests/actions/runs/1078726512)

This PR is document change only, the failure is caused by my old repo name. I will need to delete my everything and re-fork after my PRs are merged.

**Review by smlambert — APPROVED** [review]

**Pull request merged**
