### PR TITLE
(v0.9.3-release) Update repo branches in testenv.properties

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Openj9 JDK18 jdk_math: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5178/

**Comment by llxia** [comment]
Openj9 JDK11 MiniMix_5m: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5179/

**Comment by llxia** [comment]
FYI @pshipton

**Review by smlambert — COMMENTED** [review]
thanks!

**Pull request merged**
