### PR TITLE
Update jck material versions

### PR DESCRIPTION
**Pull request by sxa**
New versions of the repositories have been created for 8 and 11. This adjusts the test harness to compensate.
Draft while it undergoes testing and iterative updates.

### CODE REVIEW

**Comment by sxa** [comment]
> Just a note : IBM internal tck repositories for 8 and 11 have to be updated with 8d and 11a materials before this PR can be delivered.

Is the expection that you'll be able to do that soon? Obviously we'll want this for the next release in July.

**Comment by Mesbah-Alam** [comment]
@sxa , which version of tck are you trying to run? Are you seeing any particular errors?

**Comment by smlambert** [comment]
Please discuss details in a private DM.

**Comment by Mesbah-Alam** [comment]
Just an FYI: https://github.com/adoptium/aqa-tests/pull/4512 is working normally at hyc extended builds (e.g. Test_openjdk8_j9_extended.jck_x86-64_linux/136). Agents are starting as usual, dependent tests passing, agents then being stopped normally too. 

I will pull in the latest version for 8 and 11 and test https://github.com/adoptium/aqa-tests/pull/4601 at my end.

**Comment by Mesbah-Alam** [comment]
FYI @sxa , A fix for the issue you countered with jdwp will be delivered via https://github.com/adoptium/aqa-tests/pull/4607.

**Comment by sxa** [comment]
LGTM. On the basis that this PR works as expected I'm going to take this out of draft. Your other PR seems good too.

**Review by karianna — APPROVED** [review]

**Comment by smlambert** [comment]
I will tag AQAvit repos prior to merging this PR, in case others who may be using our scripts have a recent tag to fall back to while they update to the latest 8d/11a materials.

**Comment by sxa** [comment]
> I will tag AQAvit repos prior to merging this PR, in case others who may be using our scripts have a recent tag to fall back to while they update to the latest 8d/11a materials.

@Mesbah-Alam is this ok for your internal requirements? I'd like to get this merged today if feasible in order to allow us to be able to run the tests over the weekend.

**Comment by Mesbah-Alam** [comment]
Re https://github.com/adoptium/aqa-tests/pull/4601#issuecomment-1584518012 : Unfortunately, I am occupied with some other work today. 

If this is merged now, it will break the internal tck builds. So, please co-ordinate with @llxia and see if the internal 8 and 11 repo's could be updated today by someone else. Other option is, as Shelley [suggested](https://github.com/adoptium/aqa-tests/pull/4601#issuecomment-1584509436), use a tag. Otherwise, Please wait till next week and I will update the internal 8 and 11 repos.

**Comment by smlambert** [comment]
We will plan to merge it next week, and I will post an announcement to the Slack channel to alert any others who may be affected by it.

**Comment by Mesbah-Alam** [comment]
This PR looks good. Tested with `8d` & `11a` latest materials: 

- For 8d : Grinder_JCK/1441 (green). 
- For 11a: Grinder_JCK/1442 (green). 

Please note, the 'main' branch of the internal repos are yet to be updated with 8d and 11a. I ran my test off of my branch. I will update the 'main' branch once this PR is merged after the tagging is still done (Re: https://github.com/adoptium/aqa-tests/pull/4601#issuecomment-1584509436).

**Comment by sxa** [comment]
@smlambert Did you get a suitable tag in place? If so it sounds like we can get this in and run a test with all the fixes we have at once against the latest material :-)

**Comment by smlambert** [comment]
People can use aqa-tests tag: `june-2023-pin-jck8c` if they can not update to 8d and 11a right away, though the recommendation will be to update their materials asap.

**Review by smlambert — APPROVED** [review]

**Comment by Mesbah-Alam** [comment]
Updated Internal tck repos : 8 - 8d, 11->11a.

**Pull request merged**
