### PR TITLE
excluded testcases for vthread on aix java 19

### LINKED ISSUE #3983: jdk_nio_0 and java_nio_1 BlockingChannelOps times out on ppc64 aix for Java 19
[TRSS Test Output](https://trss.adoptium.net/output/test?id=632bf1c193ac60470bc85542) and 
[TRSS Test Output](https://trss.adoptium.net/output/test?id=632bf1c193ac60470bc85543)

### PR DESCRIPTION
**Pull request by lumuchris256**
excluded testcases for vthread on aix java 19

fixes #3983 
signed off; lumuchris

### CODE REVIEW

**Comment by lumuchris256** [comment]
@smlambert

**Comment by smlambert** [comment]
I had assigned https://github.com/adoptium/aqa-tests/issues/3983 to someone else.

**Comment by lumuchris256** [comment]
> I had assigned #3983 to someone else.

@smlambert since this was linked to similar work with an issue related  , i was in process to push its PR when you assigned
so this is the PR

**Comment by smlambert** [comment]
This PR is not needed, as #3983 is fixed via https://github.com/adoptium/aqa-tests/pull/4043, so closing this PR

**Pull request closed without merging**
