### PR TITLE
Enable VThreadStackRefTest.java

### PR DESCRIPTION
**Pull request by fengxue-IS**
Fixes: https://github.com/eclipse-openj9/openj9/issues/17712

Issue fixed via https://github.com/eclipse-openj9/openj9/pull/18379 & https://github.com/eclipse-openj9/openj9/pull/18378

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
Personal grinder verified test pass: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/35784/

**Review by JasonFengJ9 — APPROVED** [review]
LGTM

**Review by llxia — APPROVED** [review]

**Comment by llxia** [comment]
Waiting for the ECA check to pass.

**Comment by llxia** [comment]
According to https://api.eclipse.org/git/eca/status/gh/adoptium/aqa-tests/4847, ECA passed

image

However, the ECA check in the PR still shows `Pending — Eclipse Foundation Contributor Agreement validation is in progress.`.
 I tried to click on `Revalidate` in the eclipse link, but it did not help.

@smlambert do you know what we should do in this case?

**Comment by smlambert** [comment]
We can either raise a helpdesk issue to resolve (probably the best approach, as then EF can see how/why its hung), or try with a new push to this PR or a new PR.

**Comment by llxia** [comment]
@fengxue-IS do you mind trying with a new push to this PR or a new PR? If it does not work, I will raise a helpdesk issue with Eclipse.

**Comment by fengxue-IS** [comment]
@llxia ECA passed, not sure what went wrong previously 😢

**Pull request merged**
