### PR TITLE
Regenerated jcstress playlist for jcstress and pushed its generator

### PR DESCRIPTION
**Pull request by judovana**
The initial set of tests is obtained by `jcstress.jar -l` The generator is:
  mixing targets with  to few targets
  ensuring no test is run twice
  targets are as short as possible where still fully descriptive
  regexes for -t runtime are fully quified

Similarly as there is exclude list to not shorten groups where missleading preffix would remain, can be added include list, which would connect remaining tests with 1 or two targets to artificial group. But it was jsut 23 tests in time of this commit

### CODE REVIEW

**Comment by judovana** [comment]
Will resolve https://github.com/adoptium/aqa-tests/issues/5278 if (ever) agreed on

**Comment by judovana** [comment]
It seems the jcstress issue got staled a bit. Opening from draft for review.

**Review by smlambert — CHANGES_REQUESTED** [review]
Please add a .md file added into system/jcstress directory to describe how to run the generator, and capture the general gist of the tests created in the playlist.  

Also please spellcheck all of your comments for 'typing too fast' mistakes like memebrs, namesapces, etc.

**Comment by judovana** [comment]
Hello!

In past week, I was playing a lot with the generator, and before we proceed with play-list generation, and I think there is quite a few factors to consider.

* experinece: in my runs in RH, the stadnart runtime of all between jcstress2020 and 2024 got aprox 100x times longer
  * possible solutions is to not run some targets and/or limit the number of cores
  * important note is, that limiting to 1 core is no go, because it eliminates to much tests.
* The runtime is quite rising with the number of allowed cores, so keeping on default ( using all machine cores ) leads to incredibly unpredictable results. 
  * So I have added the optional `-c` switch to have predictable number of cores generated. Eg `-c 2` will mean that all machines will use two cores.
  * See eg this results I generated .
```
 1 core : Total time: 9 minutes [0d+00:09:35]
 2 cores: Total time: 16458 minutes [11d+10:18:34]
 3 cores: Total time: 33695 minutes [23d+09:35:21]
 4 cores: Total time: 149339 minutes [103d+16:59:21]
 8 cores: Total time: 149339 minutes [103d+16:59:20] 
```
not sure why 4 and 8 are same, My machine have 4cores with hyper threading, so  8 virtual. Maybe the jcstress is using only real ones or  it estimated 103days as to much . Anyway **Imagine it on 100core Arm**...

* the single jcstress test do not have constant length.
* When I did some basic grouping,  I realised, that some group with eg 100 tests runs much longer then some group with 2000 tests.
  * it is deterministic
  * It seems that generated tests are those fast ones
  * It is well visible on following figure:
```
Results gathered: 14; 100% time of longest group, n% time of ideal group
small.groups.1 with 853tests took 117791s [1d+08:43:11] (100%)(+66%)
org.openjdk.jcstress.tests.memeffects.basic-001 with 816tests took 117504s [1d+08:38:24] (99%)(+66%)
org.openjdk.jcstress.tests.atomics-001 with 694tests took 98783s [1d+03:26:23] (83%)(+40%)
org.openjdk.jcstress.tests.acqrel.varHandles.byteBuffer-001 with 672tests took 96767s [1d+02:52:47] (82%)(+37%)
org.openjdk.jcstress.tests.locks-001 with 646tests took 93023s [1d+01:50:23] (78%)(+31%)
org.openjdk.jcstress.tests.acqrel-001 with 588tests took 84671s [0d+23:31:11] (71%)(+20%)
small.groups.2 with 597tests took 83807s [0d+23:16:47] (71%)(+18%)
org.openjdk.jcstress.tests.acqrel.varHandles-001 with 504tests took 72575s [0d+20:09:35] (61%)(+2%)
org.openjdk.jcstress.tests.atomicity.varHandles-001 with 714tests took 68543s [0d+19:02:23] (58%)(-3%)
small.groups.3 with 528tests took 65915s [0d+18:18:35] (55%)(-7%)
org.openjdk.jcstress.tests.atomicity-001 with 612tests took 64800s [0d+18:00:00] (55%)(-9%)
org.openjdk.jcstress.tests.seqcst.volatiles with 2131tests took 8928s [0d+02:28:48] (7%)(-88%)
org.openjdk.jcstress.tests.seqcst.sync with 2131tests took 8927s [0d+02:28:47] (7%)(-88%)
small.groups.4 with 57tests took 5471s [0d+01:31:11] (4%)(-93%)
Total time: 16458 minutes [11d+10:18:25]
Ideal avg time: 1175 minutes [0d+19:35:36] (100%)
Max seen  time: 1963 minutes [1d+08:43:11] (166%)
Min seen  time: 91 minutes [0d+01:31:11] (7%)
Avg differecne from longest: 59%
Avg differecne from ideal: 60%
```
You can see that:
```
org.openjdk.jcstress.tests.seqcst.volatiles with 2131tests took 8928s [0d+02:28:48] (7%)(-88%)
org.openjdk.jcstress.tests.seqcst.sync with 2131tests took 8927s [0d+02:28:47] (7%)(-88%)
```
Are much shorter then others, despite having much more tests. My Generator can split it, but how, depends on how mch targets we wish to have. This example is with LIMIT=500 and not splitting the huge groups.
Also it is visible that spiting of thsoe groups have sense only since some time per group (in this case, 2 cores, it would be 2.5 hours)

All those times are based on estimations `jcstress` itself is doing. I have verified that those estimations quite precisse enough. Worst I had seen was +-25% of real run compared to estimate one, but usually less then 10%.

So the questions:
 * how much cores to use? 
 * How much can the basic split time be?
   *  longstory short  estiamtion (with two cores) are as follows (the times of groups are in last brackets):
 ```
 * split_exl Limit 10 - 603 groups, from those  7 "small groups" (0.5hours each. %like longest/ideal %17%/? (6m-2.5h)
 * split_all Limit 10 - 603 groups, from those  7 "small groups" (0.5hours each. %like longest/ideal %68%/81? (26m-38mm)
 * split_exl Limit 50 - 128 groups, from those  6 "small groups" (~2.5hhours each. %like longest/ideal %60/85% (45m-3.5h)
 * split_allLimit 50 - 128 groups, from those  6 "small groups" (~2.5hhours each. %like longest/ideal %60/85% (45m-3.5h)
 * Limit 100 - 60 groups, from those  7 "small groups" (~4.5hours each. %like longest/ideal %63/79% (2.5h-7h)
```

Although I will provide full statistics later, It seems that having  more then 150 of groups is impractical and having longer then 3hours per is impractical to. Thusl number of tests i group (limit) should be around 50. As in this are is the glorifed 2.5 hours for "unsplittable" groups, theirs split depends on selected cores and limits

**Comment by judovana** [comment]
```
jcstress-20240222. -c 1 -l | wc -l
4489
jcstress-20240222.jar -c 2 -l | wc -l
4489
jcstress-20240222.jar -c 4 -l | wc -l
4489
```
Bad luck, -l do not honour -c

**Comment by judovana** [comment]
Full statistics of cores x runs with split possibilities:
https://jvanek.fedorapeople.org/jcstress/details.html
The smallest (10)  groups with large namesapces split are still running, and will run till the end of today, but I doubt that this group wil be used. Will udpate it once finshed.

**Comment by judovana** [comment]
> Hello!
> 
> In past week, I was playing a lot with the generator, and before we proceed with play-list generation, I think there is quite a few factors to consider.
> 
>     * experinece: in my runs in RH, the stadnart runtime of all between jcstress2020 and 2024 got aprox 100x times longer
>       
>       * possible solutions is to not run some targets and/or limit the number of cores

After short discussion in https://bugs.openjdk.org/browse/CODETOOLS-7903749, dropping out some tests is no go.

And I forget about `-tb`.  That narrows the whole case. I still need to investiagte impac of `-c`  in case `-tb` is used, but in all cases, what is the maximal  time jcstress are supposed to consume?
Split to 60 tasks where each will run one hour? 30 tasks? 30 minutes? Less, More?

**Comment by judovana** [comment]
https://bugs.openjdk.org/browse/CODETOOLS-7903749 also suggestys to keep `-c` missing, thus on max (thus all available cores). I may have two issues:
 - if some of the machines will have less then 4 cores, then some generated target may end with `FATAL: No matching tests. `
   -  this may be workaroudned by  generating only targets for -c 2 or 3 but that will skip other interesting tests.
   -  waits for https://bugs.openjdk.org/browse/CODETOOLS-7903748

**Comment by judovana** [comment]
> Full statistics of cores x runs with split possibilities: https://jvanek.fedorapeople.org/jcstress/details.html The smallest (10) groups with large namesapces split are still running, and will run till the end of today, but I doubt that this group wil be used. Will udpate it once finshed.

Updated https://jvanek.fedorapeople.org/jcstress/details.html  but I guess with `-tb` it no longer metters. For curious, it is very interesting

**Comment by judovana** [comment]
> I had improved the generator so it is using `-tb` now.
> 
> I think best solution is current default or close - Generate list for all cores (so not waiting for https://bugs.openjdk.org/browse/CODETOOLS-7903748) , use all cores on any setup, set `-tb` to agreed time. And set number of parallel groups. The generated playlist now have 138 groups. 30minutes each, is some 3days of HW time (20s per test)
> 
> So the question simplified - Howmuch HW time do you wish to use for jcstress?
> 
> I'm now running the `OUTPUT=do;LIMIT=500,` with (now) default time of 30m per group and all splitting enabled (so some 20 fairly sized groups). That is some 6 hours to finish. and aprox 1-2s per test. Will see, how the enforced time (30m) will fit with final runs.


hm:(  https://bugs.openjdk.org/browse/CODETOOLS-7903748

**Comment by judovana** [comment]
> I had improved the generator so it is using `-tb` now.
> 
> I think best solution is current default or close - Generate list for all cores (so not waiting for https://bugs.openjdk.org/browse/CODETOOLS-7903748) , use all cores on any setup, set `-tb` to agreed time. And set number of parallel groups. The generated playlist now have 138 groups. 30minutes each, is some 3days of HW time (20s per test)
> 
> So the question simplified - Howmuch HW time do you wish to use for jcstress?
> 
> I'm now running the `OUTPUT=do;LIMIT=500,` with (now) default time of 30m per group and all splitting enabled (so some 20 fairly sized groups). That is some 6 hours to finish. and aprox 1-2s per test. Will see, how the enforced time (30m) will fit with final runs.

@smlambert "So the question simplified - Howmuch HW time do you wish to use for jcstress?" is really up to you. If it would be mine infra, I would give whole jcstress 12-24 houirs, split to some 12-24 chunks one hour each....

**Comment by smlambert** [comment]
> So the question simplified - How much HW time do you wish to use for jcstress?" is really up to you. If it would be mine infra, I would give whole jcstress 12-24 hours, split to some 12-24 chunks one hour each....

The answer to this depends upon how often these tests find defects.  Anyone using AQAvit could choose to run them if they want, though I imagine this set being most useful for developers making changes to GC or some such.  The important aspect of these tests are that they are available as an optional set of tests to run.  

Listing options to consider to retain flexibility / choice for people using AQAvit:

1. Parameterize the execution time (default of 30m per group) 
2. Disable long running test targets, and leaving them to be run manually via `make _disabled.jcstressxxxx` where jctressxxxx are targets that are very long.  
3. Consider running these tests in a separate test job, on a less regular basis, or based on certain types of OpenJDK code changes.

**Comment by judovana** [comment]
> > So the question simplified - How much HW time do you wish to use for jcstress?" is really up to you. If it would be mine infra, I would give whole jcstress 12-24 hours, split to some 12-24 chunks one hour each....
> 
> The answer to this depends upon how often these tests find defects. Anyone using AQAvit could choose to run them if they want, though I imagine this set being most useful for developers making changes to GC or some such. The important aspect of these tests are that they are available as an optional set of tests to run.
> 
> Listing options to consider to retain flexibility / choice for people using AQAvit:
> 
>     1. Parameterize the execution time (default of 30m per group)

(even) if the execution time is parametrized - maybe even more important if it is - then how much groups to split it on?

In theory, we may get rid of split at all, and simply relay on `-tb` . Simply run all the jcstress in one hugebulk.
1hour after commit, 3hours on daily build and 24 hours  on release build. But that is slightly going agaisnt the principle of waht is longer then 20minutes, should be split.

But splitting it, is dangerous. Because `-tb` is not reliable. If one huge testsuite of jcstress, who shoudl run for 24hours, would run for 36 hours,  or instead of 3 hours, 5 hours.. then it is moreover ok. But if it is split to 10 groups, each for hour,  and half of them will go wild, then it will cause much more mayhem.


> 
>     2. Disable long running test targets, and leaving them to be run manually via `make _disabled.jcstressxxxx` where jctressxxxx are targets that are very long.

There is nothing like this.  All tests are equally iportant.  
Currenty I'm splitting really by number of actors and arbiters (so tests). Whcih is probably the moust precisse way it can be done, except really run that. ut individual testcases really do not have constant timeframe.  I can go even more deep, and really leave it run for the 23 days,  and try to split it by real time frame. (I do not want!!!-) )

> 
>     3. Consider running these tests in a separate test job, on a less regular basis, 

Thats what the split to individual targets is doing, isnt it? Less regularly/shorter time/ dev x always - that  is up to you. Most likely I would like to have short brainstorming  gcall on this topic. My expereicne with jcstress and your expereicne with aqa and adoptium HW are hard to mix together.

> or based on certain types of OpenJDK code changes.

This is beyond my expereince on both fields. Unless you really know how to do that, I would leave it in future work.

**Comment by smlambert** [comment]
Yes, apologies, I am making notes for myself in the comment I left, not expecting you to have a response.  

I am not convinced that the jcstress tests should be run in our regular builds, as I have no metrics or data regarding their effectiveness in finding defects when compared against the amount of resources they take to run.

**Comment by smlambert** [comment]
Yes, once I review the generator and playlist more fully, I will want to have a quick call, likely Friday looking at the calendar.

**Comment by judovana** [comment]
> Yes, apologies, I am making notes for myself in the comment I left, not expecting you to have a response.
> 
Thats perfectly ok :)

> I am not convinced that the jcstress tests should be run in our regular builds, as I have no metrics or data regarding their effectiveness in finding defects when compared against the amount of resources they take to run.


They were extensively  catching hard to find issues for several years, but last two.,maybe three years they are completely silent. Most of the bugs were found during shenandaoh and aarch64  development, and jfr backporting (with jfr on, which is not applicable this case anyway)

As they are concurrency tests, the issues were very often not deterministic, but the report was usually precise enough to guide us. The non deterministic nature unluckily imply the need of long duration (longer duration, more likley the issue will be hit (and also more cores is implied by this)).

generally the nature of tests is really unique, and is covering very huge are not covered elsewhere.


> 
> The initial reason we added 'a short set of jcstress tests' initially was to show developers how to run and adapt the 

That is interesting, but this feature is in jcstress itself. Once CI hits the issue, the exact test is printed out, so developer will then loop only that single test, and as single test is in milliseconds, the develpre can loop it and be sure they hit the issue.

That circles back to CI, being capable to hit the issue, thus run all.

> tests for their own personal use and to only run a very short few hours of jcstress in our regular runs to ensure they kept 'working', not to exercise the exhaustive set regularly. The way the current PR stands, all of the test targets will get triggered as part of our EA builds (occuring weekly), consuming likely more resources than we have or wish to devote to these tests.

Yes, current case is some 24hours of HW time, only possibly able to run in parallel in 138 vms/cotnianers/chroots whatever. I assume it is no go.
> 
>     4. Create/generate documentation. Parameterize the test target name and create a jcstress_custom target to allow developers to select what they run based on the changes they are making to the OpenJDK codebase.

After this discussion, I'm even more inclined to really simply run whole jcstress, with -tb 3hours daily/weekly, and  3x-4x more  on rampdowns or simialr events . 

For the parts of jdk itself, this feature in jcstress itself. I can generate all 4000 targets  (really per case) to enable the uttermost granularity if aqavit is about to help with those, or really strictly by top level group (soem 400 targets, with 1-2000 tests each), but am not sure how useful ti would be.
In the moment there will be mechanism to map individual tests to jdk changesets, then is if course getting absolutely another dimension.

**Comment by smlambert** [comment]
> After this discussion, I'm even more inclined to really simply run whole jcstress, with -tb 3hours daily/weekly, and 3x-4x more on rampdowns or simialr events .

Yep, let's settle on a plan after a Friday call.  I will book something in the calendar to make sure time is reserved.

**Comment by judovana** [comment]
Hmm.. small change in thinking, despite all assuring I had, I'm unable to make `-tb` work.:  https://bugs.openjdk.org/browse/CODETOOLS-7903750?focusedId=14681341&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14681341

**Comment by smlambert** [comment]
Summary of our Friday discussion ( thank you for the chat @judovana ):
- Generate targets based on jcstress groups and create them as `<disable>` targets so they are there for developer use 
  - Add some doc, and potentially a lightning talk to describe the tests and how to run the disabled targets
- Add a single target for running jcstress which is enabled to run with time budget 1 hour (even though it may not be honoured)
  - Before merging, we will test the PR with these changes on all platforms to monitor the behaviour of the enabled target, if any platforms behave 'poorly' (as in, hang or timeout or crash), we will exclude on those platforms for now in order to merge the PR and with the idea to investigate platform failures under a separate issue

**Comment by judovana** [comment]
first "-tb 1h" all grinder run https://ci.adoptium.net/view/Test_grinder/job/Grinder/10399/console
Am wondering how -tb will be honored, and how resutls will be saved

**Comment by judovana** [comment]
Attemt 2 on intel: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10410

**Comment by smlambert** [comment]
Rebuild with 10410 with TIME_LIMIT=50 to see how long it takes to run: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10411/

The default TIME_LIMIT is 10 hours, which 10410 hits and then is aborted.

**Comment by judovana** [comment]
thanx!

It seems as bad as the aarch64 I got at first:

```
07:27:44  (Time: overtime 01:33:25, 1 tests in flight, 30 ms per test)
07:27:44  (Sampling Rate: N/A)
07:27:44  (JVMs: 0 starting, 1 running, 0 finishing)
07:27:44  (CPUs: 4 configured, 8 allocated)
07:27:44  (Results: 3030696 planned; 0 passed, 0 failed, 0 soft errs, 3506 hard errs)
```

And it have jsut 8 cores...

**Comment by judovana** [comment]
> thanx!
> 
> It seems as bad as the aarch64 I got at first:
> 
> ```
> 07:27:44  (Time: overtime 01:33:25, 1 tests in flight, 30 ms per test)
> 07:27:44  (Sampling Rate: N/A)
> 07:27:44  (JVMs: 0 starting, 1 running, 0 finishing)
> 07:27:44  (CPUs: 4 configured, 8 allocated)
> 07:27:44  (Results: 3030696 planned; 0 passed, 0 failed, 0 soft errs, 3506 hard errs)
> ```
> 
> And it have jsut 8 cores...

filled https://bugs.openjdk.org/browse/CODETOOLS-7903754

**Comment by judovana** [comment]
And worse:

```
14:31:03  
14:31:03    Messages:
14:31:03      Unrecoverable error while running
14:31:03      java.lang.IllegalStateException: Failed: 22
14:31:03      	at org.openjdk.jcstress.os.AffinitySupport$Linux.set(AffinitySupport.java:135)
14:31:03      	at org.openjdk.jcstress.os.AffinitySupport$Linux.bind(AffinitySupport.java:108)
14:31:03      	at org.openjdk.jcstress.os.AffinitySupport.bind(AffinitySupport.java:37)
14:31:03      	at org.openjdk.jcstress.tests.seqcst.volatiles.S1__S1_S2__S2__S2_S1_Test_jcstress$JcstressThread_actor3.jcstress_iteration_actor3(S1__S1_S2__S2__S2_S1_Test_jcstress.java:556)
14:31:03      	at org.openjdk.jcstress.tests.seqcst.volatiles.S1__S1_S2__S2__S2_S1_Test_jcstress$JcstressThread_actor3.internalRun(S1__S1_S2__S2__S2_S1_Test_jcstress.java:549)
14:31:03      	at org.openjdk.jcstress.infra.runners.CounterThread.run(CounterThread.java:44)
14:31:03  
14:31:03  (Time: 1d+overtime 08:36:44, 1 tests in flight, 30 ms per test)
14:31:03  (Sampling Rate: N/A)
14:31:03  (JVMs: 0 starting, 1 running, 0 finishing)
14:31:03  (CPUs: 4 configured, 8 allocated)
14:31:03  (Results: 3030696 planned; 0 passed, 0 failed, 0 soft errs, 45993 hard errs)
```

Next to being some 2400% late, ot started to fail.

**Comment by judovana** [comment]
Rerun againm: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10432/console ; I kept the TIME_LIMIT=50 
```
14:39:51  (Time: 00:58:55 left, 1 tests in flight, 30 ms per test)
14:39:51  (Sampling Rate: 82.80 K/sec)
14:39:51  (JVMs: 0 starting, 1 running, 0 finishing)
14:39:51  (CPUs: 8 configured, 8 allocated)
14:39:51  (Results: 491088 planned; 55 passed, 0 failed, 0 soft errs, 0 hard errs)
```

Looks healthy

**Comment by judovana** [comment]
> Rerun againm: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10432/console ; I kept the TIME_LIMIT=50
> 
> ```
> 14:39:51  (Time: 00:58:55 left, 1 tests in flight, 30 ms per test)
> 14:39:51  (Sampling Rate: 82.80 K/sec)
> 14:39:51  (JVMs: 0 starting, 1 running, 0 finishing)
> 14:39:51  (CPUs: 8 configured, 8 allocated)
> 14:39:51  (Results: 491088 planned; 55 passed, 0 failed, 0 soft errs, 0 hard errs)
> ```
> 
> Looks healthy



> Rerun againm: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10432/console ; I kept the TIME_LIMIT=50
> 
> ```
> 14:39:51  (Time: 00:58:55 left, 1 tests in flight, 30 ms per test)
> 14:39:51  (Sampling Rate: 82.80 K/sec)
> 14:39:51  (JVMs: 0 starting, 1 running, 0 finishing)
> 14:39:51  (CPUs: 8 configured, 8 allocated)
> 14:39:51  (Results: 491088 planned; 55 passed, 0 failed, 0 soft errs, 0 hard errs)
> ```
> 
> Looks healthy

ok, was killed after 50hours.

**Comment by judovana** [comment]
I had noted that non of the tests is keeping artifacts. I guess htat is not intentional.

**Comment by judovana** [comment]
Despite usptram speaking differently, I think it is crucial to limit cores to 4. its the only way I saw it end in real time, and still do probably all reasonable combinations

**Comment by judovana** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10462/  with cores limited to `-c 4` Before reaching this, I had 4 aborted builds which were just hard errors. That will need another investigations

**Comment by judovana** [comment]
> I had noted that non of the tests is keeping artifacts. I guess htat is not intentional.

@smlambert  Any thoughts about that? jcstress2024 is generating tarball**s** with results

**Comment by smlambert** [comment]
> Any thoughts about that? jcstress2024 is generating tarballs with results

If the test aborts, I do not think we attempt to keep artifacts.  Will have to check.  
Or are you referring to a test that runs to completion and does not keep artifacts?

**Comment by judovana** [comment]
on latest playbook, nothing finished so far.  I dont know what are the habbits, if builds fails  or is aborted (becasue there is no reason to run sdomehting, which print sut "error" since the launch, maybe the results shoudl be gathered anyway?
But tbh, I'm not sure if results are produced by jcsrtess itself when it is aborted in such way (if it would run in VM, it would have no chance to do anythgn anyway) 

So yes, in aborted run. Nothing nowhere I guess.

**Comment by judovana** [comment]
```
20:22:46  (Time: overtime 03:47:37, 2 tests in flight, 30 ms per test)
20:22:46  (Sampling Rate: 68.79 K/sec)
20:22:46  (JVMs: 0 starting, 1 running, 1 finishing)
20:22:46  (CPUs: 4 configured, 4 allocated)
20:22:46  (Results: 3030696 planned; 19342 passed, 0 failed, 0 soft errs, 0 hard errs)
```

not good

**Comment by judovana** [comment]
`-c 3` was killed after two days: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10498/r

Now trying `-c 2` https://ci.adoptium.net/view/Test_grinder/job/Grinder/10501/

**Comment by smlambert** [comment]
@judovana - as we wait for your suggested upstream changes to jcstress, we could consider also disabling the jcstress.all target so we can merge this PR.  Once changes upstream are accepted and we can re-enable the jcstress.all target with appropriate settings so it can be run in a timely manner.

**Comment by judovana** [comment]
```
10:30:56  (Time: overtime 16:28:58, 2 tests in flight, 30 ms per test)
10:30:56  (Sampling Rate: 135.63 K/sec)
10:30:56  (JVMs: 0 starting, 1 running, 0 finishing)
10:30:56  (CPUs: 2 configured, 2 allocated)
10:30:56  (Results: 337416 planned; 88910 passed, 0 failed, 0 soft errs, 0 hard errs)
```
Looks better then usually. 

My upstream changes are not going to solve it. They are walking around, trying to be a bit more precise, but not lowering the total time.   Give me a bt more time please. I still keep experimenting above it, and maybe it will go somewhere.

**Comment by judovana** [comment]
Killed by bug in infra:
```
11:13:16  (Time: overtime 17:11:18, 2 tests in flight, 30 ms per test)
11:13:16  (Sampling Rate: 135.71 K/sec)
11:13:16  (JVMs: 0 starting, 1 running, 0 finishing)
11:13:16  (CPUs: 2 configured, 2 allocated)
11:13:16  (Results: 337416 planned; 92563 passed, 0 failed, 0 soft errs, 0 hard errs)
11:13:16  
11:13:22  Cannot contact test-docker-ubi9-x64-1: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
11:19:55  wrapper script does not seem to be touching the log file in /home/jenkins/workspace/Grinder@tmp/durable-82ef8d76
11:19:55  (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
``` 

restart:  https://ci.adoptium.net/view/Test_grinder/job/Grinder/10505/

**Comment by judovana** [comment]
```
10:47:24  (Time: 1d+overtime 21:19:37, 1 tests in flight, 30 ms per test)
10:47:24  (Sampling Rate: 78.73 K/sec)
10:47:24  (JVMs: 0 starting, 1 running, 0 finishing)
10:47:24  (CPUs: 2 configured, 2 allocated)
10:47:24  (Results: 337416 planned; 162967 passed, 0 failed, 0 soft errs, 0 hard errs)
```

Looks good - for the test-  but not good for timeout. Anyway I think it is the way to go. To limit the `-c` to 2 and give smallest possible time budget. But still we must count with aprox 3 days on slowest machines.

**Comment by judovana** [comment]
As https://ci.adoptium.net/view/Test_grinder/job/Grinder/10505 was intel, trying now arm with `-c 2`:
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10506/

**Comment by judovana** [comment]
All targets are now disabled, and cores are set to default of 2.

https://ci.adoptium.net/view/Test_grinder/job/Grinder/10679/console

**Comment by judovana** [comment]
Will add  also `-Djcstress.console.printIntervalMs` handling

**Review by smlambert — APPROVED** [review]
Thanks @judovana - I will merge it now with all targets disabled.  In that way it can be used by running with `TARGET=disabled.jcstress.xxxx` if needed, and returned to in future when some options addressed in upstream jcstress repo.

**Comment by judovana** [comment]
wait a sec, this is funny

**Comment by judovana** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10680/ had  just `-Djcstress.console.printIntervalMs=3600000` set instead of default (-Djcstress.console.printIntervalMs=15000) And it have some unexpected impact:

Original  ETA and samplign rate
```
20:38:07  (Time: 00:59:59 left, 1 tests in flight, 30 ms per test)
20:38:07  (Sampling Rate: 147.79 K/sec)
20:38:07  (JVMs: 0 starting, 1 running, 0 finishing)
20:38:07  (CPUs: 2 configured, 2 allocated)
20:38:07  (Results: 337416 planned; 1 passed, 0 failed, 0 soft errs, 0 hard errs)
```
new ETA and sampling rate:
```
21:28:01  (Time: 11d+17:05:01 left, 1 tests in flight, 2969 ms per test)
21:28:01  (Sampling Rate: 7.62 M/sec)
21:28:01  (JVMs: 0 starting, 1 running, 0 finishing)
21:28:01  (CPUs: 2 configured, 2 allocated)
21:28:01  (Results: 337416 planned; 94 passed, 0 failed, 0 soft errs, 0 hard errs)
```

Sampling rate is much higher, but Eta is absolutely out.  And looking to the passed tests, counting, the delay is real.
The

**Comment by judovana** [comment]
Gosh, I had reset time budget. Fixing

**Comment by judovana** [comment]
ok, fixed. https://ci.adoptium.net/view/Test_grinder/job/Grinder/10681/console looks good.

I'm not aware of any more issues (except the time needed). Feel free to merge.  I will now move to next step in https://github.com/adoptium/aqa-tests/issues/5261 - to improve https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.xml so it is using [jcstress-20240222.jar](https://ci.adoptium.net/view/Dependencies/job/dependency_pipeline/1255/artifact/jcstress/jcstress-20240222.jar) from  dependency pipeline. (it will need to regenerate te playlist.xml once done)

**Review by sophia-guo — APPROVED** [review]

**Comment by judovana** [comment]
hmm.. that https://ci.adoptium.net/view/Test_grinder/job/Grinder/10681/console looks good! It is in the half after twelve hours!

**Comment by judovana** [comment]
Just for record, the https://ci.adoptium.net/view/Test_grinder/job/Grinder/10681/console finished in 20 hours :)

I think that one can be deployed under some circumsatnces.

**Pull request merged**
