### PR TITLE
(v0.9.6-release) Update branches in testenv.properties

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: Lan Xia <Lan_Xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6309/

**Comment by llxia** [comment]
FYI @AdamBrousseau @pshipton

**Review by smlambert — APPROVED** [review]

**Comment by pshipton** [comment]
The openj9 branch didn't get set.

**Comment by llxia** [comment]
ah, sorry, not sure how I missed it. I will have a PR to update it.

**Comment by llxia** [comment]
PR for Openj9 branch: https://github.com/adoptium/aqa-tests/pull/4236

**Pull request merged**
