### PR TITLE
Create universal function to retry command in get.sh

### PR DESCRIPTION
**Pull request by renfeiw**
- use retry function on git clone openj9

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
tested in Grinder_TKG/1615 1616 1617
retry output:
```
19:01:03  git clone --depth 1 -b master abc
19:01:03  fatal: repository 'abc' does not exist
19:01:03  error code: 128. Sleep 300 secs, then retry 1...
19:06:16  check for openj9. If found, the file will be removed.
19:06:16  git clone --depth 1 -b master abc
19:06:16  fatal: repository 'abc' does not exist
19:06:16  error code: 128. Sleep 300 secs, then retry 2...
19:11:16  check for openj9. If found, the file will be removed.
19:11:16  git clone --depth 1 -b master abc
19:11:16  fatal: repository 'abc' does not exist
19:11:16  error code: 128. Sleep 300 secs, then retry 3...
19:16:15  check for openj9. If found, the file will be removed.
19:16:15  git clone --depth 1 -b master abc
19:16:15  fatal: repository 'abc' does not exist
19:16:15  error code: 128. Sleep 300 secs, then retry 4...
19:21:14  check for openj9. If found, the file will be removed.
19:21:14  git clone --depth 1 -b master abc
19:21:14  fatal: repository 'abc' does not exist
19:21:14  error code: 128. Sleep 300 secs, then retry 5...
19:26:11  check for openj9. If found, the file will be removed.
19:26:11  git clone --depth 1 -b master abc
19:26:11  fatal: repository 'abc' does not exist
19:26:11  git clone error code: 128
```

**Comment by llxia** [comment]
Could you also test on windows, aix, and zos? Thanks

**Comment by llxia** [comment]
FYI @pshipton

**Comment by renfeiw** [comment]
Tested for both success and failure case:
zos: Grinder_TKG/1618, 1619
windows: Grinder_TKG/1620, 1621
aix: Grinder/23405, Grinder/23406

**Review by llxia — APPROVED** [review]
Thanks @renfeiw

**Review by smlambert — APPROVED** [review]

**Pull request merged**
