### PR TITLE
add ProblemList_openjdk21.txt for Microsoft

### PR DESCRIPTION
**Pull request by gdams**
We noticed this was missing so I've copied the Adoptium problem list. Not sure if I need to copy this to other vendor directories too?

### CODE REVIEW

**Comment by sophia-guo** [comment]
Yes, the problem list is needed per jdk version for all vendors. However, if there are no specific tests need to be excluded per vendor an empty problem list file as a placeholder should be enough.

**Review by sophia-guo — APPROVED** [review]

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
@sophia-guo - I was not aware that the vendor problem list file was actually needed, I thought it was used if it is there and not used if not present.

**Comment by sophia-guo** [comment]
> I was not aware that the vendor problem list file was actually needed, I thought it was used if it is there and not used if not present.

We can definitely enhance this.

**Comment by gdams** [comment]
> @sophia-guo - I was not aware that the vendor problem list file was actually needed, I thought it was used if it is there and not used if not present.

Yeah it currently produces an error if it doesn't exist

**Comment by sophia-guo** [comment]
Issue address this. https://github.com/adoptium/aqa-tests/issues/4790

**Pull request merged**
