### PR TITLE
Update triggerGrinder.groovy file

### PR DESCRIPTION
**Pull request by amir-waheed**
This update moves the the launch grinder function outside the node.

Fixes: #3347

Signed-off-by: Abeer Waheed <amir2@ualberta.ca>

### CODE REVIEW

**Comment by amir-waheed** [comment]
@llxia I have removed launch grinder outside the node and it seems to be building ok. https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/63/console
For my next task, I am going to work on letting the user decide the parameters for the build, however I am still a little confused about what the task entails. Would it be possible for you to explain it again? 
I also noticed that the build is now taking > 40 minutes after adding the 2 new parameters, I was wondering why that is. 
Thanks.

**Comment by llxia** [comment]
> I also noticed that the build is now taking > 40 minutes after adding the 2 new parameters, I was wondering why that is.

your build is getting slow is because you have `"PLATFORM": "all"` in your output.json. With Jocelyn's change https://github.com/adoptium/aqa-tests/pull/3317, it will try to trigger build on each platform. 


> For my next task, I am going to work on letting the user decide the parameters for the build, however I am still a little confused about what the task entails. Would it be possible for you to explain it again?

Please see https://github.com/adoptium/aqa-tests/issues/3347

**Comment by llxia** [comment]
Thanks @amir-waheed . A couple of things (below):

- Could you provide your testing links?
- We need to add the logic of triggering the python scripts, not using the sample output.json anymore. Could you add it?
- Please remove the sample output.json.

**Comment by amir-waheed** [comment]
@llxia Here are the links for the old tests that I ran on demo output.json (had only 1 closed issues with parameters 17, hotspot):
1. https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/78/parameters/
2. https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/79/parameters/
3. https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/80/parameters/
4. https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/83/parameters/ 
5. 1, 2, 3 don't trigger any test and 4 triggers the test as both JDK_IMPL and JDK_VERSION match I aborted it as it was going to take > 1 hour to finish.

I have added logic to first trigger generateDisabledTestList.json and then triggering issue_tracker. However, when I run issue_status.py on the output of generateDisabledTestList.json on my computer, output.json is not generated as it prints 'An exception occurred! Url is invalid' for every test in ProblemsList.json. I did try to test with the new changes and it shows that there is an error in generateDisabledTestList.json. Here is the link for the console output of the test: 
https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/86/console

I have also removed output.json file.

**Comment by llxia** [comment]
Thanks @amir-waheed . Could you remove ProblemList.json and __pycache__/generateDisabledTestListJson.cpython-39.pyc?

**Review by llxia — APPROVED** [review]

**Review by smlambert — APPROVED** [review]
thanks @amir-waheed !

**Pull request merged**
