### PR TITLE
Jenkins: Prepend Artifacotry buildInfo.name with sys-rt

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1402

**Comment by llxia** [comment]
Grinder/28618/

**Review by llxia — APPROVED** [review]
Thanks @AdamBrousseau

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Pull request merged**
