### PR TITLE
Add reference repo for git clone openjdk repos

### PR DESCRIPTION
**Pull request by llxia**
related: runtimes/backlog/issues/815
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
- cache folder does not exist (warning message): https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5033/
```
00:01:34.175       [exec] git clone --depth 1 -q --reference-if-able /home/jenkins/openjdk_cache -b dev https://github.com/adoptium/jdk8u.git openjdk-jdk
00:01:34.175       [exec] info: Could not add alternate for '/home/jenkins/openjdk_cache': reference repository '/home/jenkins/openjdk_cache' is not a local repository.
```
- cache folder exists and is up to date (no warning message): Grinder/25185
```
00:01:24.671       [exec] git clone --depth 1 -q --reference-if-able /home/jenkins/openjdk_cache  https://github.com/ibmruntimes/openj9-openjdk-jdk11.git openjdk-jdk
00:01:44.416       [exec] Check sha in openjdk-jdk and store the info in /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/SHA.txt
```

**Comment by llxia** [comment]
FYI @pshipton @AdamBrousseau

**Comment by AdamBrousseau** [comment]
I didn't know "if-able" was a thing. Cool!
We might want to confirm if that extra option was added in a more recent git version than what we have on our machines.
Also, on the openj9 farm machines, the cache has many repos and we can add more if needed. So you could just call it repo cache instead of openjdk repo cache.

**Comment by llxia** [comment]
I removed OPENJDK in the variable name.
retested: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5034/

**Comment by llxia** [comment]
@sxa do we have git 2.11.4+ on all Adopt test machines?

**Comment by llxia** [comment]
@sxa Could you please confirm we have git 2.11.4+ on all Adopt test machines? Thanks

**Comment by llxia** [comment]
[Prerequisites.md](https://github.com/adoptium/aqa-tests/blob/master/doc/Prerequisites.md) is updated.

**Review by smlambert — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
