### PR TITLE
Update JCK_CMD_TEMPLATE to reduce duplicate

### LINKED ISSUE #3639: Cleanup duplicate jck command information
Each jck command includes jck version and jckRoot informations, which can be encapsulated to JCK_CMD_TEMPLATE to make command clear and reduce maintenance.

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #3639 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Grinder temurin-compliance/job/Grinder/1311/

**Review by smlambert — APPROVED** [review]

**Comment by sophia-guo** [comment]
@Mesbah-Alam could you please take a review? Thanks.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by Mesbah-Alam** [comment]
Thanks for this work, @sophia-guo - the world is a bit cleaner now! 

Tested : Grinder/23742.

**Pull request merged**
