### PR TITLE
Re-enable JTReg test thrinfo01

### PR DESCRIPTION
**Pull request by dipak-bagadiya**
Re-enable JTReg test thrinfo01

Test had been fixed by https://github.com/eclipse-openj9/openj9/pull/16376

Signed-off-by: Dipak Bagadiya dipak.bagadiya@ibm.com

### CODE REVIEW

**Comment by llxia** [comment]
Related: https://github.com/eclipse-openj9/openj9/issues/16226

**Review by llxia — APPROVED** [review]

**Review by dipak-bagadiya — COMMENTED** [review]
@fengxue-IS @babsingh - please review

**Comment by fengxue-IS** [comment]
please update the commit message to something like
```
re-enable JTReg test thrinfo01

Test has been fix by https://github.com/eclipse-openj9/openj9/pull/16376

Signed-off-by: <your email>
```

Please also update the title of this PR. Convension is that the reference to openj9 PR should be part of the message, not title.

**Comment by dipak-bagadiya** [comment]
@fengxue-IS -> I updated the title and comment as needed.

**Review by Mesbah-Alam — COMMENTED** [review]
LGTM.

**Review by Mesbah-Alam — APPROVED** [review]

**Comment by llxia** [comment]
@dipak-bagadiya could you also update the commit message? Thanks

**Comment by babsingh** [comment]
Also, it should be past tense: Test has been **fixed by** https://github.com/eclipse-openj9/openj9/pull/16376.

**Comment by dipak-bagadiya** [comment]
@fengxue-IS @babsingh @llxia  I updated the commit message and made the past tense in the description part.

**Pull request merged**
