### PR TITLE
Added an exclusion statement

### PR DESCRIPTION
**Pull request by JaniPaasiluoto**

### CODE REVIEW

**Comment by JaniPaasiluoto** [comment]
Could you @sophia-guo accept the PR? Thanks.

**Comment by smlambert** [comment]
@JaniPaasiluoto - the ECA validation check is still failing.  Can you please check your Eclipse profile to confirm that your status shows that you have signed the [ECA](https://www.eclipse.org/legal/ECA.php)... the output of the validation check indicates that the email its verifying is jani.paasiluoto@****.fi - is that the same address associated with your github ID and the commits in this PR?

**Comment by smlambert** [comment]
ECA guidance at: 
https://github.com/adoptium/documentation/blob/main/documentation-documentation/eca-sign-off.adoc

**Comment by smlambert** [comment]
Closing this PR as stale.  If you would like to return to it, please sign the ECA agreement first.  Thanks.

**Pull request closed without merging**
