### PR TITLE
openjdk: Add hotspot tier1 targets

### PR DESCRIPTION
**Pull request by zzambers**
This adds [hotspot tier1 targets](https://github.com/openjdk/jdk/blob/84751cbfddf69bd9ed6bc5c39f8e056009440331/test/hotspot/jtreg/TEST.groups#L568). They only run limited set of tests from each group, without long running tests. Having these targets is usefull to be able to run tier1 style testing using aqa targets.
(They may potentially be ran as part of `sanity.openjdk`)

**Testing:**
jdk 21 / x86-64_linux
hotspot_tier1_compiler: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10991/)
hotspot_tier1_runtime: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10990/)
hotspot_tier1_gc: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10949/)
hotspot_tier1_serviceability: [OK](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10992/)
hotspot_tier1_common: [8 FAILURES](https://ci.adoptium.net/view/Test_grinder/job/Grinder/10947/)
```
gtest/GTestWrapper.java.GTestWrapper
gtest/LargePageGtests.java#use-large-pages-1G.LargePageGtests_use-large-pages-1G
gtest/LargePageGtests.java#use-large-pages-sysV.LargePageGtests_use-large-pages-sysV
gtest/LargePageGtests.java#use-large-pages.LargePageGtests_use-large-pages
gtest/MetaspaceGtests.java#balanced-no-ccs.MetaspaceGtests_balanced-no-ccs
gtest/NMTGtests.java#nmt-detail.NMTGtests_nmt-detail
gtest/NMTGtests.java#nmt-off.NMTGtests_nmt-off
gtest/NMTGtests.java#nmt-summary.NMTGtests_nmt-summary
```
All targets but `hotspot_tier1_common` are basically subsets of [existing hotspot targets](https://github.com/adoptium/aqa-tests/pull/5624), so no surprises were expected there. However `hotspot_tier1_common` shows failures of gtest tests. Seems like these are not supported yet in adoptium.

### CODE REVIEW

**Comment by zzambers** [comment]
Filled issue for gtest problem: https://github.com/adoptium/temurin-build/issues/3956

**Comment by smlambert** [comment]
Sampling some other platforms/versions:
aix 21: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10996
win64 11: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10997/
aarch64 mac 24: https://ci.adoptium.net/view/Test_grinder/job/Grinder/10998

**Comment by zzambers** [comment]
I have disabled `hotspot_tier1_common` for now, as it requires gtest support.

**Review by smlambert — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
I'm finding several tests that are failing on Windows from hotspot_tier1_runtime_0 and hotspot_tier1_serviceability_0, 
i've tried running them numerous times on several nodes as part of : https://github.com/adoptium/ci-jenkins-pipelines/issues/1104#issuecomment-2393086371

I suspect they will need excluding, maybe worth analysing to exclude before next week's release, as it's quite time consuming triaging them.

I shall try and get a list of the failing tests.

**Comment by andrew-m-leonard** [comment]
Raised: https://github.com/adoptium/aqa-tests/issues/5671

**Comment by andrew-m-leonard** [comment]
Raised: https://github.com/adoptium/aqa-tests/issues/5672

**Pull request merged**
