### PR TITLE
Initial update of Quarkus

### PR DESCRIPTION
**Pull request by sophia-guo**
Disable for jdk8
Update to 2.7.5.Final
Disable some failed tests per jdk

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Minimal version 11 is required. https://github.com/quarkusio/quarkus/blob/2.7.5.Final/pom.xml#L50-L54

**Comment by sophia-guo** [comment]
Grinder:
jdk17: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/643/
jdk11: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/638/

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
👍

**Pull request merged**
