### PR TITLE
Allow user to set OPENLIBERTY_SHA

### PR DESCRIPTION
**Pull request by llxia**

### CODE REVIEW

**Comment by llxia** [comment]
[Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33513/)
[Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33524/)

**Review by renfeiw — APPROVED** [review]
LGTM

**Review by LongyuZhang — APPROVED** [review]
LGTM

**Review by smlambert — COMMENTED** [review]
This is likely a dangerous precedent (for parameter bloat).  Wonder if there is a way to utilize test.properties or APPLICATION_OPTIONS for this type of finessing.

**Comment by llxia** [comment]
I agree, we should look into it and find a better way.

**Pull request merged**
