### PR TITLE
Update JDK18 openj9 test exclusion list w/ JDK17 version content

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Copy content from `ProblemList_openjdk17-openj9.txt`.

Note: this is to exclude JDK18 test failures https://github.com/eclipse-openj9/openj9/issues/7249 and others.

fyi @tajila @pshipton 

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
@llxia could you arrange a review?

**Comment by Mesbah-Alam** [comment]
Should it be `JDK18` in the title?

**Comment by JasonFengJ9** [comment]
Updated PR title.

**Review by llxia — APPROVED** [review]
LGTM

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Pull request merged**
