### PR TITLE
Add exclude files for Java 20

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Add exclude files for Java 20

Copied from `ProblemList_openjdk19.txt` & `ProblemList_openjdk19-openj9.txt`.

related to https://github.com/eclipse-openj9/openj9/pull/15528

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
@llxia @Mesbah-Alam could you please review?

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @JasonFengJ9 !

**Comment by JasonFengJ9** [comment]
Thanks @smlambert

**Pull request merged**
