### PR TITLE
Add SCC/AOT test with varying heap size

### PR DESCRIPTION
**Pull request by Akira1Saitoh**
Add MiniMix_aot_5m for testing SCC/AOT with varying heap size.

Signed-off-by: Akira Saitoh <saiaki@jp.ibm.com>
Co-authored-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/458/

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/468/

**Review by llxia — APPROVED** [review]
Thanks @Akira1Saitoh

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Pull request merged**
