### PR TITLE
support surefire or junit reports

### LINKED ISSUE #5791: External tests junit or surefire reports are not archived with KEEP_REPORTDIR=ture
If external test have junit or surefire reports they are expected to be kept or archived with KEEP_REPORTDIR=ture ( no matter if job passes or failed)

Current with KEEP_REPORTDIR=true, no test results have been kept or archived.

https://ci.adoptium.net/job/Grinder/11922/
https://ci.adoptium.net/job/Grinder/11923/

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix #5791

### CODE REVIEW

**Comment by sophia-guo** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/11933/

**Comment by karianna** [comment]
Linter failures

**Comment by sophia-guo** [comment]
Linter issue is here https://github.com/adoptium/aqa-tests/issues/5787

**Review by smlambert — APPROVED** [review]
thanks @sophia-guo

**Review by karianna — APPROVED** [review]

**Pull request merged**
