### PR TITLE
Re-enable superProtectedMethod lambda tests

### PR DESCRIPTION
**Pull request by tajila**
Re-enable superProtectedMethod lambda tests

Can be renabled once issue https://github.com/eclipse-openj9/openj9/issues/11783 is closed

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
@pshipton ^^

**Comment by karianna** [comment]
@tajila Needs a rebase.

**Comment by smlambert** [comment]
This PR should also be switched to Draft as it depends on a PR that is in Draft (https://github.com/eclipse/openj9/pull/11793)

**Comment by karianna** [comment]
@tajila will need a rebase.

**Comment by smlambert** [comment]
NOTE:  @karianna - this PR states it DEPENDS on an openj9 PR that is still in draft.  It can be rebased, but NOT merged until the dependent PR is out of draft and merged.

**Comment by smlambert** [comment]
@tajila - I see that the openj9 issue is closed, should this PR now be rebased/merged or closed?

**Comment by tajila** [comment]
The PR was closed because we are going to address the issue by switching to ojdk_mh. The issue is still open, https://github.com/eclipse-openj9/openj9/issues/11783

**Comment by tajila** [comment]
Ive updated the description

**Comment by JasonFengJ9** [comment]
Note: https://github.com/eclipse-openj9/openj9/issues/11783 has been verified & closed.
This test need to be enabled for JDK17 at `ProblemList_openjdk17-openj9.txt` as well.

fyi @tajila

**Comment by pshipton** [comment]
@tajila can you update this to unexclude for jdk17 and take it out of draft pls.

**Comment by tajila** [comment]
@pshipton `java/lang/invoke/lambda/superProtectedMethod/SuperMethodTest.java` doesnt exist in `aqa-tests/openjdk/excludes/ProblemList_openjdk17-openj9.txt`

**Comment by tajila** [comment]
> This test need to be enabled for JDK17 at ProblemList_openjdk17-openj9.txt as well.

@JasonFengJ9  is this the right excludes file to look at `aqa-tests/openjdk/excludes/ProblemList_openjdk17-openj9.txt` ?

**Comment by pshipton** [comment]
Sorry. I expect this can just be closed then, since jdk16 is obsolete now. Jack already fixed it in https://github.com/adoptium/aqa-tests/pull/2843.

**Comment by JasonFengJ9** [comment]
> is this the right excludes file to look at aqa-tests/openjdk/excludes/ProblemList_openjdk17-openj9.txt ?

Yes, it is the correct JDK17 exclude file.
The test in question has been enabled via https://github.com/adoptium/aqa-tests/pull/2843/files just as per https://github.com/adoptium/aqa-tests/pull/2210#issuecomment-920958183

**Pull request closed without merging**
